### ISSUE TITLE
I made a thing

### ISSUE THREAD

**Issue by williammalo** [docpad/docpad#1015]
I made a docpad plugin for babel http://babeljs.io

https://www.npmjs.com/package/docpad-plugin-babel
https://github.com/williammalo/docpad-plugin-babel

Could it be added as an official plugin?

**Comment by jking90** [comment]
Your plugin does not work. Since you added `babel-core` as a dev dependency, it does not get installed when the plugin is installed. There are several other problems with this plugin, but that's the one that will prevent it from working at all.

**Comment by williammalo** [comment]
ah thanks, I'll fix that, it's my first docpad plugin, I'm a bit of a noob.

**Comment by williammalo** [comment]
@jking90 fixed!

**Comment by jking90** [comment]
@williammalo I opened a pull request with a few improvements.

To get your plugin added on the site, fork the documentation and add you plugin [here](https://github.com/docpad/documentation/blob/master/community/plugins.html.md), then open a pull request.

**Comment by williammalo** [comment]
@jking90 Thanks! I will do that right now!
edit:https://github.com/docpad/documentation/pull/177

**Comment by balupton** [comment]
Merged :) Cool plugin!
