### ISSUE TITLE
Error running docpad generate from Wercker

### ISSUE THREAD

**Issue by neilcampbell** [docpad/docpad#1028]
Hi guys,
Just noticed a small issue when running a build on Wercker using `node ./node_modules/docpad/bin/docpad --env static --silent generate`.

Which results in the following error: `process.stdin.end is not a function`

PR incoming with the fix.

**Comment by neilcampbell** [comment]
And the PR https://github.com/docpad/docpad/pull/1029

**Comment by balupton** [comment]
@neilcampbell any idea why stdin is not defined?

**Comment by neilcampbell** [comment]
@balupton Yeah I have no idea why! I might check to see if this is still the behaviour, and dig a little deeper. Will update with my findings.

**Comment by balupton** [comment]
@neilcampbell cool thank you

**Comment by neilcampbell** [comment]
Thanks for you help with this @balupton!

The problem still exists in Wercker using the latest Node (6.2.2). Looking at the Node docs there is actually no `end()` defined for a readable stream (which stdin is) only a writeable stream. See https://nodejs.org/api/stream.html. When I log the stdin object from my local machine I get a ReadStream which contains both _readableState and _writableState keys, however from Wercker I get a ReadStream object with only the _readableState key.

Any ideas? It feels like we should not be using `stdin.end()`.

**Comment by asdofindia** [comment]
I suffer from this when I'm using [git plugin of caddy](https://caddyserver.com/docs/git) to generate docpad site. There's no process.stdin.end().
At the same time there is no error when I manually run the command through ssh.

BTW, is process.stdin.pause() useful?

**Comment by balupton** [comment]
@asdofindia does implementing the changes at https://github.com/docpad/docpad/pull/1029 fix the problem for you?

**Comment by asdofindia** [comment]
@balupton, yes, #1029 works. No idea why though. In my case, I run caddy via systemd, (with stdin being /dev/null), then caddy runs the git plugin, which runs `npm run generate` which is mapped to `node node_modules/docpad/bin/docpad generate --env static`. Maybe, somewhere in the chain, stdin loses its capabilities?

**Comment by balupton** [comment]
@asdofindia yeah, seems in certain situations stdin is instead of being a duplex stream, is one or the other - as such `.end` may not be available. Will merge in the pull request after #1045 is done

**Comment by balupton** [comment]
This will be ratified in v6.80.7 which will be out momentarily.

**Comment by balupton** [comment]
Took a bit longer than expected. But v6.80.7 is now out.
