### ISSUE TITLE
DocPad Confused a Git User

### ISSUE THREAD

**Issue by cjs-cynic-net** [docpad/docpad#1030]
Something resembling my first encounter with Docpad is reproduced below. (Actually, I got different and considerably more confusing error messages initially, but I'm not going to try to reproduce those.)

Docpad should ideally tell users that have already set up a repo that this is incompatible with the way Docpad works. If `docpad run` cannot do this, create a separate command called `docpad init` or similar so that Docpad can know it's trying to initialize a new project.

As a temporary measure, the Docpad introduction/tutorial should explain that Docpad uses git and one should not (as people like me habitually do) create a git repo to track what Docpad is doing before initializing a Docpad project, because that in itself will break Docpad.

Well, you need to explain to people about this, especially because it breaks in very non-intuitive ways for git users. Below is a reproduction of the sort of thing I encountered when first trying to follow the Docpad introduction tutorial. (Actually, I had different problems, but I'm not going to bother to attempt to reproduce them.)

Note that nothing ever told me I shouldn't be trying to use git to track what Docpad was doing in the directories, or even that Docpad had any connection with git at all. You guys should mention this, not leave habitual git users to wonder why things are blowing up when they take perfectly normal actions such as trying to track what Docpad might be doing.

```
telephonic $ mkdir z
telephonic $ cd z
telephonic $ git init
Initialized empty Git repository in /home/cjs/z/.git/
telephonic $ touch .gitignore
telephonic $ add .gitignore 
telephonic $ commit -m 'Start a test Docpad project.'
[master (root-commit) 9da458f] Start a test Docpad project.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 .gitignore
telephonic $ docpad run
info: Welcome to DocPad v6.78.4 (global installation: /home/cjs/local/lib/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: 
info: Environment: development
warning: A warning occured:

Error: We couldn't find an existing DocPad project inside your current directory. Looked at: /home/cjs/z
If you're wanting to use a pre-made skeleton for the basis of your new project, then run DocPad again inside an empty directory.
If you're wanting to start your new project from scratch, then refer to the Getting Started guide here:
    http://docpad.org/docs/start
For more information about what this means, visit:
    http://docpad.org/troubleshoot
  at DocPad.warn (/home/cjs/local/lib/node_modules/docpad/out/lib/docpad.js:3427:52)
  at /home/cjs/local/lib/node_modules/docpad/out/lib/docpad.js:5501:20
  at /home/cjs/local/lib/node_modules/docpad/node_modules/graceful-fs/graceful-fs.js:140:16
  at FSReqWrap.oncomplete (fs.js:83:15)

To report the above, follow the guide at: http://docpad.org/bug-report
info: The action completed successfully
```

**Comment by balupton** [comment]
… what was your expected output?

**Comment by cjs-cynic-net** [comment]
Turns out that there is a 'docpad init' command, and I suspect that if you simply use that for your initial initialization (instead of 'docpad run') that might fix the issue above. However, 'docpad init' didn't ask me anything about choosing a skeleton.

**Comment by cjs-cynic-net** [comment]
I was following http://docpad.org/docs/begin/ . I expected to be "prompted for a skeleton", and then I expected that after answering "no" I would have whatever files were expected to be there for a docpad site after following the tutorial instructions to that stage.

When you tried to replicate the problem by typing in the commands I showed in my first comment above, what did you see that was different and allowed you to keep following the tutorial?

**Comment by mikeumus** [comment]
@cjs-cynic-net it's the `.git` that's making `docpad run` think it's not an empty folder and to then initialize a new docpad project with skeleton selection. So Either DocPad should attempt to merge with any existing `.git` history in the folder or the guide needs to say to do `git init` after `docpad run` in the empty folder.

**Comment by cjs-cynic-net** [comment]
Yes, I know what the issue is here.

Your latter solution is simpler for you, because you're not using Git. For those us who are using it, however, saying "wipe out your current history and don't use Git when you start a DocPad project" is not very nice.

In general, saying to your customers, "don't do this not unreasonable thing" is tantamount to saying, "please go find another tool to use."

**Comment by mikeumus** [comment]
I see, pardon my use case has always been fresh DocPad projects but your point is perfectly valid. Pardon I lacked that perspective and thank you for letting me know about it. I do only use git though. 

Okay so then `docpad run` in this case should maybe fallback to a `docpad init` command if it doesn't find a `docpad.coffee` in the current folder and it should just start writing the DocPad files into that directory. 

Now I'll try to be more cautious and ask, what issues could this approach present if any and is there another/even better way to achieve this?

**Comment by balupton** [comment]
> As a temporary measure, the Docpad introduction/tutorial should explain that Docpad uses git and one should not (as people like me habitually do) create a git repo to track what Docpad is doing before initializing a Docpad project, because that in itself will break Docpad.

> Well, you need to explain to people about this, especially because it breaks in very non-intuitive ways for git users. Below is a reproduction of the sort of thing I encountered when first trying to follow the Docpad introduction tutorial. (Actually, I had different problems, but I'm not going to bother to attempt to reproduce them.)

As this is the first and only time this has been raised in the 4 years of DocPad's practice of this, I would say that it mustn't be that counter-intuitive and that much of a problem.

As the suggestion in the first paragraph is a good one, a pull request is welcome, however it is not a pressing issue and at this point, the complexity of the change doesn't seem valuable for myself to tackle over the other issues.

Will update the title and add the recommended labels.
