### ISSUE TITLE
Use Array::concat()

### ISSUE THREAD

**Issue by blitmap** [docpad/docpad#1032]
Hello, I thought I might point out that these 6 lines here:

https://github.com/docpad/docpad/blob/master/src/lib/collections/elements.coffee#L41

Might be better-written as simply: `values = [].concat values`

I hope this helps :-)

Also, below that:

```coffeescript
		# Convert string based array properties into html
		for value,key in values
			if typeChecker.isString(value)
				values[key] = new Model({html:value})
```

Can become:

```coffeescript
		# Convert string based array properties into html
		for value, key in values when typeChecker.isString value
			values[key] = new Model html: value
```

(If you want)

I sometimes help in #cofffeescript on Freenode so I like to point out little ways to make things more concise. :-)

**Comment by balupton** [comment]
Replaced by https://github.com/docpad/docpad/issues/1046
