### ISSUE TITLE
Render Content not included into Layout

### ISSUE THREAD

**Issue by Valkryst** [docpad/docpad#1033]
Hey,

I'm not totally sure if this is the right place to ask about this, but the IRC channel seems a bit dead. I just started learning to use docpad yesterday, so whatever problem I'm having is probably some small problem that I just don't see.

I'm basically just trying to get this http://pastebin.com/zbnaEXax render-page to use this http://pastebin.com/DkLXPik1 layout. It was working fine yesterday, but I obviously did something without looking and now the webpage looks like this https://imgur.com/T7aDY9r

**Comment by mikeumus** [comment]
Hey @Valkryst, pardon the tardy reply. Here's Bevry's official support page: 
- https://discuss.bevry.me/t/official-bevry-support-channels/63

Slack is our main channel of communication now. 

As per your error, is your project open on GitHub by chance? Sounds like maybe it's missing the `.html.eco` on the end of your file name maybe but can't tell from those snippets alone.

**Comment by Valkryst** [comment]
No problem, thanks for the link.

It's nothing fancy, just me messing around working on a mock-up of a website to store my cooking/baking recipes, so it's not on GitHub. I have uploaded it a the link below though.

The files haven't been touched since the posting of this little error and they still produce the reported errors after the following steps.

1. Execute the "docpad run" command in the root directory.
2. Navigate to "127.0.0.1:9778/Post-1.html" or "127.0.0.1:9778/Post-2.html".

https://valkryst.com/shared_files/Website_Files.7z

**Comment by mikeumus** [comment]
Hey @Valkryst, I'm on a chromebook and can't open the .7z easily. No shame in uploading to GitHub as storage. You'll see bunches of junk in my GitHub and it's all good, not against the Terms of Service.

**Comment by Valkryst** [comment]
Ah, I understand. You can find the uploaded files [here](https://github.com/Valkryst/Site_Cooking).

**Comment by Valkryst** [comment]
Alright, I think I've finally figured out the issue after restarting everything.

Both the layout and the render *.html pages were using eco. The render page was given the extension *.html.eco and the layout page was given the extension *.html without the ".eco" at the end.

The reason why the eco (script?) was the only thing being displayed on the rendered webpages is because docpad wasn't instructed to (parse?) the eco (script?) within the layout.

The problem is resolved by setting the layout extension to ".html.eco".
