### ISSUE TITLE
Disable outbound lookups

### ISSUE THREAD

**Issue by mrchief** [docpad/docpad#1036]
I tried adding these:

```
reportErrors: false
reportStatistics: false
growl: false
checkVersion: false
welcome: false
```

and it still fails with 

```
Error: getaddrinfo ENOTFOUND i-af486d56
  at errnoException (dns.js:26:10)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

What other lookups are there? Is there a way to disable all outbound lookups?

**Comment by balupton** [comment]
Use `--offline`

**Comment by mrchief** [comment]
I'm using `module.exports` method. How do I pass that option?

**Comment by balupton** [comment]
Try `offline: true`

**Comment by mrchief** [comment]
Didn't work. The error persists. If it helps, I'm using it in an AWS EC2 instance. I think its the `getHostName()` calls that are causing this error.

**Comment by mrchief** [comment]
Found a workaround. As pointed in the [API](http://docpad.org/docs/api) docs, creating and supplying my own express app helps circumvent this issue.

```
var express = require('express');
var http = require('http');
var app = express();
var server = http.createServer(app).listen(parseInt(process.env.PORT) || 8080);

// make docpad accept TOS
fs.writeFileSync(expandHomeDir('~/.docpad.cson'), fs.readFileSync('.docpad.cson'));

// Add our Application Middlewares
app.use(app.router);

// Add DocPad to our Application
var docpadInstanceConfiguration = {
    // Give it our express application and HTTP server
    serverExpress: app,
    serverHttp: server,

    // Tell it not to load the standard middlewares (as we handled that above)
    middlewareStandard: false
};

var docpadInstance = require('docpad').createInstance(docpadInstanceConfiguration, function(err){
    if (err)  return console.log(err.stack);

    // Tell DocPad to perform a generation, extend our server with its routes, and watch for changes
    docpadInstance.action('generate server', function(err){
        if (err)  return console.log(err.stack);
    });
});
```

As far as I can see, docpad should be able to do this without running into aforementioned errors. So in summary, I would love to: 

 - see docpad becoming AWS friendly (by not doing hostname lookups)
 - Support express v4 (since `app.router` is deprecated)

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.

`offline` configuration option probably works as expected now
