### ISSUE TITLE
Docpad generate creates site files but ends with massive error log

### ISSUE THREAD

**Issue by pvandervelde** [docpad/docpad#1040]
When I run docpad generate --env production --out c:\temp\mydir --force --debug 3 I get no output from docpad until after the process finishes. At that point I get an error log that is in excess of 170K lines long. The start of the log looks like:

	Error: The task [render] just completed, but it had already completed earlier, this is unexpected. State information is:
	 { error: 'Error: The task [render tasks for: tags/apollo.html.eco âžž  renderExtensions: tags/apollo.html.eco] just completed, but it had alre
	ady completed earlier, this is unexpected. State information is:\n{ error: \'Error: The task [renderExtensions: tags/apollo.html.eco âžž  renderExtension: tags/apollo.html.eco [eco => html]] just completed, but it had already com
	pleted earlier, this is unexpected. State information is:\\n{ error: \\\'Error: write after end\\\\n  at writeAfterEnd (_stream_writable.js:167:12)\\\\n  at Logger.Writable.write (_stream_writable.js:214:5)\\\\n  at Logger.log (E
	:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\caterpillar\\\\\\\\out\\\\\\\\lib\\\\\\\\caterpillar.js:225:12)\\\\n  at Logger.log (E:\\\\\\\\documents\\\\\\\\P
	etrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\caterpillar\\\\\\\\out\\\\\\\\lib\\\\\\\\caterpillar.js:4:61)\\\\n  at DocPad.log (E:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\\\\\
	\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\docpad\\\\\\\\out\\\\\\\\lib\\\\\\\\docpad.js:3258:18)\\\\n  at _Class.<anonymous> (E:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\
	\src\\\\\\\\node_modules\\\\\\\\docpad\\\\\\\\out\\\\\\\\lib\\\\\\\\docpad.js:1898:29)\\\\n  at _Class.emit (events.js:110:17)\\\\n  at Task.<anonymous> (E:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\b
	log\\\\\\\\src\\\\\\\\node_modules\\\\\\\\taskgroup\\\\\\\\out\\\\\\\\lib\\\\\\\\taskgroup.js:753:26)\\\\n  at Task.emit (events.js:129:20)\\\\n  at Task.<anonymous> (E:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\\\\\\proj
	ects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\taskgroup\\\\\\\\out\\\\\\\\lib\\\\\\\\taskgroup.js:53:28)\\\\n  at Task.emit (events.js:129:20)\\\\n  at Task.complete (E:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\
	\\\\\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\taskgroup\\\\\\\\out\\\\\\\\lib\\\\\\\\taskgroup.js:319:19)\\\\n  at Task.exit (E:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\
	\src\\\\\\\\node_modules\\\\\\\\taskgroup\\\\\\\\out\\\\\\\\lib\\\\\\\\taskgroup.js:301:14)\\\\n  at complete (E:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\t
	askgroup\\\\\\\\out\\\\\\\\lib\\\\\\\\taskgroup.js:388:26)\\\\n  at E:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\docpad\\\\\\\\out\\\\\\\\lib\\\\\\\\docpad.j
	s:3561:20\\\\n  at E:\\\\\\\\documents\\\\\\\\Petrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\docpad\\\\\\\\out\\\\\\\\lib\\\\\\\\docpad.js:3480:16\\\\n  at Request.callback (E:\\\\\\\\do
	cuments\\\\\\\\Petrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\superagent\\\\\\\\lib\\\\\\\\node\\\\\\\\index.js:691:12)\\\\n  at Stream.<anonymous> (E:\\\\\\\\documents\\\\\\\\Petrik\\\\
	\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\superagent\\\\\\\\lib\\\\\\\\node\\\\\\\\index.js:922:12)\\\\n  at Stream.emit (events.js:129:20)\\\\n  at Unzip.<anonymous> (E:\\\\\\\\documents\\\\
	\\\\Petrik\\\\\\\\documents\\\\\\\\projects\\\\\\\\blog\\\\\\\\src\\\\\\\\node_modules\\\\\\\\superagent\\\\\\\\lib\\\\\\\\node\\\\\\\\utils.js:108:12)\\\\n  at Unzip.emit (events.js:129:20)\\\\n  at _stream_readable.js:908:16\\\
	\n  at process._tickDomainCallback (node.js:381:11)\\\\n\\\',\\n  previousResult: [],\\n  currentArguments: [ { [Error: write after end] domain: [Object], domainThrown: true } ] }\\n  at Task.exit (E:\\\\documents\\\\Petrik\\\\do
	cuments\\\\projects\\\\blog\\\\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:309:15)\\n  at Domain.emit (events.js:107:17)\\n  at Domain.errorHandler [as _errorHandler] (domain.js:102:19)\\n  at process._fatalExc
	eption (node.js:233:33)\\n  at _Class.<anonymous> (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\docpad\\\\out\\\\lib\\\\docpad.js:1898:29)\\n  at _Class.emit (events.js:110:17)\\n  at Task.
	<anonymous> (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:753:26)\\n  at Task.emit (events.js:129:20)\\n  at Task.<anonymous> (E:\\\\documents\\\\Pet
	rik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:53:28)\\n  at Task.emit (events.js:129:20)\\n  at Task.complete (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\
	\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:319:19)\\n  at Task.exit (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:301:14)\\n  at
	 complete (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:388:26)\\n  at E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modu
	les\\\\docpad\\\\out\\\\lib\\\\docpad.js:3561:20\\n  at E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\docpad\\\\out\\\\lib\\\\docpad.js:3480:16\\n  at Request.callback (E:\\\\documents\\\\Pe
	trik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\superagent\\\\lib\\\\node\\\\index.js:691:12)\\n  at Stream.<anonymous> (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\superag
	ent\\\\lib\\\\node\\\\index.js:922:12)\\n  at Stream.emit (events.js:129:20)\\n  at Unzip.<anonymous> (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\superagent\\\\lib\\\\node\\\\utils.js:108
	:12)\\n  at Unzip.emit (events.js:129:20)\\n  at _stream_readable.js:908:16\\n  at process._tickDomainCallback (node.js:381:11)\\n\',\n  previousResult: [],\n  currentArguments: \n   [ { [Error: The task [renderExtensions: tags/a
	pollo.html.eco âžž  renderExtension: tags/apollo.html.eco [eco => html]] just completed, but it had already completed earlier, this is unexpected. State information is:\n     { error: \'Error: write after end\\n  at writeAfterEnd
	 (_stream_writable.js:167:12)\\n  at Logger.Writable.write (_stream_writable.js:214:5)\\n  at Logger.log (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\caterpillar\\\\out\\\\lib\\\\caterpill
	ar.js:225:12)\\n  at Logger.log (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\caterpillar\\\\out\\\\lib\\\\caterpillar.js:4:61)\\n  at DocPad.log (E:\\\\documents\\\\Petrik\\\\documents\\\\
	projects\\\\blog\\\\src\\\\node_modules\\\\docpad\\\\out\\\\lib\\\\docpad.js:3258:18)\\n  at _Class.<anonymous> (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\docpad\\\\out\\\\lib\\\\docpad.
	js:1898:29)\\n  at _Class.emit (events.js:110:17)\\n  at Task.<anonymous> (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:753:26)\\n  at Task.emit (eve
	nts.js:129:20)\\n  at Task.<anonymous> (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:53:28)\\n  at Task.emit (events.js:129:20)\\n  at Task.complete 
	(E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:319:19)\\n  at Task.exit (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_mod
	ules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:301:14)\\n  at complete (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\taskgroup\\\\out\\\\lib\\\\taskgroup.js:388:26)\\n  at E:\\\\documents\
	\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\docpad\\\\out\\\\lib\\\\docpad.js:3561:20\\n  at E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\docpad\\\\out\\\\lib\\\\do
	cpad.js:3480:16\\n  at Request.callback (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\src\\\\node_modules\\\\superagent\\\\lib\\\\node\\\\index.js:691:12)\\n  at Stream.<anonymous> (E:\\\\documents\\\\Petrik\\\\d
	ocuments\\\\projects\\\\blog\\\\src\\\\node_modules\\\\superagent\\\\lib\\\\node\\\\index.js:922:12)\\n  at Stream.emit (events.js:129:20)\\n  at Unzip.<anonymous> (E:\\\\documents\\\\Petrik\\\\documents\\\\projects\\\\blog\\\\sr
	c\\\\node_modules\\\\superagent\\\\lib\\\\node\\\\utils.js:108:12)\\n  at Unzip.emit (events.js:129:20)\\n  at _stream_readable.js:908:16\\n  at process._tickDomainCallback (node.js:381:11)\\n\',\n       previousResult: [],\n    
	   currentArguments: [ { [Error: write after end] domain: [Object], domainThrown: true } ] }]\n       domainEmitter: [Object],\n       domain: [Object],\n       domainThrown: false } ] }\n  at Task.exit (E:\\documents\\Petrik\\do
	cuments\\projects\\blog\\src\\node_modules\\taskgroup\\out\\lib\\taskgroup.js:309:15)\n  at Domain.emit (events.js:107:17)\n  at Task.emit (events.js:83:19)\n  at Task.exit (E:\\documents\\Petrik\\documents\\projects\\blog\\src\\
	node_modules\\taskgroup\\out\\lib\\taskgroup.js:310:14)\n  at Domain.emit (events.js:107:17)\n  at Domain.errorHandler [as _errorHandler] (domain.js:102:19)\n  at process._fatalException (node.js:233:33)\n  at _Class.<anonymous> 
	(E:\\documents\\Petrik\\documents\\projects\\blog\\src\\node_modules\\docpad\\out\\lib\\docpad.js:1898:29)\n  at _Class.emit (events.js:110:17)\n  at Task.<anonymous> (E:\\documents\\Petrik\\documents\\projects\\blog\\src\\node_m
	odules\\taskgroup\\out\\lib\\taskgroup.js:753:26)\n  at Task.emit (events.js:129:20)\n  at Task.<anonymous> (E:\\documents\\Petrik\\documents\\projects\\blog\\src\\node_modules\\taskgroup\\out\\lib\\taskgroup.js:53:28)\n  at Task
	.emit (events.js:129:20)\n  at Task.complete (E:\\documents\\Petrik\\documents\\projects\\blog\\src\\node_modules\\taskgroup\\out\\lib\\taskgroup.js:319:19)\n  at Task.exit (E:\\documents\\Petrik\\documents\\projects\\blog\\src\\
	node_modules\\taskgroup\\out\\lib\\taskgroup.js:301:14)\n  at complete (E:\\documents\\Petrik\\documents\\projects\\blog\\src\\node_modules\\taskgroup\\out\\lib\\taskgroup.js:388:26)\n  at E:\\documents\\Petrik\\documents\\projec
	ts\\blog\\src\\node_modules\\docpad\\out\\lib\\docpad.js:3561:20\n  at E:\\documents\\Petrik\\documents\\projects\\blog\\src\\node_modules\\docpad\\out\\lib\\docpad.js:3480:16\n  at Request.callback (E:\\documents\\Petrik\\docume
	nts\\projects\\blog\\src\\node_modules\\superagent\\lib\\node\\index.js:691:12)\n  at Stream.<anonymous> (E:\\documents\\Petrik\\documents\\projects\\blog\\src\\node_modules\\superagent\\lib\\node\\index.js:922:12)\n  at Stream.e
	mit (events.js:129:20)\n  at Unzip.<anonymous> (E:\\documents\\Petrik\\documents\\projects\\blog\\src\\node_modules\\superagent\\lib\\node\\utils.js:108:12)\n  at Unzip.emit (events.js:129:20)\n  at _stream_readable.js:908:16\n  
	at process._tickDomainCallback (node.js:381:11)\n',
	E:\documents\Petrik\documents\projects\blog\src\build.docpad.msbuild(135,9): warning :   previousResult: 
	E:\documents\Petrik\documents\projects\blog\src\build.docpad.msbuild(135,9): warning :    [ null,

The questions are: 
1) what is this log saying. I don't understand why the process would end and then it complains.
2) How can I make this go away. All files are generated correctly, I don't care what the error is. Apparently changing the debug verbosity of docpad doesn't do anything.

Docpad environment:
---
package.json

	{
	  "name": "mindvortex.docpad",
	  "version": "0.1.0",
	  "private": true,
	  "description": "Patrick van der Velde's personal web page.",
	  "homepage": "http://petrikvandervelde.nl",
	  "keywords": [
		"docpad-skeleton",
		"docpad",
		"website",
		"skeleton",
		"html5 boilerplate",
		"h5bp"
	  ],
	  "author": "Patrick van der Velde (http://petrikvandervelde.nl)",
	  "maintainers": [
		"Patrick van der Velde (http://petrikvandervelde.nl)"
	  ],
	  "contributors": [
		"Patrick van der Velde (http://petrikvandervelde.nl)"
	  ],
	  "repository": {
		"type": "git",
		"url": "https://github.com/pvandervelde/mindvortex.git"
	  },
	  "engines": {
		"node": "0.8.x",
		"npm": "1.1.x"
	  },
	  "dependencies": {
		"docpad": "~6.78.4",
		"docpad-plugin-coffeescript": "~2.5.0",
		"docpad-plugin-datefromfilename": "~2.0.4",
		"docpad-plugin-eco": "~2.1.0",
		"docpad-plugin-gist": "~2.1.1",
		"docpad-plugin-highlightjs": "~2.3.0",
		"docpad-plugin-marked": "~2.3.0",
		"docpad-plugin-navlinks": "~2.0.4",
		"docpad-plugin-paged": "~2.4.0",
		"docpad-plugin-partials": "~2.9.2",
		"docpad-plugin-related": "~2.2.2",
		"docpad-plugin-sitemap": "~2.2.0",
		"docpad-plugin-stylus": "~2.11.0",
		"docpad-plugin-tagcloud": "~2.0.1",
		"docpad-plugin-tags": "~2.0.7",
		"docpad-plugin-text": "~2.3.3",
		"eco": "~1.1.0-rc-3",
		"moment": "~2.12.0"
	  },
	  "devDependencies": {
		"docpad-plugin-livereload": "~2.7.1",
		"docpad-plugin-services": "~2.6.0"
	  },
	  "main": "node_modules/docpad/bin/docpad-server"
	}

Running docpad from the local install.

**Comment by mikeumus** [comment]
Hey @pvandervelde, one thing I can see right away is the older versions of node and npm in your package.json's engine settings. See DocPad's versions for Node and NPM here in it's package.json: 
- https://github.com/docpad/docpad/blob/master/package.json#L137

**Comment by pvandervelde** [comment]
Ah crap. I should have posted that. I've actually got node 0.12.7 and npm 3.5.2(?) that I'm using. I thought those would be ok? I tried node 4.4 (?) but that had issues with some NaN C++ thing.

**Comment by mikeumus** [comment]
I'm using node v4.1.1 in my current project. On a recent project I have node v4.3.2 and npm 3.8.1: 
- https://github.com/BetaBulls/betabulls.docpad/blob/MDM-dev/package.json#L6

I'd say to update your package.json to have node >=0.12 and npm >=3

**Comment by pvandervelde** [comment]
Ok I'll try that and see what happens.

**Comment by pvandervelde** [comment]
Ok so I just tried that. My package.json now looks like:

	{
	  "name": "mindvortex.docpad",
	  "version": "0.1.0",
	  "private": true,
	  "description": "Patrick van der Velde's personal web page.",
	  "homepage": "http://petrikvandervelde.nl",
	  "keywords": [
		"docpad-skeleton",
		"docpad",
		"website",
		"skeleton",
		"html5 boilerplate",
		"h5bp"
	  ],
	  "author": "Patrick van der Velde (http://petrikvandervelde.nl)",
	  "maintainers": [
		"Patrick van der Velde (http://petrikvandervelde.nl)"
	  ],
	  "contributors": [
		"Patrick van der Velde (http://petrikvandervelde.nl)"
	  ],
	  "repository": {
		"type": "git",
		"url": "https://github.com/pvandervelde/mindvortex.git"
	  },
	  "engines": {
		"node": "0.12.x",
		"npm": "3.5.x"
	  },
	  "dependencies": {
		"docpad": "~6.78.4",
		"docpad-plugin-coffeescript": "~2.5.0",
		"docpad-plugin-datefromfilename": "~2.0.4",
		"docpad-plugin-eco": "~2.1.0",
		"docpad-plugin-gist": "~2.1.1",
		"docpad-plugin-highlightjs": "~2.3.0",
		"docpad-plugin-marked": "~2.3.0",
		"docpad-plugin-navlinks": "~2.0.4",
		"docpad-plugin-paged": "~2.4.0",
		"docpad-plugin-partials": "~2.9.2",
		"docpad-plugin-related": "~2.2.2",
		"docpad-plugin-sitemap": "~2.2.0",
		"docpad-plugin-stylus": "~2.11.0",
		"docpad-plugin-tagcloud": "~2.0.1",
		"docpad-plugin-tags": "~2.0.7",
		"docpad-plugin-text": "~2.3.3",
		"eco": "~1.1.0-rc-3",
		"moment": "~2.12.0"
	  },
	  "devDependencies": {
		"docpad-plugin-livereload": "~2.7.1",
		"docpad-plugin-services": "~2.6.0"
	  },
	  "main": "node_modules/docpad/bin/docpad-server"
	}

But the error remains. The version of node.js being used is still 0.12.7 and the version of NPM being used is 3.5.2. All node packages are installed before calling out to docpad so I don't think docpad needs to run NPM.

Is there anything else I can try?

**Comment by mikeumus** [comment]
I've never used the docpad generate command: `docpad generate --env production --out c:\temp\mydir --force --debug 3`. 

Maybe it's the `--debug 3` [loglevel](https://github.com/docpad/docpad/blob/e9cca57eab80a2d5126f5924c471a457ffd0cc98/src/lib/interfaces/console.coffee#L373) :confused: .

**Comment by pvandervelde** [comment]
No it's not. I've tried levels 6 (default), 5, 4, and 3. At 3 docpad displays nearly no messages during the process, and then still dumps the error log

**Comment by mikeumus** [comment]
And you've tried it without the `--debug` I assume too then.

Is it open on GitHub by chance? I'll clone it in Cloud9 IDE and give it a try.

**Comment by pvandervelde** [comment]
Yeah tried without debug as well. I couldn't find anything on github but I'll do another search.

**Comment by mikeumus** [comment]
Pardon the confusion. I meant to ask if your DocPad project was on GitHub and I'll take a look at its source code and run the project on Cloud 9 IDE. 

I can try those commands on my DocPad project and see what I get too.

**Comment by pvandervelde** [comment]
Yeah it is. It's here: https://github.com/pvandervelde/mindvortex/tree/feature/buildscripts. The docpad code is in the src directory

**Comment by pvandervelde** [comment]
Ok I might have figured it out. There were a bunch of docpad warnings stating that some conversion didn't work. Once I fixed those the massive stack at the end of the process went away.

So my problem is solved but I still think there might be an issue in that node dumps a massive amount of information to the console when there is a failed conversion (in my case I think it was from eco to html). Realistically as a developer I don't really care about the node dump unless I ask for it. Docpad already has a  warning indicating that something wrong but that now gets overshadowed by the massive dump at the end.

**Comment by pvandervelde** [comment]
Unfortunately there's now another problem in that the process hangs at the end waiting for some handles to close. I will open another issue for that though.

Shall I close this issue or is it likely that people will want to fix the duplicate warning / large log problem?

**Comment by mikeumus** [comment]
Yeah we can close this issue but may you describe what you fixed exactly for anyone that stumbles across this issue. Thanks @pvandervelde :blush:.

**Comment by pvandervelde** [comment]
Like I said I believe it was due to the fact that the conversion from eco to html didn't do anything. The stack trace seemed to indicate that the conversion process had been killed. The massive log dump seemed to be the state of the generator at the end of the process with docpad / node indicating that it was expecting it to be alive but it wasn't.

**Comment by edudojevic** [comment]
Adding `<%- %>` as a dummy in each template at least gets rid of the warnings. Would be great if you can control the type of warnings that are being printed.
