### ISSUE TITLE
Remove Newsletter, Mixpanel & Error Reporting

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#1041]
Rationale
1. We have already abolished Google Analytics and other tracking services from all the bevry websites
2. There is still Mixpanel and Error Reporting tracking in DocPad - as no one is actively using this data, we can get rid of it, especially as it is a source of slow down and issues
3. There is still Newsletter signup in the CLI - as we now have a website for DocPad, this can be removed
4. Removing Mixpanel, Error Reporting, and Newsletter removes the need for the Privacy Policy in the CLI, however may still need the TOS as it is an app and not a library - however, I wonder if the MIT license's warranty protects us, perhaps we can then just do - do you agree to the MIT license

Immediate:
1. Remove newsletter signup
2. Move analytics and reporting sending into a plugin, it is an event anyway, so we should still emit the events, but just move the sending into a plugin - as an immediate step, we should just disable the flags by default, see how that goes for a month or two, and then proceed with removing the actual code
3. Keep the TOS and Privacy in there for now

NOTE:
- Before closing this issue, be sure to check all linked issues, to see if the implementation of this issue actually closes them.

**Comment by mikeumus** [comment]
I'd say if we have the LICENSE.md and the licence in the package.json we'll be covered.

**Comment by balupton** [comment]
These have been removed from the [helper](https://github.com/bevry/helper) as of v3.3.0

**Comment by balupton** [comment]
Removed as of v6.80.0
