### ISSUE TITLE
Meta Data Parsing Error

### ISSUE THREAD

**Issue by Valkryst** [docpad/docpad#1043]
I am using the latest version of docpad and eco. The following meta data, when used, will cause a portion of the meta data to be rendered onto the webpage. I am unsure if this is an issue with docpad or eco.

```
---
title: "Ricotta Cheese Eggs"
layout: "recipe"
image: "Post-1---Image-1.jpg"

hasOtherRecipe_A: "true"
otherRecipeTitle_A: "Valk's Home-Cooked Vegetable Soup"
otherRecipeImage_A: "Post-2---Image-1.jpg"

hasOtherRecipe_B: "true"
otherRecipeTitle_B: "Recipe B"
otherRecipeImage_B: "Post-2---Image-1.jpg"

hasOtherRecipe_C: "true"
otherRecipeTitle_C: "Recipe C"
otherRecipeImage_C: "Post-2---Image-1.jpg"
---
```

When viewing the webpage, the following portion of the meta data can be seen on the webpage itself. An image of this issue is attached.

```
hasOtherRecipe_A: "true"
otherRecipeTitle_A: "Valk's Home-Cooked Vegetable Soup"
otherRecipeImage_A: "Post-2---Image-1.jpg"

hasOtherRecipe_B: "true"
otherRecipeTitle_B: "Recipe B"
otherRecipeImage_B: "Post-2---Image-1.jpg"

hasOtherRecipe_C: "true"
otherRecipeTitle_C: "Recipe C"
otherRecipeImage_C: "Post-2---Image-1.jpg"
---
```

This issue, as far as I'm able to see, is caused by the triple-hyphens used in the image names.

![Visual Error](https://cloud.githubusercontent.com/assets/1524476/14567277/bf408108-0309-11e6-9903-e30d8a76f097.png)

**Comment by mikeumus** [comment]
Hey @Valkryst, 
Is the file named with `.html.eco` extension? 
If the project is open-source, may you share the repo url for inspection? 
Thanks,
_Mike_

**Comment by Valkryst** [comment]
If my commit was successful, you should be able to clone [this](https://github.com/Valkryst/Site_Cooking) and experience the bug.

**Comment by mikeumus** [comment]
Something to do with the way it's parsed. Now that you're up and running again. Do you mind if we close this issue and anyone may use it as reference/discussion that comes across this again and now they'll know how to fix it.

**Comment by Valkryst** [comment]
No problem, just wanted to make people aware of it.
