### ISSUE TITLE
Is the project still alive and maintained?

### ISSUE THREAD

**Issue by rszczypka** [docpad/docpad#1044]
as per title. I just don't want to spend too much time on something that can get soon abandoned.

And I can see that the last buzz about docpad is from late 2015.

**Comment by balupton** [comment]
It does its job.

**Comment by maciejmyslinski** [comment]
@balupton it has over 200 issues!
It has out of date dependencies and insecure devDependencies.
I really appreciate your work. However considering above and your answer, @rszczypka concerns about maintenance are justified.

**Comment by RobLoach** [comment]
Ben is one guy, and the DocPad community needs as much help as it can get. Sounds like you found some ways to help it out, at the very least. Mind spinning up some issues on ways to keep DocPad maintenance in check?

**Comment by balupton** [comment]
As long as we are not hitting our funding goals - http://bevry.me/patreon - DocPad is made by the DocPad open-source community for the DocPad open-source community, of which, it does the job. If you are using commercially, don't expect a free external workforce in the cloud, funding or contributing which many companies have done in signficant ways over the years, is the best route to hit needs that aren't currently being met.

**Comment by rszczypka** [comment]
Thanks for the explanation and I understand it fully. I'm not using DocPad commercially yet. At the moment I'm only looking around to find the best static site generator for my first project of this type. One of my criteria is how well the project is maintained  and documented.

DocPad seems to meet most of my requirements:
- javascript based
- supports multilingual sites
- supports many different content formats
- flexible
- powerful mongodb like search engine

However, for some reasons it looks abandoned by the community. There hasn’t been any commit activity on DocPad in the last month. There is no buzz about it in the social media.

**Comment by balupton** [comment]
No worries.

Regarding activity, the updates channel on https://slack.bevry.me is pretty comprehensive.

My focus is primarily with the Bevry community, particularly the first patreon item "Migration from CoffeeScript to ES6+ for radical Performance improvements and increased Accessibility" which I've been accomplishing more or less steadily, only about 20 or so projects remaining. These updates from the Bevry community eventually trickle down into the DocPad community.

I don't use DocPad day to day as I use to. However others like @mikeumus I believe do. We have a fairly large community of people quite happy with the way it is.

There are definitely nice things we can do, such as those outlined on patreon, and quicker maintenance, personally I'd love to put more time into it as it is really nifty, however, without funding, there are no guarantees.

**Comment by madalinignisca** [comment]
Voting for closing this issue.

Docpad is maintained.

It works for anybody who has more knowledge in working with JS and NodeJS and especially for people that contribute to it in anyway.

**Comment by almereyda** [comment]
I feel a more open communication platform than Slack, i.e. Gitter or Matrix, could help in keeping users close to the heart. Else there is https://github.com/matrix-org/matrix-appservice-slack

**Comment by balupton** [comment]
@almereyda slack works, not a fan for change for the sake of change, which ideological change mostly is

**Comment by balupton** [comment]
As an update, I've completed a large batch of bevry projext uodates the past 6 months or so. And would like to get these changes into DocPad. Here is a funsing proposal:

https://bevry.slack.com/archives/funding/p1465389361000003

To join our slack: https://slack.bevry.me

**Comment by balupton** [comment]
https://github.com/docpad/docpad/releases/tag/v6.78.5 - more to come

https://github.com/docpad/docpad/issues/1044#issuecomment-224577379 - feedback will be useful

**Comment by balupton** [comment]
Closing, as it should be evident it is maintained. Further discussions can happen on slack.
