### ISSUE TITLE
Plugin tests fail when finishing up

### ISSUE THREAD

**Issue by SteveMcArthur** [docpad/docpad#1047]
All of a sudden when I run a plugin test the test will fail massively with a never-ending, repeating stacktrace AFTER all test have completed successfully when the "finishing up" message shows. It seems to occur after installing the node_modules for a plugin. I first noticed it on travis, even though everything ran fine locally. Once I had deleted the node_modules directory and run npm install (or cake install) I would then get the error. I've downloaded the eco plugin and get the same results. Travis builds fail on node 0.12 and 4.4. I thought it may have been changes to the way NPM installs dependencies so downgraded from 3.8.8 to 2.15.5

It's hard to pinpoint where exactly the error is. The stacktrace comes from taskgroup - but that doesn't really seem to help. Can anyone else duplicate this problem?

**Comment by SteveMcArthur** [comment]
**Stacktrace:**
```
Error: The task [destroy] just completed, but it had already completed earlier, this is unexpected. State information is:
{ error: 'Error: write after end\n  at writeAfterEnd (_stream_writable.js:166:12)\n  at Logger.Writable.write (_stream_writable.js:211:5)\n  at Logger.log (F:\\Development\\docpad\\docpad-plugin-eco\\node_modules\\docpad\\node_modules\\caterpillar\\out\\lib\\caterpillar.js:225:12)\n  at Logger.__bind [as log] (F:\\Development\\docpad\\docpad-plugin-eco\\node_modules\\docpad\\node_modules\\caterpillar\\out\\lib\\caterpillar.js:4:61)\n  at DocPad.log (F:\\Development\\docpad\\docpad-plugin-eco\\node_modules\\docpad\\out\\lib\\docpad.js:3372:16)\n  at _Class.<anonymous> (F:\\Development\\docpad\\docpad-plugin-eco\\node_modules\\docpad\\out\\lib\\docpad.js:1968:27)\n  at emitTwo (events.js:87:13)\n  at _Class.emit (events.js:172:7)\n  at Task.<anonymous> (F:\\Development\\docpad\\docpad-plugin-eco\\node_modules\\docpad\\node_modules\\taskgroup\\out\\lib\\taskgroup.js:753:26)\n  at emitOne (events.js:82:20)\n  at Task.emit (events.js:169:7)\n  at Task.<anonymous> (F:\\Development\\docpad\\docpad-plugin-eco\\node_modules\\docpad\\node_modules\\taskgroup\\out\\lib\\taskgroup.js:53:28)\n  at emitOne (events.js:82:20)\n  at Task.emit (events.js:169:7)\n  at Task.complete (F:\\Development\\docpad\\docpad-plugin-eco\\node_modules\\docpad\\node_modules\\taskgroup\\out\\lib\\taskgroup.js:319:19)\n  at Task.exit 
```

**Comment by SteveMcArthur** [comment]
Ok - seem to have tracked the problem down to the latest versions of [event-emitter-grouped](https://github.com/bevry/event-emitter-grouped) and [joe](https://github.com/bevry/joe). When I fix the event-emitter-grouped module at v2.4.3 and joe at v1.6.0 the problem is fixed. This means going in to the node_modules directory after they have been installed and deleting the event-emitter-grouped and joe folders then editing the installed docpad package file to fix the versions and run cake install again.

**Comment by balupton** [comment]
Any idea why this was manifesting itself in caterpillar?

**Comment by SteveMcArthur** [comment]
Would it be worthwhile for the moment to set event-emitter-grouped and joe to the specific version in the package.json just for the moment?

**Comment by balupton** [comment]
Yeah. Probably. Highest priority for me is getting more donations or work. You have publish access right? Feel free to release.

**Comment by SteveMcArthur** [comment]
OK - pushed to git but I don't have access to publish to npm.

**Comment by balupton** [comment]
What is your npm username?

**Comment by SteveMcArthur** [comment]
stevemc

**Comment by balupton** [comment]
Added

**Comment by SteveMcArthur** [comment]
OK - pushed up version 6.78.6 of Docpad and plugin tests now complete. You will need to clear your cache on travis otherwise they will still fail there.

**Comment by Aglezabad** [comment]
Good morning:

I have checked my plugin (UnivUnix/docpad-plugin-api) and I can reproduce the same issue in TravisCI. Also, I've checked other Docpad plugins because I thought that I was doing something wrong, but I don't get any positive results. Could you provide me some help with that?

Regards.

P.D: I'm using the TravisCI open service, so I think that everything you need is visible.
