### ISSUE TITLE
Spawn unknown error

### ISSUE THREAD

**Issue by grsr01** [docpad/docpad#1050]
Hi,

I am trying to run a node application locally. It has dependencies to docpad and that is throwing an error when I say 'npm run compile'.

One of its file has an usage as below -
require('child_process').spawn(command[0], command.slice(1), opts)

At this line, it says spawn not found. It seems to be working on MAC. Its only in Windows where we are facing this issue.

DocPad version - v6.78.6
Node version - v6.6.0
npm version - 3.10.3

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
