### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by kbitlive** [docpad/docpad#1051]
![image](https://cloud.githubusercontent.com/assets/12296964/18705165/aecb503a-801f-11e6-8943-dfecb8a06b85.png)

HELP

**Comment by mikeumus** [comment]
Hi @kbitlive, may you tell us the steps you took to get here? 

Thanks.

**Comment by kbitlive** [comment]
git clone https://github.com/emmetio/emmet-docs.git
npm install -g docpad && npm install -g grunt
npm install
docpad run

this's all;

**Comment by mikeumus** [comment]
Alright, pardon but may you provide the items asked for here under: "BUG REPORTS VIA GITHUB'S ISSUE TRACKER"
- http://docpad.org/docs/support

> With your bug reports, specify:
- Your DocPad version docpad --version
- Your Node.js version node --version
- Your npm version npm --version
- Your operating system's name, architecture, and version
- What you did
- What happened
- What you expected
- The skeleton that was affected (if applicable)
- The docpad-debug.log file when you run DocPad in debug mode by specifying the -d flag (e.g., docpad run -d)

**Comment by kbitlive** [comment]
1. docpad  v6.78.6 

```
......node_modules\docpad\node_modules\extract-opts\source\index.js:6
module.exports = function (opts, next, config = {}) {
                                              ^
v6.78.6 (global installation: .....\node_modules\docpad)
```

2. node  v0.10.40
3. nom 3.10.3
4. windows 10  64

**Comment by mikeumus** [comment]
Okay can you try using `nvm` or `n` to go to node v4.5.0 and run it again. 
If that's no good then try running:
-  `docpad clean`
-  `docpad install`
-  `docpad run` 

and finally if that doesn't work, do the unspeakable `sudo docpad run` and report back. 🍀

**Comment by balupton** [comment]
Log error should solve with https://github.com/docpad/docpad/issues/1041

---

```
node_modules\docpad\node_modules\extract-opts\source\index.js:6
module.exports = function (opts, next, config = {}) {
```

Error should solve with https://github.com/docpad/docpad/issues/1045

---

Node 0.10 is no longer supported https://github.com/docpad/docpad/issues/1008

**Comment by balupton** [comment]
Dependent issues are resolved. v6.80 has the fix.
