### ISSUE TITLE
unhandled exception when cannot access the http://raw.githubusercontent.com/bevry/docpad/master/package.json

### ISSUE THREAD

**Issue by ninggf** [docpad/docpad#1056]
after run any docpad command, the exception thrown for my computer cannot access the 「http://raw.githubusercontent.com/bevry/docpad/master/package.json」：

info: The action completed successfully
info: Shutting down... cya next time!
Waiting on the requests:
[ TCPConnectWrap {
    oncomplete: [Function: afterConnect],
    address: '151.101.36.133',
    port: 80,
    localAddress: undefined,
    localPort: undefined,
    domain: 
     Domain {
       domain: null,
       _events: [Object],
       _eventsCount: 1,
       _maxListeners: undefined,
       members: [] } } ]
.................

**Comment by balupton** [comment]
Please upgrade to a newer DocPad version.
