### ISSUE TITLE
serverExpress is ignored unless serverHttp is also set

### ISSUE THREAD

**Issue by nfriedly** [docpad/docpad#1060]
I'm not sure if this was the intended behavior, but it wasn't what I expected after reading the docs. It seems that the `serverExpress` and `serverHttp` settings get ignored unless you set both of them in docpad.coffee because of this `if`: https://github.com/docpad/docpad/blob/c146742879b9d4538381cdcd3b953863f393f95e/src/lib/docpad.coffee#L380

I was hoping to be able to just set `serverExpress` and let the default http server get used.

(Looking further, I realized that I could probably do what I want with the `serverExtend` method, but I think this is still a valid ticket nonetheless.)

**Comment by balupton** [comment]
Closed in favour of https://github.com/docpad/docpad/issues/1081
