### ISSUE TITLE
Events out of order

### ISSUE THREAD

**Issue by danguilherme** [docpad/docpad#1062]
I'm writing a DocPad plugin, and I'm finding some trouble in the order of the events. They do not seem to work as the [DocPad website](https://docpad.org/docs/events/) states:

> **Available Events**
> Sorted by their flow of execution within DocPad
> - extendTemplateData
> - extendCollections
> - ...

In my plugin, if I put simple `console.log`s in these functions, the output is:

    > extendCollections called
    > extendTemplateData called

It gets worse if I declare the `collections` property in my DocPad configuration:

    docpadConfig:
        collections:
            posts:
                console.log('collections.posts called');
                // I'd like to access the collection created by my plugin

It is called before any of the above events, so the collection I created on `extendCollections` isn't available. Am I doing something wrong? Shouldn't I have access to collections "extended" in `extendCollections`?

**Comment by balupton** [comment]
thanks for feedback!

seems the docs are incorrect:

https://github.com/docpad/docpad/blob/e5e984604c53a064c44382fb653c1cbb77498a38/src/lib/docpad.coffee#L2442-L2446



> It is called before any of the above events, so the collection I created on extendCollections isn't available. Am I doing something wrong? Shouldn't I have access to collections "extended" in extendCollections?

`extendCollections` is for injecting new collections, `populateCollections` is for adding documents for them, there isn't currently something in between
