### ISSUE TITLE
Migration to Express 4.x and updating dependencies: Log of progress and questions related.

### ISSUE THREAD

**Issue by Aglezabad** [docpad/docpad#1065]
Good morning:

Maybe is a duplicate of #1045, but it's important to check that. I was checking Docpad with david-dm and we have a problem. It's not about the outdated dependencies, but security flaws instead. The versions required of **method-override, mime and superagent may cause a DoS**. The first two can be fixed with updated version, but superagent can't. I have two questions:

 * Why we need superagent? Because maybe can be removed.

 * Is there any branch for this task? Now I'm using a new branch from master on my fork. (UnivUnix/docpad)

Also, I was doing some experiments to migrate Docpad to Express 4.x but I don't know if this is a good idea for you. Can I continue the migration try?

That's all for now.

Best regards.

**Comment by Aglezabad** [comment]
Good evening:

I've made some progress.
 * express -> 4.16.2
 * safefs -> 4.1.0 
 * safeps -> 7.0.1
 * method-override -> 2.3.10
 * backbone -> 1.3.3

All tests passed but I will test with my website, so I can get real results.
Also, I'm fixing all possible breaking changes in dependencies. You can check them in https://github.com/UnivUnix/docpad if I am doing something wrong.

See you soon.

**Comment by Aglezabad** [comment]
I've made some progress with this. You can check the difference in david-dm report: https://david-dm.org/univunix/docpad?view=list . After that, I will need to do some extra testing to avoid unexpected results.

Also, I've fixed the extendr errors produced when I upgrade to latest version of it. It's because we are putting an undefined or null value as an argument (and that's not a plain object).

Finally, some plugins will need changes, because they use older version of express and they make conflicts with express used in Docpad. e.g. docpad-plugin-authentication.

Best regards.

**Comment by Aglezabad** [comment]
I've investigated the crashes produced by Taskgroup and they are caused by Coffeescript incompatibilities with ECMA6 classes (can't extend ES6 classes with Coffeescript classes). So, it's required to do the conversion from Coffee to ES6 to avoid further problems.

I didn't made changes this week.

Regards.

**Comment by Aglezabad** [comment]
I've done the conversion to ES6 using the tools proposed by @paleite in #1046 and I'm doing the manual review phase for improvement of results.

**Comment by paleite** [comment]
@Aglezabad Looking forward to it!

**Comment by Aglezabad** [comment]
Hi, I have a problem. I've tried to upgrade Taskgroup to latest version (5.0.1) and adapted the function calls to the new API, but now the tests are failing with no explanation or error stack. Only I know is they are returning code 1 to Linux, but it does not give me enough information of the cause.

Do you know how to catch Taskgroup failures? Maybe it's the most difficult part of this.

Best regards.

**Comment by mikeumus** [comment]
@balupton  ^

**Comment by balupton** [comment]
https://github.com/docpad/docpad/tree/dev-updatedeps should be of help

**Comment by balupton** [comment]
For the insecure deps, that only matters if you are running DocPad as a server rather than soley as a Static Site Generator

**Comment by Aglezabad** [comment]
Well, I'm using it as a server, but behind a Nginx as a proxy. So it's not critical to solve every insecure dependency.

**Comment by Aglezabad** [comment]
@balupton Thank you very much for showing where to get the needed clue. I was going to be crazy trying to figure where's the problem. Now I can continue with this.

**Comment by Aglezabad** [comment]
I'm going back to master and trying again this process, because I had multiple problems related with promises. So I will do this: update depedency, test, commit until I get working all components.

**Comment by Aglezabad** [comment]
I've merged dev-updatedeps with master in a new branch. Next, I've updated coffee-script to coffeescript 2.1.0 and tried to compile with that. I've solved the compilation problems (migration from 1.x) and I've solved Taskgroup creation calls. Also I've recompiled the necessary plugins for testing procedure (eco, marked and coffeekup).

Now I have this problem: Test "docpad-api -> render -> markdown file without extension" throws an error.  This error is due to next function being null in some part of the process. I've done manual debugging (adding log entries) and I supose that the problem is between the action "load contextualize" and Document.contextualize function.

I will try to get a solution for that.

Regards.

Node: v6
System: Ubuntu 17.10

**LOG:**
```
info: Environment: development
docpad-api ➞ create ➞ ready action ✔
docpad-api ➞ create ✔
docpad-api ➞ models
docpad-api ➞ models ➞ document
docpad-api ➞ models ➞ document ✔
docpad-api ➞ models ➞ create
docpad-api ➞ models ➞ create ✔
docpad-api ➞ models ➞ load
Document.contextualize: -> opts:
{}
Document.contextualize: -> next:(...args) => {
			if ( taskDomain ) {
				this.clearDomain()
				taskDomain = null
				exitMethod(...args)
			}
			else {
				// Use the next tick workaround to escape the try...catch scope
				// Which would otherwise catch errors inside our code when it shouldn't therefore suppressing errors
				queue(function () {
					exitMethod(...args)
				})
			}
		}
docpad-api ➞ models ➞ load ✔
docpad-api ➞ models ✔
docpad-api ➞ render
docpad-api ➞ render ➞ markdown without extension
Util.action: -> action:render
Util.action: -> opts:
{ data: '*awesome*',
  filename: 'file',
  renderSingleExtensions: 'auto' }
Util.action: -> next:function (err, result) {
          if (err) {
            return done(err);
          }
          equal(result.trim(), input.stdout, 'output');
          return done();
        }
Docpad.render: -> opts:
{ data: '*awesome*',
  filename: 'file',
  renderSingleExtensions: 'auto' }
Docpad.render: -> next:(...args) => {
			if ( taskDomain ) {
				this.clearDomain()
				taskDomain = null
				exitMethod(...args)
			}
			else {
				// Use the next tick workaround to escape the try...catch scope
				// Which would otherwise catch errors inside our code when it shouldn't therefore suppressing errors
				queue(function () {
					exitMethod(...args)
				})
			}
		}
Docpad.loadDoc: -> opts:
{ data: '*awesome*',
  filename: 'file',
  renderSingleExtensions: 'auto' }
Docpad.loadDoc: -> next:function (err) {
        if (err) {
          return next(err);
        }
        // Render
        return docpad.renderDocument(document, opts, next);
      }
Util.action: -> action:load contextualize
Util.action: -> opts:
{ data: '*awesome*',
  filename: 'file',
  renderSingleExtensions: 'auto' }
Util.action: -> next:function (err) {
        if (err) {
          return next(err);
        }
        // Render
        return docpad.renderDocument(document, opts, next);
      }
Document.contextualize: -> opts:
{ data: '*awesome*',
  filename: 'file',
  renderSingleExtensions: 'auto',
  exists: null }
Document.contextualize: -> next:null
docpad-api ➞ render ➞ markdown without extension ✘
Document.contextualize: -> opts:
{}
Document.contextualize: -> next:(...args) => {
			if ( taskDomain ) {
				this.clearDomain()
				taskDomain = null
				exitMethod(...args)
			}
			else {
				// Use the next tick workaround to escape the try...catch scope
				// Which would otherwise catch errors inside our code when it shouldn't therefore suppressing errors
				queue(function () {
					exitMethod(...args)
				})
			}
		}
docpad-api ➞ render ✘
docpad-api ✘

FAILURE: 6/7 tests ran successfully; 1 failed, 0 incomplete, 1 errors

Error #1:
docpad-api ➞ render ➞ markdown without extension
TypeError: next is not a function
    at DocumentModel.normalize (/home/angel/Soft/docpad/out/lib/models/file.js:1037:7)
    at DocumentModel.normalize (/home/angel/Soft/docpad/out/lib/models/document.js:305:13)
    at DocumentModel.getEve (/home/angel/Soft/docpad/out/lib/models/document.js:443:9)
    at DocumentModel.contextualize (/home/angel/Soft/docpad/out/lib/models/document.js:325:12)
    at ambi (/home/angel/Soft/docpad/node_modules/ambi/source/index.js:91:18)
    at Domain.fireMethod (/home/angel/Soft/docpad/node_modules/taskgroup/source/lib/task.js:519:5)
    at Domain.run (domain.js:221:14)
    at Task.fire (/home/angel/Soft/docpad/node_modules/taskgroup/source/lib/task.js:537:15)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by balupton** [comment]
Closed in favour of https://github.com/docpad/docpad/issues/1081
