### ISSUE TITLE
Sortby integer metadata do not work?

### ISSUE THREAD

**Issue by chenzhihuai1990** [docpad/docpad#1066]
I am new to DocPad, I have a trouble in generate a sorted navigation menu. I add an extra meta data `order` to every html files. But the finial order is not what I want.

Meta data looks like this:
```
---
title: "Home"
layout: "default"
isPage: true
order:  1
---

```
The number `1` is different for every files.
docpad.coffee:
```
docpadConfig = {
    collections:
        pages: ->
            @getCollection("html").findAllLive({isPage:true}, [{order:1}])
	# ...
}
```

template:
```
 <ul class="nav navbar-nav">
    <% for page in @getCollection("pages").toJSON(): %>
        <li class= "override <%= if page.id is @document.id then 'active' else '' %>">
             <a href=".<%= page.url %>"><%= page.title %></a>
         </li>
    <% end %>
</ul>
```

**Comment by balupton** [comment]
Can you provide a repository that reproduces the problem?

Will close in the meantime.
