### ISSUE TITLE
docpad cms plugin issue

### ISSUE THREAD

**Issue by sulthan-betabulls** [docpad/docpad#1069]
Hi i installed docpad cms plugin into docpad project. Everything seems good. Here i am getting three major issues. 
1.  when i create new page or new post it is not saving and showing under posts page. 
2.  when i try to save post and page settings they are not saving. 
3.  and no new post or new page button when i opened page or post. 

Is any alternative cms plugin for docpad....? Thanks in Advance...

**Comment by mikeumus** [comment]
Hi @sulthan-betabulls, check these two other plugins out:

- https://www.npmjs.com/package/docpad-plugin-posteditor
- https://www.npmjs.com/package/docpad-plugin-contentful

**Comment by sulthan-betabulls** [comment]
Hi @mikeumus , i installed those two plugins. All are good. 
1. but the problem is when i want to create new post or new page there is no New Post or New Page button. 

2. When i do changes in Settings section and hit on Save changes button nothing happened. it  will redirect to dashboard page. 
![image](https://user-images.githubusercontent.com/31244127/34661280-9ab563aa-f46e-11e7-8b41-e2d673f0aa24.png)

3. And the last issue is when i click on page it is an empty page. When i do changes and click on Save button it will redirect to dashboard page. And new page saved into Posts Section. Can you please tell me solution...
![image](https://user-images.githubusercontent.com/31244127/34661296-c1ccbf7e-f46e-11e7-8f57-af9b5674581b.png)

My CMS files hosted Git link is : https://github.com/sulthan-betabulls/Sample-CMS.git

Thanks in Advance...

**Comment by mikeumus** [comment]
@sulthan-betabulls, which plugin are you using exactly? The https://github.com/docpad/docpad project isn't the author of any CMS plugins, therefore, directing these questions to whoever is the author of the plugin you're using may be more effective.
