### ISSUE TITLE
Docpad CMS Issue

### ISSUE THREAD

**Issue by sulthan-betabulls** [docpad/docpad#1071]
When i click on save Changes button in Settings section. it redirects to dashboard page and changes not affecting. Can u please tell me a solution...
![image](https://user-images.githubusercontent.com/31244127/34662307-b60ef48e-f475-11e7-8bf5-aebc80f4aa39.png)

Thanks in Advance....

**Comment by mikeumus** [comment]
Hi @sulthan-betabulls, the https://github.com/docpad/docpad/ project isn't the CMS plugin. The CMS plugin is an independent plugin by another author. Which plugin are you using exactly? It would be best to post or search for your issue on that plugin's GitHub project.
