### ISSUE TITLE
New DocPad v6.80.0-beta release

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#1073]
Changelog: https://github.com/docpad/docpad/blob/beta/HISTORY.md#v6800-beta-2018-march-7

Documentation: http://v6.80.0-beta.docpad.docpad.surge.sh/docs/

Install Globally: `npm install -g docpad@6.80.0-beta`

Install Locally: `npm install --save docpad@6.80.0-beta`

Running it with CoffeeScript v1 Plugins:

```
env EDITIONS_SYNTAX_BLACKLIST=esnext docpad run
```

Running it with all CoffeeScript v2 Plugins:

```
docpad run
```

To upgrade a plugin to CoffeeScript v2 and the latest conventions, run [boundation](https://github.com/bevry/boundation) on it and send a pull request.

---

Todos before beta removal:

- [x] Upgrade all official DocPad plugins to CoffeeScript v2 using [boundation]
- [x] [Remove unnecessary cloud communication](https://github.com/docpad/docpad/issues/1041)

---

Use this thread for any errors related specifically to this beta.

v6.80 will probably be the last DocPad release. See #1072 for discussion.

Let me know what you think, or if I am just wasting my time with DocPad. Cheers!

**Comment by balupton** [comment]
Seems to be an issue with the surge.sh docs deployment. Not a biggie. I know surge is undergoing some significant upgrades soon, so will wait for them to complete in order to repush the docs. Could be a few weeks though, as their side seems to be taking a while.

**Comment by gbursson** [comment]
That's GREAT news. I have tried many static site generators and find DocPad the most intuitive and concise. All it needed really was a 'refresh' to CS2.

**Comment by balupton** [comment]
Only 3 plugins left to upgrade. Unfortunately, travis CI rate limits kicked in and I cannot finish them today.

**Comment by balupton** [comment]
Ok all plugins upgraded.

**Comment by balupton** [comment]
Ok, so the new release can't happen, as I cannot test it, as the DocPad helper is down, and is down because of https://github.com/bevry/pluginclerk/issues/2

**Comment by balupton** [comment]
Need to figure out a workaround. For now, I've run out of time today.

**Comment by balupton** [comment]
All last issues now solved. v6.80.0 on the way.
