### ISSUE TITLE
Trouble adding keywords to meta data in layout file

### ISSUE THREAD

**Issue by MadsFox** [docpad/docpad#1074]
I'm trying to add keywords to my layout file using getPreparedKeywords() from the config file, but can't seem to find out how, tried to: 
`@getBlock('meta').add(@getPreparedKeywords()).toHTML()`
But dosen't work, anybody can help me? And maybe also with where i can find the documentation to how it works.

**Comment by balupton** [comment]
Please repost on stackoverflow:

https://discuss.bevry.me/t/official-stack-overflow-support/61?u=balupton
