### ISSUE TITLE
Abstract out Server functionality into pluginland

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#1081]
v6.81 will remove all server functionality from DocPad, and place it into pluginland. A [serve plugin](https://docpad.org/p/serve) will be introduced which merely serves the `out` directory with no dynamic abilities. This will dramatically simplify the codebase, improve performance, and bring DocPad into relevance once again as an excellent static site generator.

Background reading:

- [Deprecation notice of dynamic abilities](https://discuss.bevry.me/t/deprecating-in-memory-docpad-importers-exporters/87?u=balupton)
- https://github.com/docpad/docpad/issues/821
- https://github.com/docpad/docpad/issues/705
- https://github.com/docpad/docpad/issues/1072

Closes:

- https://github.com/docpad/docpad/issues/42
- https://github.com/docpad/docpad/issues/301
- https://github.com/docpad/docpad/issues/457
- https://github.com/docpad/docpad/issues/521
- https://github.com/docpad/docpad/issues/602
- https://github.com/docpad/docpad/issues/629
- https://github.com/docpad/docpad/issues/696
- https://github.com/docpad/docpad/issues/741
- https://github.com/docpad/docpad/issues/750
- https://github.com/docpad/docpad/issues/767
- https://github.com/docpad/docpad/issues/768
- https://github.com/docpad/docpad/issues/778
- https://github.com/docpad/docpad/issues/779
- https://github.com/docpad/docpad/issues/827
- https://github.com/docpad/docpad/issues/830
- https://github.com/docpad/docpad/issues/835
- https://github.com/docpad/docpad/issues/876
- https://github.com/docpad/docpad/issues/1057
- https://github.com/docpad/docpad/issues/1058
- https://github.com/docpad/docpad/issues/1060
- https://github.com/docpad/docpad/issues/1065
- https://github.com/docpad/docpad/issues/1067
- https://github.com/docpad/docpad/issues/1081

**Comment by nfriedly** [comment]
This seems like it should be a v7 release (?)

**Comment by balupton** [comment]
It doesn't break anything that is officially supported. And resolution for all users who weren't using dynamic abilities (which have been deprecated since Feb 2016) will be to install the new plugin when it goes live.

**Comment by balupton** [comment]
Accomplished with DocPad v6.81.0

**Comment by jlukic** [comment]
You should put a prominent note that this feature was removed somewhere. 

I spent a few hours debugging things thinking that server failed to start due to plugin changes (since that was latest in readme) but realized it was because server was removed from `docpad run` without plugins.

**Comment by balupton** [comment]
It is mentioned prominently in the changelog, as well as issues and forum topics of the time period. People must read the docpad changelog for all upgrades.

As an aside, @jlukic you may be the only person outside bevry that still uses docpad.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
