### ISSUE TITLE
can't run docpad

### ISSUE THREAD

**Issue by magrawala** [docpad/docpad#1084]
I'm getting the following error when do a docpad run (Any ideas how to resolve?):

docpad run
/Users/maneesh/development/testCode/docpad-sites/maneesh-homepage/node_modules/docpad/node_modules/editions/es2015/index.js:186
        throw new DetailedError('There are no suitable editions for this environment:', { opts: opts, editions: editions, failures: editionFailures });

**Comment by balupton** [comment]
dupe of #1085
