### ISSUE TITLE
Suitable editions error on docpad run

### ISSUE THREAD

**Issue by magrawala** [docpad/docpad#1085]
I'm getting the following error when do a docpad run (Any ideas how to resolve?):

docpad run
/Users/maneesh/development/testCode/docpad-sites/maneesh-homepage/node_modules/docpad/node_modules/editions/es2015/index.js:186
        throw new DetailedError('There are no suitable editions for this environment:', { opts: opts, editions: editions, failures: editionFailures });

**Comment by balupton** [comment]
Which node version are you running?

**Comment by balupton** [comment]
Tomorrow I'll do some work to get editions v2 into docpad

https://github.com/bevry/boundation/issues/19

**Comment by balupton** [comment]
Resolved in v6.80.8
