### ISSUE TITLE
planning to drop node v4 and below when node v10 goes active LTS in october

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#1086]
https://github.com/nodejs/Release

Node v4 and below have become increasingly unstable (had several errlop crashes with them) as well as many dependencies have dropped support for them. Node v4 is already unsupported by the node team. Come October, node 6 will also be unsupported by the node team.

**Comment by balupton** [comment]
Node v4 and below and becoming increasingly unstable (had several errlop crashes with them) as well as many dependencies are dropped support for them. Node v4 is already unsupported by the node team. Come October, node 6 will also be unsupported.

**Comment by balupton** [comment]
Alright. New dependencies that we will be using only support node 6 and up. Pity they don't use Editions and our Boundation workflow.

**Comment by balupton** [comment]
So, will be dropping node 4 and below in the next minor release. Which will land sometime in the next 7 days. This will mean min node version for DocPad will be version node version 6.

The next release will revamp the console interactions, and bring all the dependencies up to date.

**Comment by RobLoach** [comment]
Congrats! Since it's a breaking change, should it be a major version release?

**Comment by balupton** [comment]
> Congrats! Since it's a breaking change, should it be a major version release?

Can't do majors until #691 is done, as otherwise a major will break compat with all plugins.

Majors in DocPad break things for everyone. Minors break things for some. As nearly everyone is probably using a modern node version, this fulfils criteria for minor.
