### ISSUE TITLE
Server not running on fresh install (OS X 10.13.6)

### ISSUE THREAD

**Issue by DEfusion** [docpad/docpad#1087]
I followed the install and getting started steps but when I run `docpad run` I don't see anything saying that it's listening and `localhost:9778` isn't responding.

```
info: Welcome to DocPad v6.81.0 (global installation: /usr/local/lib/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: https://docpad.org/donate
info: Contribute: https://docpad.org/docs/contribute
info: Plugins:
info: Environment: development
notice: DocPad is currently running without any plugins installed. You probably want to install some: https://docpad.org/plugins
info: Generating...
info: Generated 1/1 files in 0.428 seconds
info: Watching setup starting...
info: Watching setup
info: The action completed successfully
```

I've tried with `docpad run -d` but that doesn't seem to mention running a server either.

**Comment by topherfangio** [comment]
I am running into the exact same issue, but getting even less output:

```
info: Welcome to DocPad v6.81.0 (global installation: /usr/local/lib/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: https://docpad.org/donate
info: Contribute: https://docpad.org/docs/contribute
info: Plugins: haml, highlightjs, livereload, marked, sass
info: Environment: development
info: Generating...
info: The action completed successfully
```

After this, I cannot access the site at http://localhost:9778 and it doesn't appear to be running.

**Comment by topherfangio** [comment]
@DEfusion I downgraded to v6.80.0 (`npm install -g docpad@6.80.0`) and it's working.

I had some plugin errors that were causing some issues, so I got them fixed and tried re-installing/running the latest version (6.81.0) and it broke again; so I have just downgraded for now in hopes that they fix it soon.

**Comment by balupton** [comment]
Intentional, as noted by the changelog for that version.
