### ISSUE TITLE
Trimming of Team Members

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#1096]
I will be trimming everyone who is not active from the DocPad teams for security and maintenance reasons. Please post a comment below if you intend to stay active and continue maintenance. I'll do the trimming on the 24th of November 2019.

@docpad/extras-team @docpad/meta-team @docpad/core-team

**Comment by RobLoach** [comment]
I don't think I've made or reviewed any pull requests for DocPad in a while. Happy to stay on, or depart :wink: :heart:

**Comment by SergiusTheBest** [comment]
I'd happy to stay.

**Comment by sdomagala** [comment]
Hi @balupton,
I'm not really active here since I don't use DocPad anymore - I will continue to support my DocPad plugins but I probably won't contribute much, so I don't mind being dropped

**Comment by ashnur** [comment]
I am active, although I don't think there is anything I am responsible for and was never really part of the team. Once I used a wordpress plugin to populate docpad through old wp admin. It was a fun experiment. 
Nevertheless, I would rather not severe contacts.

**Comment by jeremyfa** [comment]
Do as you like, I don't really have the bandwidth to maintain anything here anyway :)

**Comment by alexwoehr** [comment]
I have two old sites with docpad but never upgraded, so it's just the
generated HTML that I am maintaining. I guess I will bow out at this point.

**Comment by balupton** [comment]
Trimming complete. Thanks everyone.
