### ISSUE TITLE
arch linux forces me to run docpad as root

### ISSUE THREAD

**Issue by rdthree** [docpad/docpad#150]
npm is in root and so are its modules apparently.  i am using the nodejs package from 'community'.

the problem with this is that i cannot install modules such as docpad without using sudo.  this then means that docpad itself only works with sudo, which results in websites that i create all having root permissions.  is there a way around this?

it would be best if i could do an

<code>
  npm -g install docpuad
</code>

as user and not as root.  if i do it as user i get the following:

<code>
  [user@arch]$ npm install -g docpad

  npm ERR! Error: EPERM, Operation not permitted
  npm ERR!     at /usr/lib/node_modules/npm/lib/utils/uid-number.js:42:18
  npm ERR!     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:54:5)
  npm ERR!     at ChildProcess.emit (events.js:70:17)
  npm ERR!     at maybeExit (child_process.js:360:16)
  npm ERR!     at Process.onexit (child_process.js:396:5)
  npm ERR!
  npm ERR! Please try running this command again as root/Administrator.
</code>

**Comment by austinbutler** [comment]
This allowed me to installed packages globally without root: https://github.com/glenpike/npm-g_nosudo

**Comment by Greduan** [comment]
@austinbutler That looks cool. Another solution is to use something like NVM which will install Node.js as your user, not as root: https://github.com/creationix/nvm

**Comment by austinbutler** [comment]
I guess I just like to have Node installed using Arch's package manager, so I went the other route. But options are always good!

**Comment by Greduan** [comment]
@austinbutler Yeah I getcha. I used to do that. But then I needed to use different versions (0.10 and 0.11) I needed to start using NVM. Which also allows me to completely skip the root permission problems.
