### ISSUE TITLE
Files like a.min.js in documents are saved to a.min

### ISSUE THREAD

**Issue by faridnsh** [docpad/docpad#192]
Update: In case you got an error like following:

> warning: Rendering the extension "eco" to "html" on ".../src/layouts/default.html.eco" didn't do anything

It might mean that you don't have the right plugin that renders the extension. Have a look at [plugins page](https://docpad.org/docs/plugins) to see how to find and install plugins.

---

There are also things like jquery.a.b.min.js which will be saved to jquery.a. The issue comes from this part https://github.com/bevry/docpad/blob/master/lib/models/file.coffee#L369, where it takes only the first extension.

I think the solution would be to push the extensions that can be rendered to a variable during render, and remove them from extensions. To do that, we need to make every rendering plugin to return a value that tells us that tells us that they have changed the content. So we remove the extension from the extensions variable.

**Comment by garthk** [comment]
@alFReD-NSH, could you edit the bug description to straighten out beginners? They're being sent here by the following error:

> `warning: Rendering the extension "eco" to "html" on ".../src/layouts/default.html.eco" didn't do anything`
> `Explanation here: http://docpad.org/extension-not-rendering`

With those extensions and that filename, the problem is that they forgot to `docpad install eco`. A note at the top would spare them wading through a couple dozen comments, none of which help.

**Comment by alFReD-NSH** [comment]
@balupton I feel like linking to issue is a bad explanation for the `extension not rendering`, as @garthk said.

**Comment by mikeumus** [comment]
:+1: 

Just solve it in the command line output if possible.

**Comment by balupton** [comment]
> Just solve it in the command line output if possible.

`http://docpad.org/extension-not-rendering` is a redirect inside the docpad website code, it can go wherever we want. The issue here, and such things is the same. It could probably go to a well crafted FAQ enty instead if someone wants to work on it?

**Comment by airtonix** [comment]
getting similar error (custom plugin for nunjucks), but template actually still gets created. how to supress this?

is it caused by my plugin not returning something specific?

**Comment by balupton** [comment]
@airtonix is there a repo for the plugin?

**Comment by airtonix** [comment]
I'm waiting for permission to publish it on github.

full stack web application developer.
Django, Python, SailsJs, Nodejs, Linux and Docker.
fear is the mind killer, the little death inside.

**Comment by airtonix** [comment]
@balupton Ok permission granted:

https://github.com/fusion-com-au/docpad-plugin-nunjucks/blob/master/src/nunjucks.plugin.coffee

**Comment by cameronjroe** [comment]
Hey all,

New to DocPad, but wanting to chime in on the approach to extension rendering. In general, I'm not particularly a fan of this solution. 

I don't see the elegance in chaining extension suffixes together for a build step. Why would people need to compile so many different suffixes anyway? Is there really a need to go from `.eco` to `.md` to `.html`? Aren't we only really dealing with one or two templating engines including markdown in general?

Thoughts on utilizing a more configuration-based approach and taking advantage of something like [consolidate.js](https://github.com/tj/consolidate.js/)? It would allow for a clear understanding of what template engine you're using. In a docpad.conf.js, you can already set the template engine and at the end of the day we're creating a static site in HTML, not an app.

As for markdown, Jekyll specifically makes you put posts in a `_posts` directory. A similar approach could be taken, and even allow for a custom directory to be pointed to for specific rendering.

Also, considering that most of the community is moving towards ES6, React, webpack/browserify, I think featuring first-class support for React would be a great idea.

**Comment by balupton** [comment]
> This would reduce overhead and allow for issues to be consolidated in the consolidate plugin itself, which could have a plethora of helpers, utils, etc. to handle these issues, hence reducing these templating issues.

Is https://github.com/robloach/docpad-plugin-consolidate helpful?



> Also, considering that most of the community is moving towards ES6, React, webpack/browserify, I think featuring first-class support for React would be a great idea.

Would be cool to see a babel plugin for sure!

**Comment by almereyda** [comment]
It is quite distracting to read

```
warning: A warning occured:

Error: Rendering the extension "eco" to "html" on "/srv/git/Fundus/github.com/TransforMap/transformap.github.io/src/render/embed.html.eco" didn't do anything.
Explanation here: http://docpad.org/extension-not-rendering
```

after `./node_modules/docpad/bin/docpad run` despite the site is served and lively reloaded well.

**Comment by balupton** [comment]
If it is a bother, the correct solution is to remove the useless extension or add some functionality to render… there is no point wasting performance on useless tasks.
