### ISSUE TITLE
Brackets Plugin

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#357]
Considering Brackets now has a npm installable distro, we can now do up a brackets plugin for DocPad. See #123

It will be great for editing locally, however for editing on a remote server, need a way of getting the changes into the repo. That could be a separate plugin.

**Comment by AdrianoCahete** [comment]
:+1:

**Comment by balupton** [comment]
As per https://discuss.bevry.me/t/deprecating-in-memory-docpad-importers-exporters/87 this issue is now outside the scope of DocPad.
