### ISSUE TITLE
Text Plugin & Markdown Not Rendering GFM

### ISSUE THREAD

**Issue by coreybutler** [docpad/docpad#403]
I'm not sure if this is a bug, enhancement request, or just sheer lack of understanding of docpad internals (I'm new to it, and new to coffeescript too). Anyhow...

I am importing a blog from Tumblr, which allows you to add `<!-- more -->` to your entry. The content written before this generates an article summary, which is what shows up on my list of blog entries. I intend to put small code snippets in these summaries (written as markdown). When I display the fully rendered page, it works as expected, generating GFM formatted code. However; the snippet only renders as regular markdown. Since I'm using the text plugin to render this, I suspect it is not using the marked plugin that the "full article" page is using... thus the difference.

For example, I have the following source as my "summary":

---

---
my file params

---

``` ruby
def test
push "something"
```

``` js
var x = 1;
console.log(x);
```

... rest of the content ...

---

Using the _text_ plugin, it renders like:
`ruby def test push "something"``js var x = 1; console.log(x)`

Using the _marked_ plugin, it renders like:

``` ruby
def test
push "something"
```

``` js
var x = 1+2;
console.log(x);
```

For completeness, here's the rest of the relevant bits in this operation:

In my `docpad.coffee`, I have a crude function to extract the summary:

``` coffeescript
getSummary: (page) ->
  if page.hasOwnProperty('summary')
    return page.summary
  c = page.body.indexOf('<!-- more -->')
  if c > 0
    return page.content.substring(0,c)
  page.content.substring(0,355)+'...'
```

And in my `layout.html.md.eco`, I use the following code within a loop of my article list:

```
<text render="html.md">
  <%- @getSummary(post) %>
</text>
```

I would expect my "summary" would render with GFM, not as plain markedown. So, I've arrived at the conclusion the _text_ plugin has it's own markdown renderer? Again, I'm new to docpad, and hopefully this is an easy thing to fix. Perhaps someone could point me in the right direction? Is there a way to configure the _text_ plugin use the _marked_ plugin?

---

Using **docpad@6.21.4**.

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
