### ISSUE TITLE
Two blog posts

### ISSUE THREAD

**Issue by npofopr** [docpad/docpad#431]
I'm trying to do 2 blog.
And almost all of it.

A list of articles displayed:
The first https://github.com/npofopr/_altyncev/blob/master/src/documents/posts.html.eco (http://altyncev.ru/posts), and the second https://github.com/npofopr/_altyncev/blob/master/src/documents/postsoleg.html.eco (http://altyncev.ru/postsoleg).

But the specific article in the second blog, is displayed with the wrong template
https://github.com/npofopr/_altyncev/blob/master/src/layouts/postoleg.html.eco
It is worth

> layout: 'dpostoleg'

In fact, output

> layout: 'defaultpost'

In what may be the problem? Can conflicts of plug-ins? 
Or prompt, where you can find the answer. Certainly it is sold)

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
