### ISSUE TITLE
Dicussion: Abstract/modularize all the things

### ISSUE THREAD

**Issue by alFReD-NSH** [docpad/docpad#445]
So I want to be able to generate my docpad website on a browser, but docpad comes with lot of other things rather than just the generation code. And I only need the core to be in the browser. So I'm thinking of making core a seperate module, which can be fed with files and relative paths and modules and then it outputs some files. Only that and nothing more.

So I have this proposed the interface:

* `new DocpadGenerator(config)`
* `DocpadGenerator::add{File,Document,Layout}(path, file)` - Will add a file to the database. The root of the path will be the `src` directory.
* `DocpadGenerator::removeAll()` - Will remove all files from database.
* `DocpadGenerator::remove(path)` - Will remove a file from database. The root of the path will be `src` directory.

* `DocpadGenerator::generate()` - Will make docpad generator to render the files that was added. After this any file related method or render should throw an error when called since the generator becomes read-only.
* `DocpadGenerator::on(event, fn)` - Will call `fn` on the `event`.
* `DocpadGenerator::renderDynamic(reqLikeObject, cb)` 

Events:

* `finishFile(path, file)` - Will call the callback when a file was finished.
* `finish` - Will call the callback when all files are finished. After this point the generator is writable. Files are not cleaned and changed files for re-rendering can be changed using `addFile` method.

**Comment by Zearin** [comment]
Some off-the-top-of-my-head ideas for splitting up the titanic class in `lib/docpad.coffee`…

Breaking the giant class into chunks of logically-related functionality, how about something like:

* `actions.coffee` (I think “actions” are basically the commands available on the console?)
* `server.coffee`
* `events.coffee`
* `config/` (see #390)
    * `core.coffee`  (or perhaps `core.cson`?  surely there must be functionality, but I like the idea of putting as much configuration into CSON files as possible)
    * `paths.coffee`
    * `*.coffee` (others by logical grouping)
    * Perhaps a config utility that lets people query docpad’s config from the console?  I’m mean more powerful than `docpad info`…something more like `npm config <get | set | list | …>`!
* `skeletons.coffee`
* `env.coffee`
* `template-data.coffee`
* `plugins/`
    * `plugins.coffee` 
    * `loader.coffee`

**Comment by balupton** [comment]
+1 good thinking, the original idea of a huge class is so people can extend the docpad class - however I doubt anyone has ever done that ever, so we can deprecate that requirement and break it out into smaller classes

**Comment by balupton** [comment]
Moving over to https://github.com/docpad/docpad/issues/1046
