### ISSUE TITLE
docpad fails to generate files for large size websites

### ISSUE THREAD

**Issue by segalr3** [docpad/docpad#446]
docpad version = 6.21.10
node version = v0.8.18
npm version = 1.2.7
Ubuntu 12.04

What i did:

I have a website with many languages, which i am migrating to docpad.
First i tried to generate for 2 languages, all was generated fine.
Then i copied the rest of the languages folders to the documents directory and tried to generate again.

what happend:

I actually hit the nodejs memory limit:

"FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory"

no files were created in the out directory.

Please advise

**Comment by balupton** [comment]
The [raw plugin](http://docpad.org/p/raw) solves this if most of your files are static files. However, if they are documents, it gets more interesting.

Moving the discussion here: https://discuss.bevry.me/t/docpad-is-slow-for-large-websites/47
