### ISSUE TITLE
Ignoring patterns.

### ISSUE THREAD

**Issue by pismute** [docpad/docpad#451]
Hi. @balupton.

I found out 4 ignoring options(ignorePaths, ignoreHiddenFiles, ignoreCommonPatterns, ignoreCustomPatterns). I don't understand ignorePaths and ignoreCustomPatterns. how do you use them?

`igorePaths` requires absolute paths because path is absolute path. but I need reletive path to project dir:

```
isIgnoredPath: (path,opts={}) ->
  ...

  # path is absolute
  if opts.ignorePaths
    for ignorePath in opts.ignorePaths
    if path.indexOf(ignorePath) is 0
      result = true
      break
  ...
```

`ignoreCustomPatterns` test basename, it has only filename and extension without path infomation:

```
...

# Test Ignore Patterns
result =
  result or
  (opts.ignoreHiddenFiles    and /^\./.test(basename)) or
  (opts.ignoreCommonPatterns and opts.ignoreCommonPatterns.test(basename)) or
  (opts.ignoreCustomPatterns and opts.ignoreCustomPatterns.test(basename)) or
  false
...
```

I think it should be like [includes and excludes of Ant FileSet](http://ant.apache.org/manual/Types/fileset.html).

Actually What I want. My blog consists of 380 files so that fully generating costs me about 22 seconds. It is too long, so boring.--;
My plan is making 2 environments. One is for writing, another is for generating. In writing enviroment, docpad ignores old files to save time. I don't care most of old files when I am writing. But when I really put off, I want to be included all files.

Any Idea?

**Comment by balupton** [comment]
https://github.com/bevry/ignorefs

Seems ignorefs has changed the code around here, but the last commit around it was in December 2013, so perhaps it was updated then considering this repo is older than that commit, perhaps is has been addressed by that old commit, as the code is now:

```
		result =
			result ||
			(opts.ignoreHiddenFiles    && (/^\./).test(basename)) ||
			(opts.ignoreCommonPatterns && opts.ignoreCommonPatterns.test(basename)) ||
			(opts.ignoreCommonPatterns && opts.ignoreCommonPatterns.test(path)) ||
			(opts.ignoreCustomPatterns && opts.ignoreCustomPatterns.test(basename)) ||
			(opts.ignoreCustomPatterns && opts.ignoreCustomPatterns.test(path)) ||
			false
```
