### ISSUE TITLE
Add more locales to the DocPad CLI, the website, and add ability for localisation to plugins

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#481]

**Comment by jeffmcneill** [comment]
Hi, any gettext mo/po file advances? I want to migrate to docpad but have multilingual sites. gettext makes things a lot easier.

**Comment by balupton** [comment]
@jeffmcneill this issue is for translating the docpad CLI, for translating your project see #17

**Comment by balupton** [comment]
Considering what is actually needed for this (see updated title), I'm going to shelve this as too ambitious and not enough interest.
