### ISSUE TITLE
Get it to work with proxies

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#488]
http://stackoverflow.com/q/15942403/130638

Current workaround, agree to the TOS manually by filling in your `~/.docpad.cson` or `~/Dropbox/.docpad.cson` file yourself:

```
{
  name: "Your name"
  email: "Your email"
  username: "Your username"
  subscribed: true
  subscribeTryAgain: null
  tos: true
  identified: true
}
```
## HOWEVER

Please post a comment below on whether or not you use `sudo` with node. If you do, it means node is installed globally and probably shouldn't be, you can use the install intructions here http://learn.bevry.me/node/install to avoid permission issues. If these better install instructions fix it, let us know.

**Comment by guaka** [comment]
I suggest giving DocPad a `--verbose` option.

**Comment by marcusstenbeck** [comment]
No sudo, this was the only thing that worked.

**Comment by balupton** [comment]
@guaka would `--verbose` be different than the already existent `--debug` flag?

**Comment by balupton** [comment]
@marcusstenbeck interesting... what was the precise issue you were facing?

**Comment by marcusstenbeck** [comment]
@balupton I was getting the perpetual TOS statement.

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
