### ISSUE TITLE
WordPress Importer

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#49]
As a User, I want the ability to import my wordpress data, so that migration will be a lot easier

See https://github.com/obazoud/docpad/commit/e21b10fd6a32e3781cc4f8cc1b4328e11413920f for reference.

Pull request here: #78

**Comment by balupton** [comment]
As per https://discuss.bevry.me/t/deprecating-in-memory-docpad-importers-exporters/87 this is outside the scope of DocPad.

**Comment by ashnur** [comment]
On the page https://discuss.bevry.me/t/deprecating-in-memory-docpad-importers-exporters/87
I get only a blank page and javascript errors.

**Comment by balupton** [comment]
@ashnur try now

**Comment by ashnur** [comment]
Yeah, it works now, thanks. Also, the change and the reasoning seems quite sound.
