### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by davidsteinberger** [docpad/docpad#496]
For some reason I'm only getting this error no matter what I do with docpad _rev 31_.
Could that be related to Node v. 10.5 (see #455)?

```
error: An error occured: Arguments to path.join must be strings TypeError: Arguments to path.join must be strings
        at path.js:360:15
        at Array.filter (native)
        at Object.exports.join (path.js:358:36)
        at /usr/local/lib/node_modules/docpad/out/lib/plugin-loader.js:75:71
        at /usr/local/lib/node_modules/docpad/node_modules/bal-util/out/lib/paths.js:58:18
        at fs.js:266:14
        at Object.oncomplete (fs.js:107:15)
```

**Comment by jegtnes** [comment]
Had the same error, removing node_modules and running `npm install` works for me too. It's truly the Node equivalent of 'have you tried turning it off and on again?'.

**Comment by balupton** [comment]
Must just be a dependency version conflict.

**Comment by jegtnes** [comment]
Yeah, wasn't really expecting a fix for this—just wanted to confirm this for anyone who stumbles across it (like I did when attempting to diagnose this issue). :)

Thanks for all your work on DocPad, @balupton, I'm trialling it for the first time and finding it very useful indeed.
