### ISSUE TITLE
Docpad caching out of sync when deleting files from 'out' directory.

### ISSUE THREAD

**Issue by d9su** [docpad/docpad#507]
I addressed this in stackoverflow before, I apologize for the delay in posting this in docpad issue tracker.

http://stackoverflow.com/questions/16151475/docpad-where-is-the-preview-node-server-serving-files-from

Basically I think the local preview server is serving files from the out directory, but if I remove a file from the out directory I can still navigate to that page from browser instead of an expected 404 error.

I'd imagine this is a cache related bug.

**Comment by balupton** [comment]
This was fixed in 6.63.0 which disabled the caching by default, which was introduced in 6.55.0, and will be completed removed in 6.81.
