### ISSUE TITLE
When a user creates a dynamic page, warn the user if they don't have the cleanurls plugin installed

### ISSUE THREAD

**Issue by SteveMcArthur** [docpad/docpad#521]
Quite often when creating a dynamic page people don't know why it doesn't work and there is no error message. The problem is that they don't have the [cleanurls](https://npmjs.org/package/docpad-plugin-cleanurls) plugin. It would be good to have a message highlighting this fact. Linked perhaps to issue #301

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad/issues/1081
