### ISSUE TITLE
Reduce overlap between docpad and grunt task resposibilities

### ISSUE THREAD

**Issue by hurrymaplelad** [docpad/docpad#524]
Seems like docpad could have fewer responsibilities (less code) by embracing and depending directly on Grunt.    

Couple examples of the tension I feel between grunt tasks, docpad plugins, and docpad core:

- #402 is just as easy in a build task as docpad plugin, and potentiallly more generally useful.
- Docpad provides a dev server almost identical to grunt.  Configuring what file changes trigger a restart is easy with grunt-contrib-watch.
- https://gist.github.com/balupton/3898915

Grunt is kind of an arbitrary choice given the many JS build systems, but It seems to have the most momentum.

**Comment by balupton** [comment]
Replaced by https://github.com/docpad/docpad/milestones/Abstract%20all%20the%20things
