### ISSUE TITLE
Watch files but don't include them in copy phase

### ISSUE THREAD

**Issue by ryanmaxwell** [docpad/docpad#540]
Hi - I can't seem to find a configuration option which allows you to watch for changes in a file - but not copy those files to the out directory.

I have found the "ignorePaths" array - but that means that it won't watch those directories.

The use-case for this feature is for the .less files. Typically a .less file includes another  .less file via the @import syntax.

e.g I have a master file

documents/styles/master.css.less

which has a line `@import 'inc/variables';`
and the file documents/styles/inc/variables.less

Only the master .less file needs to be compiled - the one which is imported needs to be watched for changes - but doesn't need to be compiled and copied separately.

In the out path I am ending up with a redundant /out/styles/inc/variables.css

**Comment by balupton** [comment]
The [raw plugin](https://docpad.org/p/raw) should address this need.
