### ISSUE TITLE
DocPad EcoSystem Architecture Vision

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#543]
Just did this graphic up, it shows how importers #500 tie together into the whole vision that is DocPad:

![jmmz](https://cloud.githubusercontent.com/assets/61148/6266324/f963bdce-b872-11e4-87d0-8cca343241db.png)

Believe in it! Speed it up by funding it! #532

**Comment by jtwebman** [comment]
@balupton the importer workflow image src is broken. Do you still have the image somewhere? I want to help out with some of these.

**Comment by balupton** [comment]
@jtwebman done

**Comment by jtwebman** [comment]
@balupton So do importers not go through plugins? Can I have a importer that formats a document in say Markdown that then goes through the normal plugins?

**Comment by balupton** [comment]
Replaced by https://github.com/docpad/docpad/milestones/Abstract%20all%20the%20things
