### ISSUE TITLE
Discussion: Memory usage optimisations

### ISSUE THREAD

**Issue by aaronpowell** [docpad/docpad#545]
I recently switched my personal website to DocPad ([source](https://github.com/aaronpowell/aaronpowell.github.io)) and once completing the migration I came across something troubling, I deployed the site to Heroku but it kept crashing. Looking in the logs it said that it crashed because it was out of memory in my Heroku instance.

So I decided to run DocPad locally to see what was going on with the memory usage, and I noticed something troubling, it was blowing out to >900mb of memory usage to generate the site! Even if I just used `docpad run` it was idle at around 850mb.

Now I have a decent number of pages on my site, with the tagged and paged plugins I hit close to 400 generated pages, but still this memory usage seems stupidly high for what is really just a static site, resulting in my inability to deploy my site anywhere that will dedicate less than 1gb of ram to my instance, which IMO completely defeats the point of generating a static site.

Ultimately I worked around this by committing my `out` folder to my git repo and writing my own static server on top of it, which then runs at an idle of ~20mb of memory usage which is more in line with what I'd expect. I've detailed my workaround [here](http://www.aaron-powell.com/posts/2013-06-18-solving-docpads-excessive-memory-usage.html).

I honestly can't see a good justification for this level of memory usage.
# Environment:
- Node 0.10.10, Windows 8, x64 (I've tested across 3 machines running Win8 with the same memory usage, and I know Heroku exceeded 512mb but not the exact figure)
- DocPad 6.44.0
- Plugins listed [here](https://github.com/aaronpowell/aaronpowell.github.io/blob/master/package.json#L9)

**Comment by balupton** [comment]
v6.80.0 fixed this

**Comment by balupton** [comment]
https://github.com/docpad/docpad-skeleton-benchmark

- docpad 6.78.3 rendered 1000 eco 2.2.1 documents with layout in 47.92 seconds
- docpad 6.83.1 rendered 1000 eco 2.5.0 documents with layout in 6.363 seconds
