### ISSUE TITLE
Request: plugin for converting CSS into inline style attributes

### ISSUE THREAD

**Issue by interpaul** [docpad/docpad#546]
Hi,

I think it is good idea to make a plugin for converting CSS into inline style attributes inside HTML like [premailer](http://premailer.dialect.ca/) does it. ([premailer on github](https://github.com/alexdunae/premailer))

The goal is to generate html newsletters with all styles inlined. 

Maybe there is something existing that could manage this task?

**Comment by rogchap** [comment]
Was looking for a way to automate my email templates and thought of using DocPad.
 I also currently have the extra steps of coping css stored in a file into the style tag and then passing the html through an css in-liner tool.
If no one has any suggestions I might be look into creating this plugin.

**Comment by rogchap** [comment]
Done: https://github.com/kayla-tech/docpad-plugin-cssinliner

**Comment by interpaul** [comment]
Thanx @rogchap
