### ISSUE TITLE
docpad update does not push docpad-plugin-jade to 2.4.1

### ISSUE THREAD

**Issue by mgroves84** [docpad/docpad#548]
Using 6.45 and run the docpad update command to force all plugins to get updated. Docpad-plugin-jade only was updated to 2.4.0. 

This could be since npmjs.org does not have 2.4.1 yet. https://npmjs.org/package/docpad-plugin-jade

npm install --save --force docpad-plugin-jade@2.4.1 does work for some reason.

**Comment by balupton** [comment]
Closing due to age. Further discussion should go through the new channels for such things:
https://github.com/docpad/docpad/blob/master/CONTRIBUTING.md
