### ISSUE TITLE
'docpad run' asks me which program I want to open the file 'docpad.js' with

### ISSUE THREAD

**Issue by craigagnew** [docpad/docpad#561]
Hi guys,

In response to the following tweet...

https://twitter.com/DocPad/status/360032863309135876

My experience went something like this:
1. I went through the installation steps on the docpad website, including installing Git, Node.js and Growl (plus extension for notifications).
2. I fired up command prompt and done a 'mkdir [foldername]'
3. Under my newly created folder I ran 'docpad run', which prompted me to choose a template - I was expecting this as I wanted to have a look at some of the examples.
4. After the files were checked out from the repository I tried hitting localhost:9778, which came back 404.
5. I thought another 'docpad run' was in order then, so executed that and Windows prompted me to select a program to open the 'docpad.js' file that exists in the directory of my website (shown below).
6. If I select a program, or if I click cancel, nothing (docpad related) happens and I either get a new line in the command prompt or an 'Access denied' if I cancelled.

I'm running Windows 7 64-bit.

Thanks,
Craig

![image](https://f.cloud.github.com/assets/5082297/849501/66d723a0-f475-11e2-9a50-8fd34003375b.png)

**Comment by amb26** [comment]
This resolution is no good since it prevents me from writing cross-platform scripts invoking "docpad". I can't insert "docpad.cmd", e.g. into an npm script definition

**Comment by balupton** [comment]
@amb26 nothing we can do though, as this is just windows being lame.

Perhaps https://github.com/dthree/cash or https://blog.docker.com/2016/03/docker-for-mac-windows-beta/ will help

**Comment by pflannery** [comment]
@amb26 

You could rename `docpad.js` config file to something else and then run

```cmd
docpad run -c myconfig.js
```

or

You can use a `docpad.coffee` formatted file instead

or

use powershell or bash as they dont have this problem.

**Comment by amb26** [comment]
@pflannery - Thanks for the productive suggestion. Option 1 worked fine. I didn't find docs on docpad's CLI options, I would have expected them together with the rest of the CLI docs at http://docpad.org/docs/cli/ ?

**Comment by balupton** [comment]
`docpad --help` should be comprehensive
