### ISSUE TITLE
Suggestion: Robust internal hyperlinks between documents

### ISSUE THREAD

**Issue by gebrits** [docpad/docpad#593]
I think it's worth discussing how to improve internal linking of documents in markdown. I.e: I'd like to be able to reference a document by a static identifier, which on site-generation would resolve to the actual url. 

e.g: 
`[my referenced doc](/posts/post1)` 

This has the benefit of documents being able to change urls (through the url meta property, etc. ) without documents pointing to that document need changing too. 

Afaik this doesn't work at the moment. I've only known Docpad for a small week so I could be wrong :)

This would enable things as "Living Documents" in which documents covering developing stories are updated when news rolls in. To reflect a change to the document the title is changed, which in turn updates the slug, which in turn kicks off the doc being added (again) to say an rss / atom feed, etc. All previous urls of the document would automatically 304 to the new url. 

See http://www.fastcolabs.com/3009577/open-company/this-is-what-happens-when-publishers-invest-in-long-stories/ for some awesome story why "living documents" are cool. 

technically: the static identifier could well be the physical filepath of the document I believe.

Hope this is worth discussing. I'm willing to participate in some development if there's interest.

**Comment by balupton** [comment]
Use the `simpleRedirects` from the [cleanurls plugin](https://docpad.org/p/cleanurls)
