### ISSUE TITLE
Exporters / Sources

### ISSUE THREAD

**Issue by gebrits** [docpad/docpad#597]
See https://github.com/bevry/docpad/issues/597#issuecomment-25136442 for latest plan.

---

Would it be useful to have a 'generic export hook / command' that allows you to loop all documents as they exist just before they would be written to `out` (but without doing the actual writing)?

I imagine this to be a separate `docpad` cli command, say `docpad export`, which parameterized could run your export of choice.  

particularly: I wanted a way to quickly generate the accurate set of meta-data properties of all documents. Since these meta-data properties may be enriched  by all kinds of hooks there needs to be a reliable way to process the documents as they normally would. I.e: all hooks capable of changing the meta-data when doing a `docpad generate` would need to run when doing the `docpad export` 

I've quickly hacked the following (a separate node project which includes docpad) which seems to run most (?) of the needed hooks before it loops the documents. It seems to run okay and obviously is blistering fast since if skips all the actual writes: 

    // Add DocPad to our Application
    var docpadInstance,
	_ = require("lodash");

    var docpadInstanceConfiguration = {
        env: 'static'
    };

    var balUtil = require('bal-util'),
	extractOptsAndCallback = require('extract-opts').extractOptsAndCallback;

     docpadInstance = require('docpad').createInstance(docpadInstanceConfiguration,     function(err){
    if (err)  return console.log(err.stack);

    var that = docpadInstance;

    var generateRender = function(opts, next) {
		var docpad, _ref1;
		_ref1 = extractOptsAndCallback(opts, next), opts = _ref1[0], next = _ref1[1];
		docpad = that;
		opts.templateData || (opts.templateData = that.getTemplateData());
		opts.renderPasses || (opts.renderPasses = that.getConfig().renderPasses);
		balUtil.flow({
		  object: docpad,
		  //ORIG
		  //action: 'contextualizeFiles renderFiles writeFiles',
		  action: 'contextualizeFiles',
		  args: [opts],
		  next: function(err) {
		    return next(err);
		  }
		});
		return that;
	};

        //overwrite
        docpadInstance.generateRender = generateRender;

        docpadInstance.action('generate', function(err){
		if(err){
			throw new err;
		}
		_.each(docpadInstance.getCollection('html').models, function(doc){
			//do stuff
		})
        });
    });

I think it wouldn't require that much work to make this into something more robust. Would there be any interest for such a feature?

**Comment by balupton** [comment]
This approach no longer makes sense. See here for the latest thoughts: https://discuss.bevry.me/t/docpad-architecture-vision-2015/46
