### ISSUE TITLE
asciidoc converter

### ISSUE THREAD

**Issue by reyman** [docpad/docpad#599]
Asciidoc renderers / converters ?

**Comment by derberg** [comment]
you know if there is anybody working on that plugin? markdown sucks because it can't be used in divs and asciidoc sounds like a great alternative for complicated docs

**Comment by balupton** [comment]
> markdown sucks because it can't be used in divs

Can you give an example of that?

**Comment by Greduan** [comment]
If you use a div in a Markdown file, like so:

    <div class="whatever">
        _italic_.
    </div>

Markdown will interpret that as:

    <div class="whatever">
        _italic_.
    </div>

Instead of:

    <div class="whatever">
       <p><i>italic</i>.</p>
    </div>

**Comment by derberg** [comment]
See my comments and this ticket https://github.com/chjj/marked/issues/488

So for example in a sample.html.md file I would put
<div class="something">
Super `strange` test **here**
```
{
"test":"test"
}
```
</div>

and the result would be that the simple markdown would be parsed but the code would not be rendered correctly with pre as a block but one line

so what currently we are using is the text plugin

<div class="something">
<t render="html.md">
``` json
{
	"test":"some",
	"test":"plus"
}
```
</t>
</div>

I hate workarounds

**Comment by balupton** [comment]
> so what currently we are using is the text plugin

Hehe, exactly why I was asking :-) :+1:

**Comment by fboulay** [comment]
Hello all !
I had the same needs, so I created a Docpad plugin for asciidoc. I released the first version today, so it might contain some bugs. 

here it is:
https://github.com/fboulay/docpad-plugin-asciidoc

**Comment by balupton** [comment]
Cool. I'll close this issue then!
