### ISSUE TITLE
Bug: DocPad Router doesn't handle URL escaping

### ISSUE THREAD

**Issue by AndrewJo** [docpad/docpad#602]
First of all, I want to thank @balupton and everyone involved in DocPad development. The framework allowed me to quickly build a [corporate website](http://verdigristech.com) for a company I work for within a matter of days.

While writing a custom collection in docpad.coffee, I came across an issue which seems to be a bug in the router code.

This is a snippet of the custom collection for job listings:

``` coffeescript
collections:
  jobs: (database) ->
    query = relativeOutDirPath: $startsWith: 'jobs'
    sorting = [locationDir: 1, categoryDir: 1, subcategory: 1]
  database.findAllLive(query,sorting).on 'add', (document) ->
    attr = document.attributes
    layout = 'job_detail'
    standalone = true
    locationDir = pathUtil.basename pathUtil.resolve (pathUtil.dirname(attr.fullPath) + '../../')
    location = locationDir.replace(/[\-0-9]+/,'')
    categoryDir = pathUtil.basename pathUtil.resolve (pathUtil.dirname(attr.fullPath) + '../')
    category = categoryDir.replace(/[\-0-9]+/,'')
    subcategoryDir = pathUtil.basename pathUtil.dirname(attr.fullPath)
    subcategory = subcategoryDir.replace(/[\-0-9]+/,'')
    name = attr.basename.replace(/[\-0-9]+/,'')
    urls = [ "/jobs/#{location}/#{category}/#{subcategory}/#{name}" ]

    document.setMetaDefaults({
      layout
      standalone
      locationDir
      location
      categoryDir
      category
      subcategoryDir
      subcategory
      name
      url: urls[0]
    }).addUrl(urls)
```

Now, if the location is a single word, it works as expected. For example, when you hit `www.example.com/jobs/Seoul/Engineering/Software/node-js-developer` on the browser address window, it works fine and displays the file that sits in `out/jobs/Seoul/Engineering/Software/node-js-developer.html`.

This however breaks when there are characters which causes URL escape characters to be inserted by the browser (e.g. spaces -> %20). When you try to hit `www.example.com/jobs/San Francisco/Engineering/Hardware/embedded-linux`, the browser escapes the spaces with %20 and DocPad returns 404. Interestingly enough, if you request `www.example.com/jobs/San Francisco/Engineering/Hardware/embedded-linux.html` on the browser, it serves up the document without a hitch.

I figured it was the issue with the DocPad router not properly detecting escaping because if I change the collections code as follows, it no longer 404s:

``` coffeescript
...
    subcategory = subcategoryDir.replace(/[\-0-9]+/,'')
    name = attr.basename.replace(/[\-0-9]+/,'')
    urls = [ "/jobs/#{location}/#{category}/#{subcategory}/#{name}" ]

    # Temporary work-around to fix URL escaping issue
    urls[0].replace(' ', '%20')

    document.setMetaDefaults({
      layout
      standalone
      locationDir
...
```

I'm guessing this is a bug and not a design choice (or is it? :wink:)

Again, keep up the great work! :+1: :beers:

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad/issues/1081
