### ISSUE TITLE
During `docpad render` opts.templateData does not include full templateData for plugins as it does when using `docpad run` or `docpad generate`

### ISSUE THREAD

**Issue by jeffbski** [docpad/docpad#614]
In developing a plugin which uses the `render(opts)` method, that when I am doing a `docpad run` or `docpad generate`, that `opts.templateData` includes the full set of helpers and data, but when using `docpad render` then `opts.templateData` only includes document and documentModel.

Use this code in a plugin to illuminate:

``` javascript
MyPlugin.prototype.render = function (opts) {
  console.log(Object.keys(opts.templateData));
};
```

When this is run as `docpad run` or `docpad generate` then this will show the full suite of template helpers like `getFullURL()`, `include()`, etc.

When it is run as `docpad render pathToFile` then this only has `[document, documentModel]`

I would assume that this is a defect since I would expect that we should have access to the same templateData when rendering one page as we would when rendering all.

If this is not a defect, then how does one access the rest of the templateData helpers and data from a plugin render call?

Thanks.

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
