### ISSUE TITLE
Where to improve DocPad log messages?

### ISSUE THREAD

**Issue by Zearin** [docpad/docpad#622]
I’m interested in working on DocPad’s log messages.  But I’m not (yet) familiar with the codebase, so I wanted to ask if there was a good starting place.  (Basically, I’m trying to avoid manual changes if there is a centralized piece of code that can change more with less work.)

**Bonus points:** If you could describe the (conceptual) structure of DocPad’s logging in relation to its other components, that would be super helpful. 8)

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
