### ISSUE TITLE
Help: customize directories + rendering

### ISSUE THREAD

**Issue by Zearin** [docpad/docpad#625]
I’d like a _slightly_ different layout than DocPad’s default.  Rather than this:

```
- src/
    - documents/
        - styles/
        - scripts/
        - index.html.md
        - «etc.»
```

I’d like this:

```
- src/
    - styles/               # renders to out/styles
    - scripts/              # renders to out/scripts
    - documents/            # renders to out/
        - index.html.md
        - «etc.»
```

**But** I still want `css/` and `js/` to render as their own directories under `out/`—just as they used to.  

(In other words, I want content in `documents/` totally separate from code. :smile:)

---

How do I do that?

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
