### ISSUE TITLE
Rename `files/` ► `static/`

### ISSUE THREAD

**Issue by Zearin** [docpad/docpad#626]
The `files` directory isn’t really named in a meaningful way.  I mean, what do you call the rest of the stuff in a DocPad project?  (They’re files, too! :tongue:)

I recommend changing DocPad’s default name for this folder to `static/`.  It’s a little better at communicating that “stuff in this folder is copied as-is” to `out/`.

----

**But won’t that break existing DocPad projects?**

Well, I recommend using the old name `files` as a fallback.  DocPad could also issue a deprecation warning that `files` will stop being used altogether in the next major release.  

In the meantime, new DocPad projects would initialize using the newer `static` name.

(Same goes for config properties named to match `files`.  Basically, code that uses the term “files” should refer to *files in general*, rather than files that live in a folder that happens to be named `files`.)

**Comment by balupton** [comment]
This has been completed in the docs for a while. I believe the last piece for this is updating all skeletons, and updating the core code for the new defaults.

**Comment by balupton** [comment]
Considered done, as all things we control has done this.
