### ISSUE TITLE
Discussion: Pitching DocPad to enterprise

### ISSUE THREAD

**Issue by dwynne** [docpad/docpad#634]
We recently rebuilt http://red-badger.com using DocPad and had a fantastic experience doing so.  Red Badger is a software consultancy and we tend to work with quite large corporate organisations.  We want to convince them that should opt to head in the static site generator direction for new projects (where suitable) rather than plump for the "tried and tested" CMSs like Drupal.

The issue is that large corporates don't like risk.  And if they don't understand something or feel that they're doing something no-one else is doing, then they get worried and back away.

This puts us in a catch 22 situation.  We know they often don't need the complexity of a large CMS, but we also know that if we try and recommend something else (like DocPad) we face an uphill battle convincing them it's the right choice and that they should award us the work.

I suspect I am not the only person in this situation and as such would like to collectively build a case _for_ statically generated sites that we can all use when pitching for work.  What do we need to do that?

We need examples of large or significant sites that have chosen to go the CMS-less route.  Doesn't have to be DocPad - any static site generator will help.

**Some examples:**
- [Obama's campaign site](http://kylerush.net/blog/meet-the-obama-campaigns-250-million-fundraising-platform/)
- [Healthcare.gov](http://developmentseed.org/blog/new-healthcare-gov-is-open-and-cms-free/)

**What are not good examples?**
As much as I like our [site](http://red-badger.com) and many of the examples on [docpad.org](http://docpad.org/docs/showcase) - they aren't significant enough to convince a large corporate it's the way to go for them.  Nor are personal blogs or homepages.

Frankly I'm struggling to build a case, which is a real shame because I strongly believe that the simpler approach of DocPad is suitable for so many sites that instead choose a life of complexity and vendor lock-in.

If anyone can help provide some more high profile examples, then I hope we can provide a really useful resource for those us trying to convince customers to embrace CMS-less approaches.

Thanks,
David.

**Comment by balupton** [comment]
Closing due to age.
