### ISSUE TITLE
Discussion on Legal Documents: CLA and Sponsorship Contract

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#635]
Hey Everyone,

As the Bevry and DocPad communities are now starting to reach a pretty big volume, it's about time we do up a Contributors License Agreement, and as we are now starting to take on sponsors, it's time we do up a Sponsorship Contract as well.

Please let me know what you think of the following documents:
- [Contributors License Agreement](https://docs.google.com/document/d/1rs39tPoWqBTbJxPMWAhvU-IGlublq5HXmL5bXgKIGnA/edit)
- [Sponsorship Contract](https://docs.google.com/document/d/1Tsnx5aU0e4GZqPvkl-S2rucFYYbhZsVRNX9Zbwkfnzo/edit#)

One thing to note is that in those documents it mentions the Public Domain rather than a specific license (like our current MIT license). Going forward, with the community's okay (or no disagreement), I'll proceed to release all of the Bevry's works to the Public Domain as it is the most frictionless way to ensure that _everyone_ can act freely on the information they've received.

**Comment by konobi** [comment]
CLAs are a trap. Just look at how Oracle was able to take OpenSolaris back into a closed source by their use of a CLA. Never ever contribute to a project that requires a CLA.

Infact, even the TOS are useless since it can just be removed. And should be.

**Comment by napolitano** [comment]
Reading a while on the not very user friendly project page, i decided to give docpad a try. I installed it, i fired `docpad --offline init` on the CLI and then deleted it immediately. You may ask "Why?". 

The reason is simple: 
`Before we continue, have you read and agree to DocPad's Terms of Service (http://bevry.me/tos) and Privacy Policy (http://bevry.me/privacy)?`

#fail Sorry guys, your software can be made by elves and it might be the best node based static page generator ever - but this is a major show stopper for me.

From the privacy policy (highlighted by me):

> Bevry **may disclose personally identifiable information** under special circumstances, such as to comply with subpoenas or when your actions violate the Terms of Service.

From the TOS (highlighted by me):

> By using any services, websites, projects or products ("Service") of Bevry Pty Ltd ("Bevry"), you are agreeing to be bound by the following terms and conditions ("Terms of Service"). **If you are entering into this agreement on behalf of a company or other legal entity, you represent that you have the authority to bind such entity, its affiliates and all users who access our services through your account to these terms and conditions, in which case the terms "you" or "your" shall refer to such entity, its affiliates and users associated with it.** If you do not have such authority, or if you do not agree with these terms and conditions, you must not accept this agreement and may not use the services.
> 
> **Bevry reserves the right to update and change the Terms of Service from time to time without notice.** Any new features that augment or enhance the current Service, including the release of new tools and resources, shall be subject to the Terms of Service. Continued use of the Service after any such changes shall constitute your consent to such changes. You can review the most current version of the Terms of Service at any time at: http://bevry.me/tos
> 
> You understand that the technical processing and **transmission of the Service, including your Content, may be transfered unencrypted** and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.

Sorry guys, i don't give a "blanco-agreement". Never. That's one point. The second point is, that it is hardly to accept, that a open tool calls the mothership when it is used. It's not your business to know when, where and with how many computers i use the software.

I could remove the responsible parts from the code - but it's one of my key principles to not support this kind of behavior in any imaginable way. Sorry. :-/

**Comment by balupton** [comment]
> Bevry reserves the right to update and change the Terms of Service from time to time without notice. Any new features that augment or enhance the current Service, including the release of new tools and resources, shall be subject to the Terms of Service. Continued use of the Service after any such changes shall constitute your consent to such changes. You can review the most current version of the Terms of Service at any time at: http://bevry.me/tos

Can probably make this the same as the privacy policy:

> Bevry may periodically update this policy. We will notify you about significant changes in the way we treat personal information by sending a notice to the primary email address specified in your Bevry primary account holder account or by placing a prominent notice on our site.

**Comment by balupton** [comment]
As for the others, I'm not a lawyer, and we will need a lawyer to review. However those clauses are quite standard as [internet](https://duckduckgo.com/?q=%22If+you+are+entering+into+this+agreement+on+behalf+of+a+company+or+other%22&t=osx) [search](https://duckduckgo.com/?q=%22may+disclose+personally+identifiable+information+under+special+circumstances%2C+such+as+to+comply+with+subpoenas+or+when+your+actions+violate+the+Terms+of+Service.%22&t=osx) [shows](https://duckduckgo.com/?q=%22You+understand+that+the+technical+processing+and+transmission+of+the+Service%2C+including+your+Content%2C+may+be+transfered+unencrypted+%22&t=osx). I believe ours was generated from a service or template - and customised for our particular needs. So I'm hesitant to change any of those.

I'm not too fussed if people use DocPad nor not. I am fussed about protecting ourselves from lawsuits.

**Comment by napolitano** [comment]
IMHO you don't need an lawyer, you just should drop this stuff from the project. It's that easy. If you want to release it as open source, you don't need all this over-regulation stuff. For this the well known licenses were created. Just remove any "phone home"-feature and you can drop privacy policies and terms of service from the tools. Just my 2 cents ;)

**Comment by balupton** [comment]
Skeletons require phoning us so we can give the skeleton listing. We have a newsletter, a forum, and a slack channel. Enterprises to freelances use our software and services. We need to be protected.

**Comment by blitmap** [comment]
People don't seem to like submodules, but perhaps we could make the listing another repo that is routinely managed and committed as a submodule within docpad's repo.  I am indifferent, but that would mean no more phoning home :-)

**Comment by balupton** [comment]
> People don't seem to like submodules, but perhaps we could make the listing another repo that is routinely managed and committed as a submodule within docpad's repo. I am indifferent, but that would mean no more phoning home :-)

Originally that was the case, but it became too complicated to keep backwards compatibility when new requirements came out.

Also when the core starts abstracting out, we will need a [pluginclerk](https://github.com/bevry/pluginclerk) service to install and find the correct plugins that are supported in our environment (node version, other plugin versions, etc).

**Comment by balupton** [comment]
https://github.com/bevry/helper/blob/19f76403b81a13b598fc362dca8b40e561b9c173/esnext/lib/docpad.js is everything the helper currently does

**Comment by balupton** [comment]
How about this @napolitano - if they say no we don't accept the TOS and Privacy Policy, they just use it as a pirate instead, rather than having to fork the code.

**Comment by napolitano** [comment]
To be honest, i'm out of this discussion. I have chosen a different solution. Sorry for that.

**Comment by balupton** [comment]
No worries.

**Comment by balupton** [comment]
Closing due to age.
