### ISSUE TITLE
better errors for plugins

### ISSUE THREAD

**Issue by MehdiK** [docpad/docpad#640]
I just started writing a plugin and I think errors around plugin management could be improved. 

I am now getting 

```
warning: Skipped the unsupported plugin: heroku due to version-plugin
```

and have no idea what this means (help on this would be appreciated). Before this I set my version to `0.1` and I got this error:

```
/_mine/Code/mehdi-khalili.com/node_modules/docpad/node_modules/semver/semver.js:271
    throw new TypeError('Invalid Version: ' + version);
      ^
TypeError: Invalid Version: 0.1
```

While this one was not that hard to figure out, it could be an error logged to the console pointing out the requirements around version number instead of an unhandled exception.

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
