### ISSUE TITLE
Randomly stops watching files and doesn't regenerate

### ISSUE THREAD

**Issue by greduan** [docpad/docpad#641]
I've had a strange issue recently where for no reason, out of nowhere, DocPad just stops watching the files.

I have no idea what's causing it since it happens at random times but it seems to happen mostly when I work at night... No idea why.

Of course it can be fixed by restarting DocPad, i.e. running DocPad again.

**Comment by roblafeve** [comment]
I want to add that including `interval: 0` in `watchOptions` when using `watchFile` (due to the OS X watch issue) makes file regeneration happen instantaneously (the latency here was becoming a huge issue for me—so this has me very excited!). Hope this helps someone else.

Example configuration:

```js
watchOptions:
  preferredMethods: ['watchFile','watch']
  catchupDelay: 0
  interval: 0
regenerateDelay: 0
```
