### ISSUE TITLE
Being able to modify file's output folder/filename

### ISSUE THREAD

**Issue by greduan** [docpad/docpad#648]
Would be nice to be able to have something like this:

```
src/
  render/
    posts/
      - file1.html.md
      - file2.html.md
```

And the first file has:

```

---
title: whatever
layout: post
date: 2013-08-18
output: /2013/08/whatever

---
post content or whatever, seriously.
```

And the output would be:

```
out/
  posts/
    2013/
      08/
        - whatever.html
    - file2.html.md
```

See where I'm getting at? It would be kind of a pain to create the 2013/08 folders and imagine doing that for each month, maybe days if I wanted to. Not ideal.

Also this allows the user to order their files using stuff like `01-filename.html.md` etc.

So yeah, would be nice to see this implemented. :)

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
