### ISSUE TITLE
DocPad International Meetup

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#655]
Considering the size of the community these days, as well as what it will grow to hereafter, it is perhaps time for us to start considering a global retreat where the entire community could come together for a few days of socializing, and perhaps even a few days of intense hacking.

Keen to hear the +1s on this, as it is only feasible if we can get a lot lined up. Also post your location.

Perhaps February 2014?

**Comment by balupton** [comment]
Migrated here: http://discuss.bevry.me/t/proposal-bevry-docpad-conference/32/1

**Comment by SteveMcArthur** [comment]
I can't log on to the conference site - says that it is by invite only.

**Comment by balupton** [comment]
Try now

**Comment by SteveMcArthur** [comment]
OK - working now

**Comment by balupton** [comment]
URL now https://discuss.bevry.me/t/proposed-international-docpad-conference/31
