### ISSUE TITLE
setMeta and setMetaDefaults not working as expected

### ISSUE THREAD

**Issue by thesec** [docpad/docpad#662]
Trying to overwrite documents' meta info in docpad.coffee I tried

I. `setMetaDefaults` at first but it seems that `urls` gets not set?

II. ... switching to `setMeta` then `urls` does not get reset when already defined in YAML?

Is both the expected behaviour?

What I'd somehow expected is `setMetaDefaults` to set the defaults for any key passed in and `setMeta` to set any key to the value passed in, hence overwriting both default and a documents' property if defined in YAML.

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
