### ISSUE TITLE
Asynchronous Template Helpers

### ISSUE THREAD

**Issue by yazla** [docpad/docpad#667]
Hi, i didn't find a proper place to put this question, so please point me if i choose the wrong one.

The problem is that i didn't find a method to use the async functions in the template helpers. Is this possible at all? I just want to put there the  app logic which usually require an async db(Mongo) access.

Thanks.

**Comment by balupton** [comment]
See [ropo](https://github.com/bevry/ropo) for a way to do this. Otherwise, one could use a javascript and promise based templating engine.
