### ISSUE TITLE
Bug: Webserver + docpad-plugin-multiplelayouts

### ISSUE THREAD

**Issue by kristfal** [docpad/docpad#696]
Hello,

I'm running docpad 6.54.2 + eco, livereload, marked, multiplelayouts 2.0.1

I'm using multiplelayouts to generate two versions of the same document (one for web browsers with a header and footer and another one that will be displayed within a native iPad application without the header and footer).

/src/documents includes:

privacypolicy.html
subscriptionagreement.html

The documents have the following metadata:

title: "Privacy Policy"
layout: "default"
additionalLayouts: "native"
isPage: true

title: "Subscription Agreement"
layout: "default"
additionalLayouts: "native"
isPage: true

I'm running two layouts:

default.html.eco
native.html.eco

/out includes:

privacypolicy.html
privacypolicy-native.html

subscriptionagreement.html
subscriptionagreement-native.html

So far so good, everything is fine and the pages are generated correctly. Here comes the bug though:

Browsing to either localhost:8779/privacypolicy.html or localhost:8779/subscriptionagreement.html on the built in webserver of docpad actually displays the *-native.html version. 

I've cleared the browser cache, no fix. So I fired up another webserver and pointed it to the /out directory. With this server, everything was loading up correctly. Everything also worked fine when pushing it into production.

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad/issues/1081
