### ISSUE TITLE
Docpad.destroy not called during ctrl+c (windows)

### ISSUE THREAD

**Issue by pflannery** [docpad/docpad#698]
docpad destroy never gets called when using ctrl+c on windows. 

I'm not to sure where to fix this in docpad but I believe this may help http://stackoverflow.com/questions/10021373/what-is-the-windows-equivalent-of-process-onsigint-in-node-js#answer-14861513

Hopefully fixing this will fix issue #551

**Comment by balupton** [comment]
This will be ratified in v6.80.7 which will be out momentarily.

**Comment by balupton** [comment]
Took a bit longer than expected. But v6.80.7 is now out.
