### ISSUE TITLE
DocPad v6.55.4 — Changes to a jade include into layout does not re-render the layout's children

### ISSUE THREAD

**Issue by uhunkler** [docpad/docpad#724]
I start DocPad with "docpad run".

I have a layout.jade layout template and include for example a footer via "include includes/footer". The "footer.jade" is saved in the folder "src/layouts/includes/footer.jade". When I change the "footer.jade" file the DocPad re-render process is triggered but DocPad does not re-render the layout's children.

This issue is not new to DocPad v6.55.

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
