### ISSUE TITLE
Docpad not serving without a generate action

### ISSUE THREAD

**Issue by djskinner** [docpad/docpad#741]
Hi,

I'm trying to integrate docpad into my express application. I have this:

```
var docpadInstanceConfiguration = {
    // Give it our express application and http server
    serverExpress: app,
    serverHttp: server,
    // Tell it not to load the standard middlewares (as we handled that above)
    middlewareStandard: false
};

var docpadInstance = require('docpad').createInstance(docpadInstanceConfiguration, function(err){
    if (err)  return console.log(err.stack);
    console.log('docpad create instance OK');

    // Tell DocPad to perform a generation, extend our server with its routes, and watch for changes
    docpadInstance.action('generate server', function(err){
        if (err)  return console.log(err.stack);
        console.log('docpad server action OK');
    });
});
```

Which works fine. However, I don't want to have to do a generation every time the app starts - the generation will be part of the grunt build process.

If I first do a `docpad generate` and then run my express app without the generate action (i.e. `docpadInstance.action('server', ...)`) I would expect everything to work.

However, if the generate action is not there then docpad will not serve any pages - it just simply hangs indefinitely and may eventually come back with a "no data received" message.

Any ideas?

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad/issues/1081
