### ISSUE TITLE
docpad slow to notice changes in watched files

### ISSUE THREAD

**Issue by trooney** [docpad/docpad#749]
Docpad is slow to pick up changes to watched files. Previously a save almost immediately triggered a regeneration. Now it takes 3-9 seconds before Docpad notices the change and triggers a regeneration. 

This occurs on a fresh DocPad install with only 1 document. No plugins installed.

It began around 6.55. I thought it related to the new database cache. But I've rolled back to 6.52 and the lag still remains. Have tested on my MacBook and a iMac at work. Perhaps either a change with Node, or a OS X Patch?

Docpad is a great tool, but the lag makes styling sites frustrating. Have tried adding preferredMethods watchFile and watch to docpad.coffee, but this only increases the delay.

Attached the log, but the times listed below were from an earlier run. 

https://gist.github.com/trooney/8bf37b1677a8d23c6da2

docpad v6.59.6
node v0.10.24
npm 1.3.21
Macbook Pro (OS X 10.9.1, Core i7, SSD)

```
Change    Regenerating  Time
23:06:38  23:06:42      00:00:04
23:06:49  23:06:52      00:00:03
23:07:01  23:07:07      00:00:06
23:07:18  23:07:22      00:00:04
23:07:31  23:07:37      00:00:06
```

**Comment by Zearin** [comment]
Was getting the “regenerate on first change, then nothing” problem myself.  Found this issue.

For @trooney and anyone else interested in speeding up performance:

The “official” template engine is usually `docpad-plugin-eco`.  However, it has a fork named `docpad-plugin-ect`, which is focused on performance.  It uses the same syntax as ECO.

If you switch the plugins, remember to rename all your `*.eco` to `*.ect`. :)

Finally, [here are some benchmarks](http://ectjs.com/#benchmark) that compare the performance of ECT to ECO.  (**Note:** (Core) ECT includes some features beyond that of (core) ECO.  However, these aren’t available in `docpad-plugin-ect`.  They are mentioned in that link, so I just wanted to be clear.  This is a difference between the template engines; between `docpad-plugin-eco` and `docpad-plugin-ect`, there are no feature differences…only performance!)
