### ISSUE TITLE
Usage of id for meta data

### ISSUE THREAD

**Issue by oleersoy** [docpad/docpad#751]
Hi,

This is more of a developer question, so I'm asking here, but please let me know if I should move it to stackoverflow.

I created a link plugin (https://github.com/oleersoy/docpad-plugin-link) that uses a document's id to generate links to the target document.  However now when I run docpad I get the message:

`The document /home/ole/Projects/test/src/documents/test.html.md.eco tried to over-write its`id`attribute with its meta-data.
This will cause unexpected issues. We have ignored the`id`attribute changes to prevent further errors.`

Does that mean I need to change the `link` plugin to use something other than `id`?  In other words is `id` reserved?  The document `id` should be unique always, and I would prefer if docpad allowed it to be specified, but ensured that it is unique.

**Comment by balupton** [comment]
I believe backbone does offer IDs.
