### ISSUE TITLE
Warning: Rendering the extension "eco" to "md" on "index.html.md.eco" didn't do anything

### ISSUE THREAD

**Issue by oleersoy** [docpad/docpad#752]
I've created a project from the quickstart guide running docpad v6.59.6.  I'm only generating a single file - `documents/index.html.md.eco`, which I have made to contain minimal markdown, just to see that the conversion works OK, which it does.

However I get this message:

info: Generating...
warning: 
  Rendering the extension "eco" to "md" on "index.html.md.eco" didn't do anything.

Thoughts on why this is being displayed (I've looked at http://docpad.org/extension-not-rendering, but that does not seem to be relevant in this case)?

**Comment by danguilherme** [comment]
I know this is a really old thread, but I ended up with the same error, even with eco plugin installed...

```text
warning: A warning occured:

Error: Rendering the extension "eco" to "html" on "C:\path\to\project\src\render\index.html.eco" didn't do anything.
Explanation here: http://docpad.org/extension-not-rendering
```

And the explanation URL still seems to be irrelevant to the issue. It's weird that everything was working fine!

Writing this comment I realized that there wasn't any `eco` block in my `index.html.eco` file, so I added `<%- @site.title %>` and DocPad generated it just fine, with no error or warnings. It means it's really just a warning, but the URL did not help to troubleshoot it. The message `Rendering the extension "eco" to "html" on "..." didn't do anything.` would be better if shown alone, without the URL and especially the `Error: ` part.

```bash
node --version
# => v0.10.26
docpad -V
# => v6.78.1
```

**Comment by greduan** [comment]
Yeah I agree that's a warning and not an error.

**Comment by awendland** [comment]
Is it possible to suppress this warning/error?

**Comment by tomccabe** [comment]
This warning is *ridiculous*, doesn't provide any way to clear it and is followed by a stacktrace for each of my ~50 files, so anything that _might_ be useful in the cl output is blown away by this garbage. I spent a full day trying to figure out what was wrong only to find out it's nothing.

The "extension-not-rendering" link is a 404 as well.

Absurd.

**Comment by balupton** [comment]
@tomccabe if you have javavascript enabled, http://docpad.org/extension-not-rendering should take you here.

**Comment by balupton** [comment]
> Is it possible to suppress this warning/error?

Remove the unnecessary extension.
