### ISSUE TITLE
6.59.6 Issues

### ISSUE THREAD

**Issue by keithrobinson** [docpad/docpad#753]
Not sure if this is the right spot, but figured I'll leave this here just in case someone is having similar issues.

I've got a fairly simple site running and things have been great up until today when I updated docpad.

Here is the repo: https://github.com/the-mason-jar/www-the-mason-jar

The new version wouldn't render anything. The templates were all busted and when I generated there was no /out directory. I tried to revert everything and I set the my docpad version back to the previous, but now all of my directory pages are messed up. Essentially the code I was using to generate link lists isn't working. I spent a few hours digging through and can't figure out what's wrong. Here is what that code that's not rendering looks like:

```
  <ul id="directory">
      <% for page in @getCollection("allCocktails").toJSON(): %>
          <li class="<%= if page.id is @document.id then 'active' else 'inactive' %>">
              <a href="<%= page.url %>">
                  <%= page.title %>
              </a>
          </li>
      <% end %>
  </ul>
```

Again, this all worked until I ran the update. I thought reverting the version would fix things, but it didn't. So now I'm kind of stuck on the previous version with nothing working. Is there a way I could do a completely clean install to that version? Any ideas why the latest version doesn't generate the /out directory?

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
