### ISSUE TITLE
DocPad's future, your thoughts!

### ISSUE THREAD

**Issue by greduan** [docpad/docpad#756]
@balupton Recently expressed that he feels that not everybody is clear on what DocPad is and what it's future will be. Everybody's pointing a different direction.

So to clear that up, everybody that finds this and is familiar with what DocPad is please answer with the following info:

- What is DocPad? What was it developed for? To the extent of your knowledge of course.
- What do you use DocPad for?
- What do you expect or what do you think DocPad will be in the future? Like the idea that you have it will turn into.

I expect a lot of different answers, if possible don't look more into docPad before answering since that would ruin it a bit.

That is all. Thanks! :)

**Comment by balupton** [comment]
Closing for age. Discussions and progress on this has moved elsewhere.

**Comment by Zearin** [comment]
> Closing for age. Discussions and progress on this has moved elsewhere.

Makes sense, but…

Could you please add links to “elsewhere”?

**Comment by balupton** [comment]
Good point. Mostly discussions have happened in a variety of places over the last two years. The summary locations are https://bevry.me/patreon which has the roadmap and reasoning and https://discuss.bevry.me which has discussions.
