### ISSUE TITLE
How to get docpad to do less

### ISSUE THREAD

**Issue by djskinner** [docpad/docpad#758]
Hi everyone,

I'm building an express app using docpad for the static site generation side of things whilst also using it to render dynamic documents using the [API](http://docpad.org/docs/api). I find this architecture very powerful in that docpad takes care of the bulk of the website extremely well with all the goodies you would expect (layouts, collections, partials, 404s, plugins, etc.). I can then simply drop in additional functionality such as contact forms and online booking processes by writing them in express and calling the docpad API functions to serve my pages dynamically.

The important thing to me is that _this is an express app_, not a docpad app. I want to use grunt in to produce a build of the app and ultimately run it using `node app.js`.

In practice this means that I would like to generate a static site using the [CLI](http://docpad.org/docs/cli) (as a grunt task) and then simply attach docpad to my express app to provide the routing (i.e. for cleanurls and 404's etc..). If I need to use docpad to render a file for me elsewhere in my express app I can then simply use `serveDocument`.

I seem to be doing a bit battling against docpad when using this approach of _grunt and express first with docpad second_. It seems to me that docpad is trying to do too much. This was actually great at the start because the watching and built in server functionality allowed me to rapidly get a static site up and running. However, now that docpad is taking a back seat in a larger app it seems to be getting in the way a little. 

The main issue I am facing at the moment is that docpad requires me to generate the entire site every time the app starts up. This not only takes a long time and seems to me unnecessary if the static site had already been built, but also overwrites output which was generated by the grunt build process. This may include further processing, which is then lost.  All I need is for docpad to provide the routes for an already generated site without having to generate it again first.

Is anyone else coming up against these difficulties and if so how have you dealt with it?

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad/milestone/16

See https://discuss.bevry.me/t/deprecating-in-memory-docpad-importers-exporters/87?u=balupton for a related discussion.
