### ISSUE TITLE
Copying src/files to out is slow

### ISSUE THREAD

**Issue by ghost** [docpad/docpad#762]
Why not serve src/files in environment development?

Static files have no dynamic attributes, I'm making an argument for serving src/files directly from the docpad server — only when in environment development. Instead, Docpad currently relies on the static files to be generated and placed into the directory _out_. This is very slow when editing JavaScript files, css, and tpl files — so slow it has encouraged me to suggest this as a modification . Static assets are the issue here, nothing else.

**Comment by jlukic** [comment]
Just checking in here after a long absence. Back last year I added `standalone: false` to all documents and they are now speedy as can be. 

I am however still getting slow copies after updating static files in `src/files/`, typically 30-45 seconds. Is there a workaround for this case?

**Comment by dimitarkolev** [comment]
Try using docpad-plugin-copy

**Comment by jlukic** [comment]
I realized even after swapping to docpad coffee, that I would get the same issues since all files were being processed as `standalone: false` 

Finally solved this by adding back to `files/` and using
```coffeescript
events:
    extendCollections: (opts) ->
        @docpad.getCollection('files').on('add', (document) ->
            document.setMetaDefaults(standalone:true))    
```
