### ISSUE TITLE
Dynamic pages after 6.57.3

### ISSUE THREAD

**Issue by peterhaldbaek** [docpad/docpad#767]
There seems to be a problem with dynamic pages since 6.57.3. When I type an incorrect URL and receive a 404 the (dynamic) error page sometimes does not show (sometimes it does) but any requests to static pages after that are shown without layout.

If I make the 404 page static everything behaves nicely. The latest version of DocPad where it works for me is 6.57.3.

You can recreate this by running the twitter-bootstrap-jade.docpad plugin and hit a non-existing URL.

Node 0.10.23.

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad/issues/1081

**Comment by michaelsbradleyjr** [comment]
It's been so long that when I saw the email notif from GitHub just now, I was like... what's docpad? Will have to give it another look. 😄
