### ISSUE TITLE
Prevent plugin conflicts

### ISSUE THREAD

**Issue by misterdai** [docpad/docpad#771]
There appears to be an issue with the plugin architecture whereby plugins can overwrite each others template methods.  For example, "docpad-plugin-paged" provides ["getPageUrl"](https://github.com/docpad/docpad-plugin-paged/blob/414bd36c09ba72c9e4ae315e071b3caf102ef436/src/paged.plugin.coffee#L45) and "docpad-plugin-services" provides ["getPageUrl"](https://github.com/docpad/docpad-plugin-services/blob/b3b33f54e26b9993ba34480a570e7c149a066ea1/src/services.plugin.coffee#L18).  When using both of these plugins, the one "getPageUrl" will overwrite the other, [breaking the expected behaviour](https://github.com/docpad/docpad-plugin-paged/issues/10) or causing errors.

It'd be nice to have a way to prevent plugins from doing this.  Otherwise, the more plugins people develop and use, the more chance we'll have of other conflicts.

I'll leave others to come up with suggestions as to how ;-)

**Comment by StormPooper** [comment]
Yeah, I think throwing a conflict error would be a nice middle-ground while a more compatible approach is decided upon. In the meantime, I think we'll have to go ahead and rename the conflict given in this example, as it's stopping people from using the paged plugin and the service plugin together.

**Comment by balupton** [comment]
This should be solved in username by having plugins write to their own namespace. For instance `templateData.feedr.blah()`
