### ISSUE TITLE
Support for single extenstions

### ISSUE THREAD

**Issue by dimitarkolev** [docpad/docpad#772]
It will be nice if docpad can support single extension documents. This can be a config option. For example its almost 100% that less will output css and md will output html., coffee will output js, etc. It will be great if we can put somewhere inside the config that all md files will be treated as .html.md and all .less files as .css.less.
The extension problems is clearly visible when you add external library to docpad. Right now you have to rename files by hand.

**Comment by musicist288** [comment]
In a recent attempt to setup docpad as the framework behind a multi-page (purely client-side) web application this seemed to be a blocker short of forking docpad and maintaining the fork.  

If you're still interested in this issue, there seems to be a statement that prevents documents with a single extension from being processed through rendering extensions: https://github.com/docpad/docpad/blob/master/src/lib/models/document.coffee#L420  It would seem that the first step is to remove this line, though I don't know much about the docpad render loop to know what consequences that has.

In my specific case, I wanted to render typescript files passing them through the typescript compiler, but it's essential that they only have the single `.ts` extension for various reasons related to the way typescript resolves modules.

**Comment by balupton** [comment]
This was added with v6.3.0

https://github.com/docpad/docpad/blob/master/HISTORY.md#v630-2012-july-18
