### ISSUE TITLE
How to manipulate the meta block for a document?

### ISSUE THREAD

**Issue by RobLoach** [docpad/docpad#777]
I'm attempting to manipulate the meta tags of each document, but it looks like getBlock('meta') is not what it seems...

http://github.com/RobLoach/docpad-plugin-opengraph/blob/master/src/lib/opengraph.plugin.coffee#L40

Anyone know how one should change the meta tags for the document? Or is this just not handled in DocPad yet?

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
