### ISSUE TITLE
Http request for file that does not exist crashes docpad

### ISSUE THREAD

**Issue by madshobye** [docpad/docpad#778]
I have been testing and testing. I crashes consistently after a file has been requested that is not avaliable.

info: Generated 6/66 files in 3.562 seconds
notice: 404 Not Found: /favicon.ico
info: Generating...
info: Dumped 66 files to the database cache
info: Generated 6/66 files in 3.622 seconds
Error: Bad Request
    at SendStream.error (/Users/xxx/Desktop/xx/xxx/node_modules/docpad/node_modules/express/node_modules/send/lib/send.js:145:16)

After this the template does not render. You can find a screenshot here:

https://drive.google.com/file/d/0B_ctupPLDOrUVm1nU21rMXlwSmM/edit?usp=sharing

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad/issues/1081
