### ISSUE TITLE
dynamic collection configuration

### ISSUE THREAD

**Issue by waynedpj** [docpad/docpad#782]
ahoy,

  i recently discovered DocPad and its neat static/dynamic integration .. excited to check it out .. thanks for DocPad first off!

  i was looking into collections and how DocPad defines them in the config file explicitly.  what i am wondering is if DocPad can configure collections dynamically from a directory hierarchy?  for example, with the following `documents` directory structure:

```
documents/
├── index.html
└── releases
    ├── A
    │   ├── index.html
    │   └── tracks
    │       ├── 01
    │       │   └── index.html
    │       ├── 02
    │       │   └── index.html
    │       └── 03
    │           └── index.html
    ├── B
    │   ├── index.html
    │   └── tracks
    │       ├── 01
    │       │   └── index.html
    │       ├── 02
    │       │   └── index.html
    │       ├── 03
    │       │   └── index.html
    │       └── 04
    │           └── index.html
    └── index.html
```

and _without specifying each collection explicitly in the config file_, DocPad would
- have a `releases` collection with items `A` and `B`
- each release `A` & `B`would have a child collection `tracks` with the respective items (i.e. `A` has elements `01`,`02`,`03` and `B` has elements `01`,`02`,`03`,`04`)

in essence the collection configuration _is_ the directory structure with the generic form of `collection/items/sub-collection/items/sub-collection/items ....` allowing collections to be created by simply placing directories and files in a certain place.

i assume this can be done with some code in the config file, similar to https://gist.github.com/balupton/4166806 .  however, i am unsure how to build the child collections recursively.

i would appreciate any solutions/advice/etc. for how to do this the DocPad way.

thanks in advance.

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
