### ISSUE TITLE
Add performance asserts to the tests

### ISSUE THREAD

**Issue by dimitarkolev** [docpad/docpad#786]
I am using docpad almost from the start and during the last several years i see it getting slower and slower. I believe that there should be some time span asserts in the tests that will guarantee that newer versions dont become slower.
I am not sure what is the proper way to implement this but i feel that its something very important. 
I just checked an old website that used to generate for less than 2s and now it takes 25s. There should be some limits for the performance that should be considered as breaking changes.
As an example if the generation when watching for changes on css(less) files happens it should take less than 1 sec to finish. Without such constraints docpad is moving from its initial goal to stay out of the way. And it is making me reinvent the whole workflow so i can use docpad only i am certain that i am not going to change the files.

**Comment by balupton** [comment]
Addressing this with #936
