### ISSUE TITLE
generateAfter event called regardless of generate errors

### ISSUE THREAD

**Issue by stongo** [docpad/docpad#800]
I'm not sure if this behavior is expected, but if I have an error in an .eco template, it throws the exception during generation, but then proceeds to call the generateAfter event and crashes my site completely or else triggers plugins that hook in to generateAfter, which then have broken files to work with.

Is there a way for a plugin to check for errors in the generateAfter event?

Wondering if event hooks should all follow this signature:

```
generateAfter: (err, opts, next) ->
```

This way events can pass errors down the chain

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
