### ISSUE TITLE
`ignored: true` documents are showing up in collections

### ISSUE THREAD

**Issue by robhawkes** [docpad/docpad#807]
Not sure exactly what version triggered this behaviour, but at least in 6.63, `ignore: true` has stopped ignoring files – they generate into the out directory.

This has already resulted in near-embarrassment as draft articles have been published without my knowledge or permission.

Any idea why this is happening?

**Comment by balupton** [comment]
Possible dupe of https://github.com/docpad/docpad/issues/392
