### ISSUE TITLE
"Unable to parse"

### ISSUE THREAD

**Issue by RobLoach** [docpad/docpad#808]
When the YAML fails to parse, it reports `Unable to parse` without much information into where the parse error was. It would be great if it was a bit more descriptive. Maybe stick the parsing in a try/catch and then report a bit more information as to what document faiiled to parse?

I've gotten around it by using `docpad generate -d > .log` and then reading through where the error is, but it would be great if it reported it appropriately.

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
