### ISSUE TITLE
RST support

### ISSUE THREAD

**Issue by MarcosBL** [docpad/docpad#81]
I've trying nodepad to build my personal documentation site. Most of my existing documents are in RST format, because it allows you to autogenerate TOC's and other magic that markdown doesn't

Would it be hard to add RST support to docpad , as you already did with markdown and so, even if we need some kind of middleware ?

It would be really helpful.

Thanks in advance, and congrats on such a wonderful product !

MarcosBL

**Comment by balupton** [comment]
Userland.
