### ISSUE TITLE
docpad render takes significantly longer than manual

### ISSUE THREAD

**Issue by Naatan** [docpad/docpad#812]
I was trying to figure out how to make my project render faster when I decided to try docpad render of a scss file against manually invoking scss. Here are the results:

[nathan@nathan-ubuntu]❯ time scss src/documents/styles/style.css.scss > /dev/null         komodo-website/git/master !
scss src/documents/styles/style.css.scss > /dev/null  0.58s user 0.01s system 99% cpu 0.595 total
[nathan@nathan-ubuntu]❯ time docpad render src/documents/styles/style.css.scss > /dev/null
docpad render src/documents/styles/style.css.scss > /dev/null  2.10s user 0.06s system 68% cpu 3.141 total

Fwiw, the file in question is: https://github.com/Komodo/komodo-website/blob/master/src/documents/styles/style.css.scss

I realize docpad won't ever be as fast as running scss (or whatever parser) directly, but I wasn't expecting the difference to be quite so big.

Unfortunately --debug doesnt seem to work with 'docpad render' and its too late for me to dig much further. But I wanted to report my findings.

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
