### ISSUE TITLE
meta data format causes parse error

### ISSUE THREAD

**Issue by oopschen** [docpad/docpad#822]
Yesterday, i change my blog from Jeklly to docpad, it is really awesome. I find some problems in the meta data parsing process.

```

---
layout: post

---
```

the above meta data works perfectly, but fails when i write data as below:

```

---
layout:post

---
```

It fails every time i occasionlly write meta data like that. The problem might be Docpad must have me to write a **space** between the **:** and my first letter in the meta data value.

It might be great to fix it.

PS:
os: gentoo
encoding: utf-8
docpad version: v6.64.0
node version: v0.10.21
npm version: 1.3.11

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80.
