### ISSUE TITLE
Updated files not updated when viewing in browser

### ISSUE THREAD

**Issue by Naatan** [docpad/docpad#830]
I'm seeing this problem increasingly more often where a file gets updated, the log shows its re-rendered but the browser is not showing the update (I've cleared the browser cache & refreshed manually). The only thing I can do is restart docpad. I've also tried manually editing a file in the "out" folder, which also doesn't appear to get picked up.

I'm on the latest version of Docpad (saw a commit related to caching but this did not seem to fix the issue I am seeing).

This was never an issue up until about 2 or 3 weeks ago.

Any ideas?

**Comment by balupton** [comment]
This will be fixed in v6.81, as that will just serve `out` directly. So what is written is what you get.

Details over at https://github.com/docpad/docpad/issues/1081
