### ISSUE TITLE
Integrating Docpad and Express

### ISSUE THREAD

**Issue by jsloyer** [docpad/docpad#835]
I am trying to integrate docpad with express and running into a couple issues.  I have the integration working where I let docpad generate the content on server startup but I am trying to modify it so I can generate the content before hand (build an npm module and import it in my app).

Calling docpadInstance.action("server", callback); doesn't work, my express server just hangs on the docpad routes.  It seems docpad doesn't see that there is content already generated in the out folder.

Anyone have any thoughts on this?

**Comment by Zearin** [comment]
@mikeumus @balupton :+1:

**Comment by balupton** [comment]
> Basically I want to know if there is a way to run docpad with pre-generated content and not call the generate action and attach docpad to an existing express server to serve content.

Not yet possible. DocPad requires the meta data (that it only gets from parsing the source files) to serve with its express extensions.

Maybe in a future major revision of DocPad, however now ETA for that. If there was an ETA it would be 2016 or higher.

Your best option in that scenario is to not use the DocPad server at all, serve the output folder using a static middleware that you setup, and then just get docpad to generate things via the generate action making sure the environment is set to `static`

**Comment by balupton** [comment]
DocPad went that way with `docpad-compile` and its desire for dynamic abilities, however it turned out to be a terrible business decision.

As of DocPad v6.81, such use cases will be removed.

See https://github.com/docpad/docpad/issues/1081 for details.
