### ISSUE TITLE
Improve DocPad code documentation

### ISSUE THREAD

**Issue by greduan** [docpad/docpad#837]
I plan on going through all of the DocPad code to see what it does and how, so I can understand it to an extent and start hacking on it.

While doing this, I plan on going through it and adding real code documentation using something like JSDoc or something similar.

Are there any objections to this @balupton @mikeumus? Anything else I should use instead?

Anyone else have suggestions on what to use instead of JSDoc or anyone against this idea?

**Comment by balupton** [comment]
Ecosystem over the years has incorporated such documentation upgrades.

See [boundation](https://github.com/bevry/boundation) for how we automate it.

For DocPad API docs, see #933
