### ISSUE TITLE
Watch has stopped watching directory

### ISSUE THREAD

**Issue by ezmiller** [docpad/docpad#846]
I've been working on a DocPad project for a while now, and the watch method has worked well up until now. Now it has stopped watching an entire directory containing js script files:

 > src/documents/scripts/

When I make changes to these files docpad does not notice. When I make a change, stop the docpad run process, and then restart it, docpad changes the file to which I have made a chance back to an earlier version. Anyone have any ideas what might be going on here?

**Comment by gursesl** [comment]
Similar issue here.

Site files reside under:
- layouts
- render
  - pages

Regardless of the type of file (HTML, JADE, MD), the watcher works for the first change only and then never picks up the changes until docpad is restarted.

**Comment by balupton** [comment]
Does this still happen?

If so, can you forward the error to: http://github.com/bevry/watchr

Thanks!

**Comment by gursesl** [comment]
Issue resolved on OSX by adding this to docpad.coffee:

# Watch options
    watchOptions:
        catchupDelay: 0
        preferredMethods: ['watchFile', 'watch']
