### ISSUE TITLE
git-ftp

### ISSUE THREAD

**Issue by ungki** [docpad/docpad#848]
I have installed [git-ftp](https://github.com/git-ftp/git-ftp) in output folder. Unfortunately when i use `docpad update`, not working. 

```
error: Somthing went wrong with the action
error: An error occured:
Error: EPERM, unlink `c:\example\out\.git\objects\01\b50cd....`
```

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this.
