### ISSUE TITLE
redirect secondary url to primary url doesn't work

### ISSUE THREAD

**Issue by shawnzhu** [docpad/docpad#850]
* Your DocPad version `v6.68.1`
* Your Node.js version `v0.10.28`
* Your npm version `1.4.13`
* Your operating system `OS X, x86_64, 10.9`

## What happened
I'm using document secondary urls feature and the redirect doesn't work.

The documented [secondary url](http://docpad.org/docs/meta-data#-url-) feature seems broken:

> `url`
>  When a user accesses a document via a secondary URL, the user will be redirected to the primary URL automatically.

For example, you have a docpad document `/src/documents/secondary-url.html.md`:

    ---
    urls:
     - '/my-secondary-urls1'
     - '/my-secondary-urls2'
    ---
    # primary url should be `secondary-url.html`

## Expectation
it should respond status code 301 with redirect location `/secondary-url.html` when visiting `http://localhost:9778/my-secondary-urls1` while actually docpad responds status code 200.
It seems the feature itself exists based on docpad code: https://github.com/bevry/docpad/blob/572fad61f699e20d0f0516c3e362d4cd7e20270d/src/lib/docpad.coffee#L4619

So I believe this is an issue. Here's [my original question](http://stackoverflow.com/questions/24197428/does-docpad-secondary-url-redirect-feature-work).

**Comment by garthk** [comment]
@shawnzhu, could you send that upstream as a pull request?

**Comment by balupton** [comment]
Fixed in v6.71.0 February 19, 2015
