### ISSUE TITLE
Plugin for Liquid templates support

### ISSUE THREAD

**Issue by paulradzkov** [docpad/docpad#852]
Required Liquid template support for DocPad. Found https://github.com/sirlantis/liquid-node, possibly it can be integrated as a plugin.

P.S. Or maybe anyone will suggest a manual how to convert Jekyll site into DocPad.

**Comment by cameronjroe** [comment]
I personally like liquid A LOT more than coffeescript. 

Is there a reason there needs to be separate plugins though, when we have something like [consolidate](https://github.com/tj/consolidate.js)? Seems confusing to have all these template engine plugins, when ideally we could just literally configure them in the docpad configuration with one plugin and let the plugin handle that complexity.

**Comment by greduan** [comment]
@cameronjroe FYI, there is a consolidate plugin: http://github.com/robloach/docpad-plugin-consolidate

**Comment by cameronjroe** [comment]
@greduan Indeed, I'm using that. Not sure if it supports liquid though.

**Comment by greduan** [comment]
The answer is no. You could add support for it perhaps. But Liquid is much more complex than what consolidate is looking for, IIRc.

**Comment by balupton** [comment]
Closing as this is a userland issue.
