### ISSUE TITLE
Some bug in the ToS

### ISSUE THREAD

**Issue by greduan** [docpad/docpad#854]
Hey @balupton, it seems there's something going on in the ToS section of DocPad's code.

https://github.com/bevry/docpad/issues/851
https://github.com/bevry/docpad/issues/853
https://github.com/bevry/docpad/issues/857

The bug is that when the user runs `docpad run` and is asked to accept the ToS, when the user says `Y` DocPad just stops executing.

At this point if the user runs `docpad run` again the same thing happens.

Any idea what could be happening? Seems like some logic went awry at some point in the code...

**Comment by austinbutler** [comment]
Using --offline only presented me with 1 skeleton, so it wasn't a great workaround. Instead I used this, which allowed me to install npm packages globablly without root: https://github.com/glenpike/npm-g_nosudo

**Comment by 7wonders** [comment]
Also getting this problem but then --offline presents a new error:

```
Fantastic. We like informed people!
error: An error occured: 
ReferenceError: userConfigString is not defined
  at DocPad.updateUserConfig (/project/node_modules/docpad/out/lib/docpad.js:1555:40)
  at /project/node_modules/docpad/out/lib/interfaces/console.js:271:22
  at DocPad.track (/project/node_modules/docpad/out/lib/docpad.js:2167:11)
  at /project/node_modules/docpad/out/lib/interfaces/console.js:265:25
  at /project/node_modules/docpad/node_modules/promptly/index.js:80:9
  at Interface.onLine (/project/node_modules/docpad/node_modules/promptly/node_modules/read/lib/read.js:111:5)
  at Interface.emit (events.js:107:17)
  at Interface._onLine (readline.js:214:10)
  at Interface._line (readline.js:553:8)
  at Interface._ttyWrite (readline.js:830:14)
  at ReadStream.onkeypress (readline.js:109:10)
  at ReadStream.emit (events.js:110:17)
  at readline.js:1175:14
  at Array.forEach (native)
  at emitKeys (readline.js:993:10)
  at ReadStream.onData (readline.js:910:14)
  at ReadStream.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at ReadStream.Readable.push (_stream_readable.js:126:10)
  at TTY.onread (net.js:529:20)
```

**Comment by shearer12345** [comment]
I get the same error as @7wonders when using the the --offline option (node version v0.12.0, built from source)

**Comment by balupton** [comment]
Should be fixed in the upcoming version.

**Comment by shearer12345** [comment]
Great. Thanks. :-)

-- Shearer

**Comment by norpol** [comment]
In my opinion, tt's hilarious that you need an `--offline` function for using this tool...

**Comment by balupton** [comment]
@norpol fetching skeletons, fetching plugin versions, feedr plugin, cachr plugin, etc all use online abilities. I find very cool that we have a flag so that DocPad works gracefully offline, rather than all those abilities falling over. Hilarious wouldn't be the word I use for such maturity of a project.

**Comment by norpol** [comment]
I don't (and didn't) want to bother you, but what bothers me is when I see something like that:
```info: Welcome to DocPad v6.73.2 (global installation: /home/tom/.npm-packages/lib/node_modules/docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: 
info: Environment: development
Before we continue, have you read and agree to DocPad's Terms of Service (http://bevry.me/tos) and Privacy Policy (http://bevry.me/privacy)? [Y/n] ```
But yeah, that's a personal opinion. All other tools  on my machine I'm using are not asking me to agree their tos and privacy policy. They've just got simply a licence. :c
