### ISSUE TITLE
Prismic.io plugin

### ISSUE THREAD

**Issue by hivearts** [docpad/docpad#855]
Hello guys,

I am looking for a docpad integration with prismic.io

Prismic.io is beautiful content repository management service.

I have found prismic.io node.js starter kit:
https://github.com/prismicio/javascript-nodejs-starter

But i am not skilled to make it working with docpad.

Can anybody please make a plugin?

**Comment by balupton** [comment]
Moved to: https://discuss.bevry.me/t/docpad-plugin-prismic-io/42
