### ISSUE TITLE
Error encountered while following the tutorial

### ISSUE THREAD

**Issue by LD99** [docpad/docpad#856]
Hi, I encountered error while I was following the beginner's tutorial.

My DocPad version: v6.69.0
My Node.js version: v0.10.29
npm version: 1.418

I am using Mac OSX 10.9.4, on my Macbook Air 2013 version.

What happened was that I just followed the tutorial. Initially I couldn't proceed because of the TOS bug (using the tip from https://github.com/bevry/docpad/issues/488 resolved it).

Then I followed the tutorial, and I got as far as "Installing the template engine". In fact it threw an error when I changed the "about.html" and the "index.html" as per tutorial instruction (changing it to take advantage of the layout wrapper). When I refreshed the page it didn't give me a blank page like the tutorial said, but instead the page remain unchanged.

Then I quitted docpad, and installed eco as instructed. I tried to run docpad again, but this time it won't run.

I hope this is the correct way to file a bug report. I am new to Github.

Thanks.

The bug log is as follows:

debug: Emitting the event: consoleSetup
    → [2014-06-30 23:49:52.547] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: consoleSetup
    → [2014-06-30 23:49:52.563] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Loading user's configuration: /Users/LD99/.docpad.cson
    → [2014-06-30 23:49:52.601] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1420] [Task.<anonymous>]
debug: Loading configuration path: /Users/LD99/.docpad.cson
    → [2014-06-30 23:49:52.605] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1580] [load]
debug: Loading user's configuration: /Users/LD99/.docpad.cson
    → [2014-06-30 23:49:52.633] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1428] [unknown]
debug: Loading website package.json configuration: /Users/LD99/Documents/Dropbox/Docpad/package.json
    → [2014-06-30 23:49:52.638] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1468] [Task.<anonymous>]
debug: Loading configuration path: /Users/LD99/Documents/Dropbox/Docpad/package.json
    → [2014-06-30 23:49:52.642] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1580] [load]
debug: Loaded website package.json configuration: /Users/LD99/Documents/Dropbox/Docpad/package.json
    → [2014-06-30 23:49:52.647] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1477] [unknown]
debug: Loading .env file configuration: /Users/LD99/Documents/Dropbox/Docpad/.env
    → [2014-06-30 23:49:52.650] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1487] [Task.<anonymous>]
debug: Loading website configuration
    → [2014-06-30 23:49:52.654] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1511] [Task.<anonymous>]
debug: Loading configuration path: /Users/LD99/Documents/Dropbox/Docpad/docpad.coffee
    → [2014-06-30 23:49:52.664] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1580] [load]
debug: Loaded website configuration
    → [2014-06-30 23:49:52.672] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1526] [unknown]
debug: Plugins loading for: /Users/LD99/Documents/Dropbox/Docpad/node_modules
    → [2014-06-30 23:49:52.694] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2569] [DocPad.loadPluginsIn]
debug: Loading plugin: .bin
    → [2014-06-30 23:49:52.702] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2525] [DocPad.loadPlugin]
debug: Loading plugin: docpad
    → [2014-06-30 23:49:52.705] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2525] [DocPad.loadPlugin]
debug: Loading plugin: eco
    → [2014-06-30 23:49:52.708] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2525] [DocPad.loadPlugin]
debug: Skipped the unsupported plugin: docpad due to type
    → [2014-06-30 23:49:52.712] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2539] [unknown]
debug: Loaded plugin: eco
    → [2014-06-30 23:49:52.719] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2555] [unknown]
debug: Plugins loaded for: /Users/LD99/Documents/Dropbox/Docpad/node_modules
    → [2014-06-30 23:49:52.722] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2592] [scandir.next]
debug: Emitting the event: extendCollections
    → [2014-06-30 23:49:52.729] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: extendCollections
    → [2014-06-30 23:49:52.745] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Emitting the event: extendTemplateData
    → [2014-06-30 23:49:52.750] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: extendTemplateData
    → [2014-06-30 23:49:52.754] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Emitting the event: docpadLoaded
    → [2014-06-30 23:49:52.760] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: docpadLoaded
    → [2014-06-30 23:49:52.765] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
info: Welcome to DocPad v6.69.0 (local installation: /Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad)
    → [2014-06-30 23:49:52.770] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1237] [DocPad.ready]
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
    → [2014-06-30 23:49:52.773] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1238] [DocPad.ready]
info: Contribute: http://docpad.org/docs/contribute
    → [2014-06-30 23:49:52.775] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1239] [DocPad.ready]
info: Plugins: eco v2.0.3
    → [2014-06-30 23:49:52.777] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1240] [DocPad.ready]
info: Environment: development
    → [2014-06-30 23:49:52.779] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1241] [DocPad.ready]
debug: Emitting the event: welcome
    → [2014-06-30 23:49:52.784] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: welcome
    → [2014-06-30 23:49:52.790] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Emitting the event: docpadReady
    → [2014-06-30 23:49:52.797] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: docpadReady
    → [2014-06-30 23:49:52.801] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Emitting the event: serverBefore
    → [2014-06-30 23:49:52.857] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: serverBefore
    → [2014-06-30 23:49:52.868] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Emitting the event: serverExtend
    → [2014-06-30 23:49:52.881] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: serverExtend
    → [2014-06-30 23:49:52.884] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Starting server on hostname null port 9778 directory /Users/LD99/Documents/Dropbox/Docpad/out
    → [2014-06-30 23:49:52.890] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:4374] [Task.<anonymous>]
info: DocPad listening to http://0.0.0.0:9778/ on directory /Users/LD99/Documents/Dropbox/Docpad/out
    → [2014-06-30 23:49:52.894] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:4381] [Server.<anonymous>]
debug: Emitting the event: serverAfter
    → [2014-06-30 23:49:52.898] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: serverAfter
    → [2014-06-30 23:49:52.905] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
info: Generating...
    → [2014-06-30 23:49:52.911] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:3077] [DocPad.generate]
debug: Emitting the event: notify
    → [2014-06-30 23:49:52.914] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: notify
    → [2014-06-30 23:49:52.935] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Generate options: { cache: false,
  initial: true,
  reset: true,
  populate: true,
  reload: true,
  partial: false,
  renderPasses: 1 }
    → [2014-06-30 23:49:52.946] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:3140] [Task.<anonymous>]
debug: Emitting the event: populateCollectionsBefore
    → [2014-06-30 23:49:52.956] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: populateCollectionsBefore
    → [2014-06-30 23:49:52.961] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Parsing directory: /Users/LD99/Documents/Dropbox/Docpad/src/documents
    → [2014-06-30 23:49:53.003] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2401] [unknown]
error: Something went wrong with the action
    → [2014-06-30 23:49:53.045] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/interfaces/console.js:107] [ConsoleInterface.destroyWithError]
error: An error occured: 
Error: Failed to parse the meta data using the yaml parser on /Users/LD99/Documents/Dropbox/Docpad/src/documents/about.html 
The error follows: Unable to parse.
    at /Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/models/document.js:116:21
    at FileModel.parse (/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/models/file.js:622:7)
    at DocumentModel.parse (/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/models/document.js:76:37)
    at Task.<anonymous> (/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/models/file.js:561:21)
    at ambi (/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
    at fire (/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:375:25)
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at Task.fire (/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:386:25)
    at /Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:402:26
    at process._tickDomainCallback (node.js:463:13)
    → [2014-06-30 23:49:53.062] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2010] [DocPad.error]
error: To report the above error, follow the guide at: http://docpad.org/bug-report
    → [2014-06-30 23:49:53.070] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:2011] [DocPad.error]
debug: Emitting the event: notify
    → [2014-06-30 23:49:53.078] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1160] [DocPad.emitSerial]
debug: Emitted the event: notify
    → [2014-06-30 23:49:53.105] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
debug: Updated mtime for these models due to addition of a similar one []
    → [2014-06-30 23:49:53.123] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1084] [FilesCollection.<anonymous>]
debug: Adding document: /Users/LD99/Documents/Dropbox/Docpad/src/documents/index.html
    → [2014-06-30 23:49:53.142] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1651] [setCollections.documents]
debug: Adding generate file: /Users/LD99/Documents/Dropbox/Docpad/src/documents/index.html
    → [2014-06-30 23:49:53.153] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1678] [setCollections.generate]
debug: Adding has layout file: /Users/LD99/Documents/Dropbox/Docpad/src/documents/index.html
    → [2014-06-30 23:49:53.170] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1694] [setCollections.hasLayout]
debug: Adding html file: /Users/LD99/Documents/Dropbox/Docpad/src/documents/index.html
    → [2014-06-30 23:49:53.177] [/Users/LD99/Documents/Dropbox/Docpad/node_modules/docpad/out/lib/docpad.js:1700] [setCollections.html]

**Comment by balupton** [comment]
For what it's worth, https://github.com/docpad/docpad/issues/626 is the resolution for this
