### ISSUE TITLE
Train new maintainers for DocPad

### ISSUE THREAD

**Issue by Greduan** [docpad/docpad#858]
@balupton 
How does the idea of getting a maintainer for DocPad sound? I mean someone, besides you, that can spend time on DocPad fixing bugs, enhancing it etc.

Right now I feel like I could probably manage with a little bit of training on the codebase, but I am not making a lot of websites right now so I can't really be in communication with DocPad as a whole.

I say we offer the position anyone that is willing to take it up, give them access to the DocPad repo and make a backup of the repo. Releases would still have to be distributed by you, in order to make sure there is no security issue of any kind.

What do you think?

**Comment by balupton** [comment]
Moved to: https://discuss.bevry.me/t/what-are-the-current-hurdles-with-helping-out/43
