### ISSUE TITLE
Can't iterate through object properties

### ISSUE THREAD

**Issue by ranisalt** [docpad/docpad#866]
I'm creating a conference website based on [braziljs/conf-boilerplate](https://github.com/braziljs/conf-boilerplate), which uses Docpad, but I have to tweak it a little. I had to use an associative array on `docpad.js` and, as far as I'm concerned, the only way to mimic it with Javascript is to use an object with property names as the keys for the array.

I tried to create an object like this:
```js
speakers: {
    "Speaker 1": {
        photo: "themes/img/speaker.jpg",
        bio: "?",
    },
    "Speaker 2": {
        photo: "themes/img/speaker.jpg",
        bio: "?",
    }
}
```
At any part of the partials, if I output this variable with `<%= JSON.stringify(@speakers) %>`, it prints the correct object data. But if I try to iterate over properties, like this:
```js
<% for data, name in @speakers: %>
    <%= name %><br><%= data.bio %>
<% end %>
```
It just doesn't work properly, it prints nothing, as if `@speakers` was empty. I thought maybe the parameters are inverted (`data` with `name`), but changing them does not work too.

This for...in is the default syntax for JS iterating over object properties, does Docpad use any other syntax for it or doesn't support iterating over properties?

**Comment by balupton** [comment]
If you're using coffeescript templating like eco, then it will be:

```
<% for own data, name of @speakers: %>
    <%= name %><br><%= data.bio %>
<% end %>
```
