### ISSUE TITLE
Append script tags to end of page (like Rails' content_for)

### ISSUE THREAD

**Issue by gurdotan** [docpad/docpad#874]
Hi,

I'm looking for a way to create a yielding block at the end of an HTML page (using eco templates) that will accumulate script tags from all templates, includes and partials involved in the rendering of a single page and will put them all in one section at the bottom of the page.

In simpler words, I'm trying to achieve what Rails does:

``` erb
# In the main HTML layout
<%= yield :javascripts %>

# In other parts of the page \ its partials
<% content_for :javascripts do %>
  <script ....>
<% end %>
```

(See: http://guides.rubyonrails.org/layouts_and_rendering.html#understanding-yield)

The goal is to have a main layout that renders all pages and has some common script tags (jQuery, Bootstrap etc.) and that each page can append its own script tags to the end of these scripts.

Any ideas? Thanks

**Comment by balupton** [comment]
You can add the content to a meta property on your document. Then output it using your layout.
