### ISSUE TITLE
MIME types

### ISSUE THREAD

**Issue by ezmiller** [docpad/docpad#876]
I am trying to use the video element to display a video. However, it is not working on the iPad. I discovered [here](http://diveintohtml5.info/video.html#video-mime-types) that this can be related to the server not providing the correct MIME type. I've labeled the mime type in my html and I'm wondering if the docpad server is somehow not specifying the MIME type correctly. I couldn't find much in the documentation about how MIME types are handled. Does anyone know how this is done. In Apache, one would add lines like this to .htaccess:

```
AddType audio/ogg .oga
AddType video/ogg .ogv
AddType application/ogg .ogg
```

How is this done in node/docpad? Perhaps this should be documented?

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad/issues/1081
