### ISSUE TITLE
Waiting on The Following files on renderFiles

### ISSUE THREAD

**Issue by flaviomicheletti** [docpad/docpad#885]
### What I did

I started to create a website with DocPad and insert some pages
I ran the command `docpad run --silent` (normal user, not a root)
### What happened

The DocPad entered a infite loop and showed the following message:

```
Waiting on The Following files on renderFiles
```
### What I expected

It generates is usually the site.
- npm --version 2.0.0-beta
- node --version v0.10.29
- docpad --version v6.69.0 (local installation: /home/...bla bla bla
- Plugins: cleanurls, eco, livereload, marked, pygments
- [ docpad-debug.log](https://gist.github.com/flaviomicheletti/cea658c1b4ce20335e21)

View the question on the [stackoverflow](http://stackoverflow.com/questions/25764189/waiting-on-the-following-files-on-renderfiles).

My "repo" for testing [https://github.com/devfuria/www.devfuria.com.br/tree/docpad](https://github.com/devfuria/www.devfuria.com.br/tree/docpad)

**Comment by balupton** [comment]
Issues are no longer present in v6.80.
