### ISSUE TITLE
Problem when pulling docpad repo down to a new computer

### ISSUE THREAD

**Issue by ezmiller** [docpad/docpad#889]
When I pull a docpad repository that I've been developing on another computer down to new computer that has docapd already installed globally, I keep getting this error:

> module.js:340
>     throw err;
>           ^
> Error: Cannot find module '../out/bin/docpad'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/ethan/Sites/berlincrisis/node_modules/docpad/bin/docpad:2:1)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
> An error occured within the child DocPad instance: exited with a non-zero status code

I usually end up having to resolve it by rerunning install scripts, but it is very nervewracking and i'm not sure what is going on here. Can someone explain? How can I avoid this?

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80.
