### ISSUE TITLE
Installing bourbon+neat without a plugin?

### ISSUE THREAD

**Issue by neo-art** [docpad/docpad#892]
Hi,

I would like to use Docpad for some of my project but I couldn't install Bootstrap and Zurb Foundation skeletons:

``` ruby
16. Zurb Foundation: Performing renderFiles (pass 1) at 2/5 40% ===================------------------------------
An error occured within the child DocPad instance: exited with a non-zero status code
```

or for Bootstrap:

``` ruby
No compatible version found: eco@'>=1.1.0 <1.2.0'
```

so I was wondering if it is possible to install **Bourbon+Neat** without a plugin (i.e. nodesass and sass plugins)?

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80.
