### ISSUE TITLE
Docpad run does not start

### ISSUE THREAD

**Issue by patrixd** [docpad/docpad#896]
Some time ago I noticed that sometimes Docpad run did not start. I tried and tried and it worked again.
But while I continue working with Docpad this problem increase. Docpad does not start, I try and try and it does not work with no errors.
The last end before crash is: DocPad listening to http://0.0.0.0:9778 on directory C:\....\out

What can I do? This problem is really anoying and cause me to lost LOT of time. And sometimes I can't continue working in my docpad site.

I am using windows 8.1 Pro
Thanks a lot in advance

**Comment by balupton** [comment]
Try run with the `prompts: false` or `progress: false` in your docpad configuration. When DocPad is using progress bars stdin is paused so we won't detect the `ctrl+c`.

**Comment by patrixd** [comment]
Thank you so much Benjamin Lupton, I think prompts: false really helped. =)

*ATT Patri  **｡◕‿‿◕｡ ♪ *


2015-03-18 15:43 GMT+01:00 Benjamin Lupton <notifications@github.com>:
