### ISSUE TITLE
Better Plugin Maintenance Workflow

### ISSUE THREAD

**Issue by dimitarkolev** [docpad/docpad#898]
What is the best way to improve docpad plugins. I noticed that its very hard to make someone responsible for a plugin accept a pull request or recomendation for a fix. There are several plugins that need to be fixed in order for DocPad to be production ready. For example we changed raw plugin which is a must for any project as well as thumbnails and paged, but its very hard for those fixes to find a way to npm.
We can create new plugins but they will be 90% the same as the ones we changed and this will make it hard for the user to choose from. Please advice.
On the other side we are using them in websites with thousands of pages and the performance benefit is enormous compared to the original version which is hardly usable. From my experience looking at the issues they are solving many of the performance problems reported here.

**Comment by balupton** [comment]
Jumping on this a bit late, but there's the implemented and ideal workflow:

1. A popular plugin gets moved to the `docpad` github org

2. A `docpad` github org adds the `docpad extras team` to maintain that repo

3. The plugin author does a `npm owner add balupton` inside the plugin directory

4. I then automate a `npm owner add [all the other docpad core team]`

5. Any of the extras team can then merge in fixes, they then alert a core team member, and the core team member publishes it

We have a bit of work to do to streamline this. During my absence it's probably slowed down a bit. I have 6 months before I become a hermit, so I'll see what I can do to streamline this.

**Comment by balupton** [comment]
Added https://github.com/docpad/documentation/blob/master/extend/plugin-write.html.md#maintenance
