### ISSUE TITLE
Error: getaddrinfo ESRCH

### ISSUE THREAD

**Issue by xiwc** [docpad/docpad#899]
# Environment: VirtualBox - CentOS6.5

when exec `docpad run -d`

Debug message:

> debug: Emitted the event: serverExtend
>     â [2014-12-01 15:31:29.144] [/home/semantic/Semantic-UI-Docs/node_modules/docpad/out/lib/docpad.js:1165] [TaskGroup.<anonymous>]
> debug: Starting server on hostname centos port 9778 directory /home/semantic/Semantic-UI-Docs/docs
>     â [2014-12-01 15:31:29.152] [/home/semantic/Semantic-UI-Docs/node_modules/docpad/out/lib/docpad.js:4376] [Task.<anonymous>]
> error: Something went wrong with the action
>     â [2014-12-01 15:31:47.712] [/home/semantic/Semantic-UI-Docs/node_modules/docpad/out/lib/interfaces/console.js:107] [ConsoleInterface.destroyWithError]
> error: An error occured:
> **Error: getaddrinfo ESRCH**
>     at errnoException (dns.js:37:11)
>     at onanswer (dns.js:124:16)
>     â [2014-12-01 15:31:47.753] [/home/semantic/Semantic-UI-Docs/node_modules/docpad/out/lib/docpad.js:2010] [DocPad.error]
> error: To report the above error, follow the guide at: http://docpad.org/bug-report
>     â [2014-12-01 15:31:47.763] [/home/semantic/Semantic-UI-Docs/node_modules/docpad/out/lib/docpad.js:2011] [DocPad.error]
> debug: Emitting the event: notify

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
