### ISSUE TITLE
Jekyll features on website comparison table needs updating

### ISSUE THREAD

**Issue by lietu** [docpad/docpad#904]
At [https://docpad.org/docs/intro](https://docpad.org/docs/intro) you have quite a bit of misinformation, mainly about Jekyll.

Jekyll HAS a plugin system: [http://jekyllrb.com/docs/plugins/](http://jekyllrb.com/docs/plugins/)

Jekyll has bundled support for 2 markup languages, Markdown and Textile, and more can be implemented via plugins. [http://jekyllrb.com/docs/plugins/#converters](http://jekyllrb.com/docs/plugins/#converters)

Jekyll has pre-processors, even the default project you get with `jekyll new project-name` uses SCSS. [https://github.com/jekyll/jekyll/tree/master/lib/site_template/_sass](https://github.com/jekyll/jekyll/tree/master/lib/site_template/_sass)

Both Jekyll and pretty much any and all CMS systems support partials [http://jekyllrb.com/docs/templates/#includes](http://jekyllrb.com/docs/templates/#includes)

For most intents and purposes (for CMS systems) Jekyll basically has database support as well, via it's [data files](http://jekyllrb.com/docs/datafiles/) system.

If you use GitHub for hosting your Jekyll website there's also a WYSIWYG editor, [Prose](http://prose.io/#about)

These mistakes make your project look worse than it might actually be when people who actually know these things see you spread lies and misinformation. It is rather easy to assume that if you're willing to lie about other projects, you're lying about your features as well.

**Comment by balupton** [comment]
> These mistakes make your project look worse than it might actually be when people who actually know these things see you spread lies and misinformation. It is rather easy to assume that if you're willing to lie about other projects, you're lying about your features as well.

Wow... that was pretty hostile.

DocPad was started in March 2011, due to the frustration of Jekyll not having those things. No deceit was intended, that content is simply like that because it hasn't been updated, most likely because we don't pay attention to other SSGs as we are too busy focusing on our own.

A PR would have been a lot nicer than your accusations. Happy to accept a PR.
