### ISSUE TITLE
problematic behavior when running via API

### ISSUE THREAD

**Issue by ghost** [docpad/docpad#908]
I have have the following app.js file:

```
var docpadInstanceConfiguration = {
};

require('docpad').createInstance(docpadInstanceConfiguration, function(err, docpadInstance) {
    if (err) return console.log(err.stack);

    docpadInstance.action('generate server', function(err, result) {
        if (err) return console.log(err.stack);
        console.log('docpad server is running');
        console.dir(result);
    });

});
```

When I run this, it generates the site as expected and starts the server. Yay!
However, I want to generate the site in a separate step and use this script to start the server.
If I remove `generate` from above, the server appears to start but it does not process any requests. :-(

I can reproduce this behavior on my local machine as well as when I deploy (Azure website).

I'm running Windows 8.1, DocPad 6.69.2, Node 0.10.32.

Any thoughts on what would cause this behavior?

**Comment by bennage** [comment]
It says ghost, but it's really me. :-)

**Comment by bennage** [comment]
FYI, I'm willing to make a fix and send a PR. I'm just hoping for some hints before I spend time doing the investigative work.

**Comment by Greduan** [comment]
Yeah I don't have the expertise required, right now Ben is the most knowledgeable of that stuff I think. /cc @balupton

**Comment by balupton** [comment]
API has changed for this over the years. It likely now works correctly.
