### ISSUE TITLE
Docpad does not run

### ISSUE THREAD

**Issue by varya** [docpad/docpad#909]
Because of this bug https://github.com/bevry/istextorbinary/issues/3 is is impossible to run docpad now

**Comment by mikeumus** [comment]
https://github.com/bevry/istextorbinary/issues/3 is patched now. :fire: :fire_engine:

**Comment by varya** [comment]
Thanks!

**Comment by mikeumus** [comment]
You're welcome. Thank you for reporting it. :smile:
