### ISSUE TITLE
Metadata error with Slim

### ISSUE THREAD

**Issue by stoplion** [docpad/docpad#912]
Can you use Metadata with Slim? (using the docpad-plugin-slim)
If I remove the metadata, the errors are gone.
// index.html.slim
```
---
title: "test"
layout: "default"
---

h1 Hello
```

// layout/default.html.slim
```
html
  head
    title = @document.title | My Website

  body
    h1 = @document.title
    = @content
```

```
error: An error occured: 
Error: SyntaxError: (__TEMPLATE__):5: syntax error, unexpected $undefined, expecting ')'
; _buf << ("</title>\n  </head>\n  <body>\n    <h1>".freeze); 
                     ^
(__TEMPLATE__):7: unknown regexp option - h
unmatched close parenthesis: /head>\n  <body>\n    <h1>".freeze); 
; _buf << (::Temple::Utils.escape_html((::Temple::Utils.indent_dynamic((document.title), true, "\n      ", _temple_html_pretty1)))); 
; _buf << ("\n    </
(__TEMPLATE__):7: syntax error, unexpected tINTEGER, expecting ')'
; _buf << ("\n    </h1>".freeze); _buf << (::Temple...
                      ^
(__TEMPLATE__):7: syntax error, unexpected $undefined, expecting ')'
...ent_dynamic((content), true, "\n    ", _temple_html_pretty1)...
...                               ^
(__TEMPLATE__):8: syntax error, unexpected $undefined, expecting ')'
; _buf << ("\n  </body>\n</html>".freeze); _buf = _buf.join
             ^
(__TEMPLATE__):8: unknown regexp options - htl
(__TEMPLATE__):8: unterminated string meets end of file
(__TEMPLATE__):8: syntax error, unexpected end-of-input, expecting ')'
end;end;end;end
               ^
```

**Comment by Greduan** [comment]
AFAIK the metadata is removed from the content given to the template or markdown language, so I'm not sure what could be causing this error. :/

**Comment by stoplion** [comment]
[Here is the repo](https://github.com/stoplion/back-journal). If you remove the Yaml front matter the build errors go away.

**Comment by Greduan** [comment]
@balupton Got any ideas?

**Comment by balupton** [comment]
It's an issue with the plugin, file a report at https://github.com/patocallaghan/docpad-plugin-slim/blob/master/src/slim.plugin.coffee about it.

Seems that the plugin is not using our render events, and instead is doing its own thing.

**Comment by stoplion** [comment]
Ok thanks

**Comment by patocallaghan** [comment]
@balupton I'd like to resolve this issue in the slim plugin but just enquiring about your *the plugin is not using our render events* observation.

I'm currently using the `render` event ([seen here](https://github.com/patocallaghan/docpad-plugin-slim/blob/master/src/slim.plugin.coffee#L60)) when transforming the content. Is there something else I should be doing as looking at other plugins and the docs this seemed to be the correct way of doing it.

Any pointers are appreciated, thanks.
