### ISSUE TITLE
Dropping Node 0.8 Support

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#913]
Now that only a few people use Node 0.8, and now that Node 0.12 and IO.js are both out. We will drop support for Node 0.8.

We'd also highly encourage everyone to move to IO.js (best), or Node 0.12 (better), than using Node 0.10 as well - as the new ones are way faster and way better.

**Comment by balupton** [comment]
We will need to update our node install instructions to reflect this. This will require waiting for heroku to offer node 0.12 or iojs support.

**Comment by zenorocha** [comment]
Heroku already added support for io.js: https://devcenter.heroku.com/changelog-items/595

But it seems it's going away: https://medium.com/@iojs/io-js-and-a-node-js-foundation-4e14699fb7be

**Comment by zenorocha** [comment]
I updated node to v0.12 and it doesn't work with DocPad's latest stable version:

```
error: undefined '/Users/zeno/Dropbox/.docpad.cson'
error: null
error: null
TypeError: undefined is not a function
  at Object.exports.eval (/.../docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:133:47)
  at CSON.parseSync (/.../docpad/node_modules/cson/out/lib/cson.js:105:34)
  at ambi (/.../docpad/node_modules/ambi/out/lib/ambi.js:57:27)
  at [object Object]._onTimeout (/.../docpad/node_modules/cson/out/lib/cson.js:89:18)
  at Timer.listOnTimeout (timers.js:110:15)
error: null
info: null
```

**Comment by balupton** [comment]
Yeah, we gotta breaking release. Will be out this week sometime.

**Comment by pflannery** [comment]
@balupton I did do some updates -> https://github.com/pflannery/docpad/compare/node-0-12-update earlier which updates to CSON 2.0.0 and Coffee-Script 1.9.0 but I ran in to an issue where the environments weren't merging properly. 
It was failing on an action test because ```config.environments.__proto__ === Object.prototype``` was returning false...

**Comment by balupton** [comment]
Leave it with me, I already have begun work on this.

**Comment by pflannery** [comment]
ok thanks :+1:

**Comment by balupton** [comment]
0.12 and iojs support is in v6.70

**Comment by pflannery** [comment]
:+1:

**Comment by zenorocha** [comment]
:+1: glad to see you working on this @balupton ;D

**Comment by alexwoehr** [comment]
I am finding some situations in the docs where 0.10 is recommended. Based on initial comment in this thread, I am preparing a pull request to update these places.

**Comment by alexwoehr** [comment]
Oops, sorry to post on a closed thread. I am creating a new one and assigning myself.
