### ISSUE TITLE
docpad fails to generate website after local update from v6.53.4 to v6.69.2 with npm install

### ISSUE THREAD

**Issue by andreyvolokitin** [docpad/docpad#914]
I have docpad-powered website running on Ubuntu 13.04 (GNU/Linux 2.6.32-042stab094.7 x86_64). Earlier I had docpad v6.53.4 locally and globally. Then I accidently updated local docpad to v6.69.2 by changing package.json file with the new one containing new versions of docpad and some other packages and then running ```npm install``` (maybe it is even not appropriate way to update...). It happened because I mistakenly done ```docpad update; docpad upgrade;``` on my local machine and then just pushed changes to the server with the new package.json, server then run ```npm install``` automatically as a part of deploy process.

After this `docpad generate --env static` stopped working. Nothing was generating and it throwed this: http://pastebin.com/XaRQwEBh. Then I thought that generation stopped working because I did not update global docpad also. So I did `docpad upgrade` first, and then `sudo docpad upgrade` (did not mean to do `sudo`, it just happened). Now I have v6.69.2 globally and locally, but `docpad generate --env static` still not working properly. 

What I tried so far: reinstalled global and local docpad, updated node and npm, updated grunt-cli. Tried to downgrade back to v6.53.4 to see if it will be working again, but failed to ```npm install docpad@6.53.4``` due to [this](https://github.com/js2coffee/js2coffee/issues/326).

Info about current versions: http://pastebin.com/5ixJZ7Zz 
Output of ```docpad generate --env static -d```: http://pastebin.com/TavvGyKY - so it basically starts parsing ```/home/andrey/www/volokitin.me/web/src/files``` and then exits with ```An error occured within the child DocPad instance: exited with a non-zero status code``` message. But in server logs I found that this message happened many times before during previous deployments and nevertheless I did not experienced any problems before now. So I even did not know if this message actually related to this issue...

On my local machine (OS X 10.9.5) I have no problems.

What could be causing this? Maybe the reason is that I did ```npm install``` of the newer local docpad version instead of ```docpad update```/```docpad upgrade```? How can I debug it further?

**Comment by balupton** [comment]
Could be related to the current issue I'm working on. Will see.

**Comment by balupton** [comment]
@andreyvolokitin if you could try again with the latest v6.71.0 and let me know how it goes, as the issue that could be causing it #926 has now been fixed.

**Comment by andreyvolokitin** [comment]
@balupton, done upgrading and updating: http://pastebin.com/uZTmwyMU, then tried to generate: http://pastebin.com/V4djzqjc. But now it just fails a lot faster...

**Comment by andreyvolokitin** [comment]
Updated to 6.73.5. ```docpad generate --env -static -d``` is now executing much longer, it starts parsing ```/home/andrey/www/volokitin.me/web/src/files```, and full log is about 3mb, but it ends with the same ```An error occured within the child DocPad instance: exited with a non-zero status code``` error. Some logs from the end of 3mb log file: http://pastebin.com/98CSxeRk

**Comment by andreyvolokitin** [comment]
I guess my most promising option is to just reinstall server OS and all stuff from scratch.

**Comment by balupton** [comment]
@andreyvolokitin would you be able to give me access to the website repo that you are using? I'd like to see if I can reproduce on my local machine, and then I could debug further.

Shutdowns like that are generally when a crash occurs but is uncaught, this shouldn't happen in the DocPad core, but perhaps a plugin or dependency isn't behaving correctly.

**Comment by andreyvolokitin** [comment]
@balupton, here is repo: https://github.com/andreyvolokitin/volokitin-me. But the problem is that it works fine on my local machine. The problem exist only on the server, to which I can also give access.

**Comment by balupton** [comment]
I've done some work with different server compatibilities in the recent releases. Can you try the latest release and let me know if it is still a problem?

**Comment by andreyvolokitin** [comment]
Nope, still not generating. Now it exits without any message and throws error about ```could not determine the mac address``` at the beginning (docpad also throws this error on ```docpad clean``` but it do ```clean``` just fine): http://pastebin.com/wJDm8pwF. Some debugging logs prior silent quit: http://pastebin.com/nf7sk7vF

**Comment by balupton** [comment]
It must be a callback that never gets called... I'll see what I can do about adding some debugging for such situations. Perhaps doing a check like: on process exit, output the names of all running tasks in taskgroup
