### ISSUE TITLE
Switch from CoffeeScript to LiveScript

### ISSUE THREAD

**Issue by Greduan** [docpad/docpad#916]
I believe it is a better idea to use LiveScript. The syntax is extremely similar, making it very simple to [convert from one to the other](http://livescript.net/#coffee-to-ls), most of the stuff being search and replace.

And I find it's mostly a good idea because of some of the ambiguities that CS has in its syntax. For example the assignment operator (`=`), you have to be _very_ wary of what variable you are actually defining with CS, because of all the scope stuff.

I dunno, just mentioning it, it's probably better for people to do their individual research. BTW LiveScript != TypeScript.

**Comment by balupton** [comment]
We already get critised for using CS, which is the most popular JS pre-processor by a very long shot. Niching it up even more wouldn't make sense.

**Comment by pflannery** [comment]
imo I think if any switch is made it should be to ES6

**Comment by balupton** [comment]
@pflannery agreed. If we migrate to the chainyjs ecosystem that will happen, however chainy helps for async waterfall situations, but not event situations - will think about that solution over the next 6 months.

**Comment by pflannery** [comment]
@balupton nice one.

I watched a recent [todo app tutorial for Angular 2](https://www.youtube.com/watch?v=uD6Okha_Yj0&feature=youtu.be) and they were ranting how good [zone.js](https://github.com/angular/zone.js) and how it takes care of telling them a changes occurred. Might be the answer to events with chainy, I will have to get my head around it

**Comment by pflannery** [comment]
@balupton just an update to my findings so far with ZoneJS, it seems that it wraps native methods like setTimeout etc.. and also wraps all the DOM events, this way it can figure out when they are called and when they finish within a Zone instance. This helps it build stack traces so you can find out who called who and follow it back to the source which is very useful in an event driven system like the DOM. 

At first I thought it seemed like a task engine but really its more of a container generator that currently only works with the browser. If Zones also supported node etc.. then it could be an awesome library to use along side chainy.
