### ISSUE TITLE
Update test deps to go inside test site when npm 3 comes out

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#919]
http://blog.npmjs.org/post/110924823920

> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.

**Comment by jlukic** [comment]
@balupton Have you decided on a strategy for handling peer Deps in Npm3? It looks like a disaster..

**Comment by balupton** [comment]
This has been resolved by the ecosystem with [pluginclerk](https://github.com/bevry/pluginclerk) for plugin fetching, and [boundation](https://github.com/bevry/boundation) for plugin generation
