### ISSUE TITLE
Metadata not updated when property is deleted

### ISSUE THREAD

**Issue by dimitarkolev** [docpad/docpad#929]
I noticed a strange behavior when having a property in the document metadata and delete it. It is not deleted from the metadata until the next regeneration.
This is not a major issue but may lead to unexpected behavior.

**Comment by balupton** [comment]
More details at https://github.com/docpad/docpad/issues/980

**Comment by balupton** [comment]
Closing as dupe of #588

**Comment by balupton** [comment]
Closing as dupe of #521

**Comment by balupton** [comment]
Closing as dupe of #517
