### ISSUE TITLE
Docpad API documentation

### ISSUE THREAD

**Issue by SteveMcArthur** [docpad/docpad#933]
I've been working on a Docpad API browser off and on. The original idea is not wholly restricted to Docpad. But I thought I might run it by the community. You can see it at: http://docpad-api.herokuapp.com . Not the finished deal by a long shot. Its mostly generated from the source code. I'm just really wondering if others feel that this might be of use. Two things I wanted was to see all the properties available to Docpad's objects in the one place and have any properties I view be 'sticky' so I didn't have to look them up again in the same session. I've also found it helpful to see what's going on in the source for a particular property to understand what it is doing.

**Comment by Greduan** [comment]
Dude that's awesome! I've wanted to do something like this for very long but I'm too lazy. :P

**Comment by Zearin** [comment]
Ah!  Wonderful!  I have been wanting something like this for ages!

**Comment by Zearin** [comment]
@SteveMcArthur Can you explain what the icons mean?  I tried to look for differences between the “gear”, “A”, and “nodes” icons, but I can’t seem to figure it out…

**Comment by mikeumus** [comment]
Hey @SteveMcArthur, this is pretty cool. Is it open-source/can we use it? We're about to launch an new look for the landing page and a discourse forum shortly as well and this could be perfect to have on DocPad.org as well. Good work man! :smile::+1:

**Comment by balupton** [comment]
Looks good! We've been using a project called biscotto for bevry/TaskGroup with good success. Perhaps some beneficial overlap?

**Comment by SteveMcArthur** [comment]
@Zearin yeah - I need some sort of legend to explain the icons. They're supposed to indicate type. The blue forks are methods, red cogs properties (where the type is not obvious), purple A is a string, the '1-9' numeric and the yellow flash is an event.

@mikeumus Yep - the idea was really to let you guys use it if it was of benefit. Will upload it to github shortly and let you know

@balupton had a quick look at some coffeescript source processors before, but the docpad source doesn't really follow any source doc conventions and I was looking for something that would produce output independent (ie json) of the actual final documentation presentation.

**Comment by SteveMcArthur** [comment]
I've uploaded the website to: [https://github.com/SteveMcArthur/docpad-api-documentation](https://github.com/SteveMcArthur/docpad-api-documentation). Will upload the generating code shortly.

**Comment by SteveMcArthur** [comment]
I would like to mark some properties as "private" so that they can be initially hidden in the tree and also give users an indication that the properties are not designed to be used within an application. Properties accessed by a getter should probably be private, but also some are obviously only for internal use (initialConfig). I can do this myself with some sort of list used by the generator or it could be marked in the source by a comment.

**Comment by balupton** [comment]
Okay cool. I really like the tomdoc syntax that biscotto uses, so happy to add tomdoc annotations to updated DocPad code. Perhaps tomdoc is what we can use in your parser as well? Will certainly help with adoption and reusability of your tool :-) Happy to move away from biscotto, as it isn't that well maintained.

**Comment by SteveMcArthur** [comment]
@balupton I'm going to have a closer look at biscotto. I think I would much prefer using someones more established code rather than re-inventing the wheel. I think adopting any sort of commenting system is better than none. Will get back to you.

**Comment by pflannery** [comment]
@SteveMcArthur yeah docpad definitely needs a developer api documentation and a nice little browser like your example. I do the same thing for a lot of my more recent projects like [this example here](http://pflannery.github.io/queryifyjs/). I use yuidoc to generate the json data.

Instead of biscotto or tomdoc it might be worth considering transforming CS comments to JS then using jsdoc or yuidoc to generate the documentation json for consumption.

CS comments like (using jsdoc):
```coffee
###*
# Solves equations of the form a * x = b
# @example
# // returns 2
# globalNS.method1(5, 10);
# @example
# // returns 3
# globalNS.method(5, 15);
# @returns {Number} Returns the value of x for the equation.
###
```
would transform to 
```js
/**
 * Solves equations of the form a * x = b
 * @example
 * // returns 2
 * globalNS.method1(5, 10);
 * @example
 * // returns 3
 * globalNS.method(5, 15);
 * @returns {Number} Returns the value of x for the equation.
 */
```

**Comment by mikeumus** [comment]
I'm a fan of yuidoc.

**Comment by SteveMcArthur** [comment]
@pflannery I like the look of your example. It makes sense to use something more established like jsdoc or yuidoc. Can I pinch your code?

**Comment by pflannery** [comment]
the theme code is here - https://github.com/pflannery/yuidoc-theme-dyno, do what you want it's MIT.

**Comment by balupton** [comment]
@SteveMcArthur we're trying to document the es6 branch of taskgroup, but not having much luck. Nothing passes tomdoc and es6, and nothing seems to parse es6 and jsdoc either.

I'm thinking perhaps we could use your work to solve this.

**Comment by SteveMcArthur** [comment]
@balupton not sure if this is what you're after, but I've uploaded to: https://github.com/SteveMcArthur/api-generator

It's mainly about looping through the source files and counting indentations and applying regex to each line.

**Comment by SteveMcArthur** [comment]
I'm planning to do some more work on the documentation generator by combining what's generated from the source code with actual objects generated in a live docpad application. Mainly to reflect what a developer would actually be dealing with in a live application. Parsing the source code alone doesn't really reflect the objects in a live application when taking into account inheritance.

It would be nice if someone with a bit of time on their hands could start converting the source comments to yuidoc ;). Any takers?

**Comment by balupton** [comment]
Does yuidoc work with CoffeeScript? As it will be a while until we convert everything from CoffeeScript to ES6+

**Comment by SteveMcArthur** [comment]
I honestly haven't looked into it too deeply whether yuidoc works in CoffeeScript. I've just assumed that we can substitute js comments for CoffeeScript comments (@pflannery seems to suggest that). Mainly I thought of yuidoc because its pervasive and a decision is better than no decision. But if you're planning to move to ES6 then a js commenting system like yuidoc would make sense in the long run.

For me - I don't really care what system. As long as there is a system.

**Comment by SteveMcArthur** [comment]
As an afterthought. What I'm looking for is that a comment actually pertains to a following method or property. At the moment I'm assuming all preceding comments pertain to the following method/property - which is not always the case. An indication of the type returned by the property/method would be nice, as well as the parameters passed. I think yuidoc also allows for indicating the inherited object - but perhaps that sort of depth could be left for a later day.

**Comment by pflannery** [comment]
I just noticed that it's also possible to pass `--syntaxtype coffee` to the yuidoc cli. I never saw that before :open_mouth: . More info here - http://yui.github.io/yuidoc/args/index.html#command-line

Example Usage: https://github.com/yui/yuidoc/blob/master/tests/input/coffee1/test.coffee

**Comment by SteveMcArthur** [comment]
Thanks to @pflannery. I think we have a decision. All those that say "nay"?

**Comment by balupton** [comment]
If YUIDoc supports CoffeeScript, and someone wants to take adding YUIDoc, that will be great preparation for my ES6+ conversions.

**Comment by SteveMcArthur** [comment]
@balupton OK if no one else sticks their hand up, I'll do it. Let me know how you want me to do it. ie - branching strategy.

**Comment by balupton** [comment]
fork master, and go bit by bit

**Comment by SteveMcArthur** [comment]
ok - will do :+1:

**Comment by balupton** [comment]
Hop on our Slack channel too :) https://slack.bevry.me

**Comment by mikeumus** [comment]
Awesome. I love yui and yuidocs. Gets a 'yay' vote from me. We also have a
trello where we can better track/discuss things like this if you're
interested Steve.

**Comment by balupton** [comment]
@SteveMcArthur I've done a new release, so if you do a pull, `npm run-script meta` will compile the YUIdoc changes. Doesn't seem it is rendering correctly, any ideas?

**Comment by SteveMcArthur** [comment]
No data is being generated in the data.json file and the api.js file. I've tested the generation process in isolation by copying the docpad.coffee file into its own dir and running:

'yuidoc --syntaxtype coffee -e .coffee path_to_dir'

Are you telling yuidoc where the sourcefiles are?

**Comment by balupton** [comment]
@SteveMcArthur right, you need the `-e .coffee`, that's lame

**Comment by balupton** [comment]
@SteveMcArthur fix pushed to master, `npm run-script meta` now generates our YUIdocs and published them to the `docs` directory

**Comment by balupton** [comment]
@SteveMcArthur browseable at https://rawgit.com/docpad/docpad/master/docs/

**Comment by SteveMcArthur** [comment]
@balupton OK - needs to load over http for the http://yui.yahooapis.com/ files to load

**Comment by SteveMcArthur** [comment]
@balupton Not too keen on the existing YUI themes (bit too early 2000s). Had a hunt around, but couldn't find much better. @pflannery's ( https://github.com/pflannery/yuidoc-theme-dyno) is by far the best. But I couldn't get it to work (could be my brain that's frazzled from staring at YUIdoc comments over the last few days).

There is also a "project" node in the YUIdoc.json file which I couldn't seem to get to populate. I assume this data comes from the yuidoc.json file. Lastly, the "module" node is not getting populated, despite this being in the source file.

**Comment by pflannery** [comment]
@SteveMcArthur I will have look at https://github.com/pflannery/yuidoc-theme-dyno over this weekend see what's up.

**Comment by pflannery** [comment]
Also great work so far @SteveMcArthur

**Comment by SteveMcArthur** [comment]
@pflannery I don't think it's your code, I think its just me - not that crash hot with grunt.

Thanks, by the way :)

**Comment by pflannery** [comment]
@SteveMcArthur I understand. 

I've wrapped the app in to a docpad setup. Docpad will bundle the angular app js and copy the static files over automatically. https://github.com/pflannery/yuidoc-theme-dyno 
So just run the usual `docpad generate` or `docpad run` etc...

To change  yuidoc data.json just overwrite the data.json file at the [www/yuidoc](https://github.com/pflannery/yuidoc-theme-dyno/commit/37681b984f2d8df95f689843b31bc8ff7f7667a8) folder

Let me know how you get on ;)

I will be doing some more updates and fixes to  https://github.com/pflannery/yuidoc-theme-dyno this week.

**Comment by balupton** [comment]
Closing as there is now API docs, thanks to @SteveMcArthur.

You can find them at http://master.docpad.docpad.surge.sh/docs/
