### ISSUE TITLE
Improve performance for large sites

### ISSUE THREAD

**Issue by dimitarkolev** [docpad/docpad#936]
Make DocPad work for large site. 10`000 blog posts for example. Right know after going beyond 1000 its getting painfully slow.

Any suggestion or even workaround will be highly appreciated.

**Comment by balupton** [comment]
Is there any file based ssgs that are fast with this amount of blog posts?

**Comment by dimitarkolev** [comment]
I don't know. But I don't think 10'000 is too big number related to software in general. Lets say I want to build a web store based on DocPad 10`000 items aren't that much.

**Comment by balupton** [comment]
Well, 10,000 items and all their contents to keep in memory, which is what most SSGs do, is a lot. For CMS it isn't that much, as they have an external database instead of an in-memory database.

Having an external database is really the proper solution for this - however if another SSG has accomplish good speed with an in-memory database, it would be cool.

**Comment by dimitarkolev** [comment]
I don't think i have memory problems i have like 16G of ram and its more than enough to store all documents but docpad gets very slow when there are even 1000 documents (10min for generation).

Beside that how hard is to abstract QueryEngine to a database? And have two options:
1. docpad dump and put document data in the database
2. docpad generates only based on the document data from the database

**Comment by Greduan** [comment]
One thing I'd like to note is that most CMSs are dynamic, which means they just load the page whenever it's asked for and then cache it.

DocPad generates everything once, and then you serve the static site. This is certainly going to take much more time than generating stuff only when needed

Unless you're using DocPad's dynamic features in which case yeah, this is a problem.

**Comment by dimitarkolev** [comment]
10min for 1`000 documents is one thing (still too much) but 2hours for 10`000 is not working scenario by much.
There is huge place for optimization. Those times are based on very optimized DocPad configuration. I believe that if i run it with defaults it will be easily 5 times more.

**Comment by Greduan** [comment]
Yeah that's a problem. Perhaps DocPad never actually releases the memory of documents it's already processed?

**Comment by dimitarkolev** [comment]
Its not a memory issue. There is plenty of free memory and SSD as well.

**Comment by asatgs** [comment]
@dimitarkolev Are your documents really that interconnected that you need to regenerate all of them? Or is it a case where you have a menu that has links to everything?

In my case it is the latter so I just wrote a plugin that generates a JSON menu file on every `writeBefore` event and marked every document as `standalone`. That menu file is then dynamically fetched by each document. This has it's drawback as the menu will load via a script but the regeneration time for a single document is now nearly instant.

**Comment by dimitarkolev** [comment]
There a are a lot of references between documents (mostly interested in other documents metadata) so i think having standalone is not an option. And initial generation time is with the same importance as the regeneration time.
What we did is that we divided the documents in several src/documents folders(mostly based on the interconnection between categories) and set up different docpad environments building only a specific portion of the site, but its hacky solution.

**Comment by dimitarkolev** [comment]
I have a question regarding referencesOthers. In the documentation its written: It is automatically set to true whenever a template helper is called that references another document.
What is template helper?

**Comment by pflannery** [comment]
Docpad and a lot of associated coffee-script libraries will get a bit of a boost from [this](https://github.com/jashkenas/coffeescript/issues/3274#issuecomment-75263418) change when it happens and it looks like the change is being made as I write this. TaskGroup relies heavily on ```args...``` statements and is a big piece behind docpad. 

@dimitarkolev do you have a test project we can look at?

**Comment by dimitarkolev** [comment]
I will prepare one in the upcoming days. The project I am referring is way to complex for investigation. It has several custom plugins pulling data from legacy systems and very complex structure. At it will require VPN and some extra configuration to be able to run outside our environment. I believe it will much better to illustrate the problem with very simple site. I'll make sure it wont be oversimplified but more like real world scenario.

**Comment by balupton** [comment]
@dimitarkolev thanks, having a test site for this will certainly help. There's certainly many optimisations that could be made, all of which would optimise different things for different use cases. Having a test site would allow me to recommend the correct optimisation for your case.

In the future, it will be good for us to have an advanced docpad section in the manual (perhaps a paid/donation book!) which could go into more advanced optimisations - such as caching partials, etc.

**Comment by JeremyBYU** [comment]
Hugo is a SSG built with Go that generates content very fast.  According to this about 5000 posts in 6 seconds.  

https://www.youtube.com/watch?v=CdiDYZ51a2o

> Is there any file based ssgs that are fast with this amount of blog posts?

**Comment by balupton** [comment]
@JeremyBYU interesting... any idea if Hugo supports cross-document referencing? As this is one of the features that slows DocPad down - I think most SSGs only do 1 render pass, whereas docpad does 1 for files that don't reference anything else, and 2 for files that do. This is the area of the largest redundancy, but it allows the use case of blog post listings containing the content of the rendered blog posts rather than just meta titles.

I'm not sure if the solution is to allow tweaks to the current DocPad workflow, or to rewrite DocPad's ORM  and templating systems to be database agnostic - as such things would allow us to say use MongoDB for the database, store last modified and last generated times for documents, as well as the rendered steps along the way, as well as getting rid of anything in memory that we don't need, as we could provide some async templating helpers that could do async database fetches in the templates. Could be an option.

**Comment by dimitarkolev** [comment]
I remember the time when docpad was blazing fast. It was the time when
docpad was just static site generator. I don't think that two pass or tree
pass rendering has anything to do with the performance issues. I think that
the main issue are so called live collections. I remember the time when
they were introduced and its the time things become slow. I am not that
familiar with docpad's code and I am not sure why is that. From all my
experiments the speed has nothing to do with rendering process itself.
There are plenty of plugins that update documents metadata and this makes
live collections and subscribed listeners do crazy things. There is no
batch mode, so if a plugin changes document property and live collection
fires change and another plugin is listening to this change it starts to do
things but in most cases plugins do change set of documents that makes a
storm of unnecessary things going on for every change. I am not sure about
my observation and @benjamin might have better understanding of the
problem. My observation is based on my experience with docpad and its
evolution.

**Comment by pflannery** [comment]
I've made a really basic 1000 document setup which all use a basic layout. https://github.com/pflannery/docpad-large-site-test/
It took me 2.35 minutes to render. 

Its obviously not a real world scenario setup but it could be something to work with.

**Comment by balupton** [comment]
Sweet. I know that eco is really slow, someone posted benchmarks of eco vs something else a while ago. I can't recall where that comparison lies.

**Comment by futekov** [comment]
This benchmark compares some of the template engines - http://jsperf.com/dom-vs-innerhtml-based-templating/957 - eco is close to 10 times slower than the fastest one.

**Comment by balupton** [comment]
http://ectjs.com is the one I remember, however I also found http://beebole.com/pure/ and https://olado.github.io/doT/index.html which claim to be fast (the latter are in @futekov's link)

**Comment by balupton** [comment]
However, the benchmarks are still completing in a <10 seconds for 100,000 plus renders. So it's not the templating engine's fault.

**Comment by dimitarkolev** [comment]
If you add paged plugin it will get at least three times slower. And when
dealing with that much documents its common scenario.

**Comment by balupton** [comment]
So I swapped out Backbone for [Exoskeleton](http://exosjs.com/) locally which is meant to be 20x faster than Backbone.

With Exoskeleton:

```
info: Generated 1000/1001 files in 170.041 seconds
info: Generated 1000/1001 files in 170.686 seconds
info: The action completed successfully
info: Shutting down... cya next time!
```

With Backbone:

```
info: Generated 1000/1001 files in 174.208 seconds
info: Generated 1000/1001 files in 170.458 seconds
```

So insignificant difference... Although visually it seems that renderFiles is faster with Exoskeleton. Would be good to get better data on each thing - I believe someone has a benchmarking plugin for DocPad.

I've also been considering adding some extensions to TaskGroup to generate flame-like graphs.

**Comment by balupton** [comment]
Okay with the `benchmark` extension:

With Exoskeleton:

```
event               │ time in ms │ percentage │
populateCollections │ 55839      │ 32%        │
contextualizeAfter  │ 12392      │ 7%         │
renderAfter         │ 89579      │ 51%        │
writeAfter          │ 17506      │ 10%        │
Total               │ 175654     │            │
```

With Backbone:

```
event               │ time in ms │ percentage │
populateCollections │ 54757      │ 32%        │
contextualizeAfter  │ 11964      │ 7%         │
renderAfter         │ 87359      │ 51%        │
writeAfter          │ 17404      │ 10%        │
Total               │ 171834     │            │
```

So again, an insignificant difference between Backbone and Exoskeleton.

**Comment by balupton** [comment]
Until we get flame graphs or proper profiling tools for Node.js, it is going to be very hard to track this down.

**Comment by dimitarkolev** [comment]
Why does renderAfter and populateCollections take so much time? 

As a side note: My observation is that when you add paged plugin to your site you get x2(even more) to the render time. I dont know what is the special thing with it, I looked many hours on the code and did not find anything extraordinary there so I assume its something in docpad worlkflow. 

Unfortunately I dont have good understanding about DocPad internals but we do have huge experience using it :) We want to start few big projects (in terms of page count) but i am afraid it wont scale enough.

**Comment by balupton** [comment]
populate reads the files, render renders the files

**Comment by balupton** [comment]
> I don't think that two pass or tree
> pass rendering has anything to do with the performance issues. I think that
> the main issue are so called live collections.

Live collections speed things up. I've removed any collection listeners locally, and it's impact was trivial.

**Comment by dimitarkolev** [comment]
I know task group has parallel mode... cant DocPad read/write/render the files in parallel? I know hdd is blocking but from this statistic it looks like the IO is not big part of the process.

**Comment by balupton** [comment]
It does.

**Comment by dimitarkolev** [comment]
From what i see one core at 100% all the rest under 2% all the way to the end.

**Comment by balupton** [comment]
Node is a one core per process thing. We can't do anything about that, unless we split docpad into multiple processes. Ref #793

**Comment by balupton** [comment]
This discussion isn't providing too useful. Let's leave it for implemented proposals, rather than proposal speculations.

**Comment by dimitarkolev** [comment]
No more ideas :)

**Comment by pflannery** [comment]
One thing I've found so far is that TaskGroup is generating a lot of overhead memory and I've got a feeling that this overhead is giving the GC a lot to work with.
You can see my findings in the issue I have raised for [TaskGroup](https://github.com/bevry/taskgroup/issues/19) and the GC report below that was generated when running the [test site](https://github.com/pflannery/docpad-large-site-test) I posted above.

```sh
$ node --trace_gc ./node_modules/docpad/bin/docpad generate
[6156]       58 ms: Scavenge 2.0 (37.6) -> 1.7 (37.6) MB, 1.0 ms [allocation failure].
[6156]       61 ms: Scavenge 2.0 (37.6) -> 2.0 (38.6) MB, 2.0 ms [allocation failure].
[6156]      103 ms: Scavenge 3.2 (38.6) -> 3.0 (38.6) MB, 1.0 ms [allocation failure].
[6156]      123 ms: Scavenge 4.4 (39.6) -> 4.0 (40.6) MB, 1.0 ms [allocation failure].
[6156]      153 ms: Scavenge 5.2 (41.6) -> 4.9 (41.6) MB, 1.0 ms [allocation failure].
[6156]      221 ms: Scavenge 8.6 (42.6) -> 6.1 (43.6) MB, 2.0 ms [allocation failure].
[6156]      300 ms: Scavenge 9.9 (43.6) -> 6.9 (44.6) MB, 1.0 ms [allocation failure].
[6156]      387 ms: Scavenge 11.1 (45.6) -> 7.9 (45.6) MB, 1.0 ms [allocation failure].
[6156]      463 ms: Scavenge 12.0 (45.6) -> 9.3 (45.6) MB, 2.0 ms [allocation failure].
[6156]      620 ms: Scavenge 17.9 (47.6) -> 12.1 (48.6) MB, 3.0 ms [allocation failure].
[6156]      766 ms: Scavenge 20.6 (49.6) -> 15.6 (51.6) MB, 1 / 6.0 ms [allocation failure].
[6156]      941 ms: Scavenge 23.1 (52.6) -> 17.3 (53.6) MB, 4.0 ms [allocation failure].
[6156]     1137 ms: Scavenge 26.6 (55.6) -> 20.9 (55.6) MB, 3.0 ms [allocation failure].
info: Welcome to DocPad v6.73.5 (local installation: d:\temp\dp\node_modules\docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: jade
info: Environment: development
Performing generate tasks ?  fetch data to render at 3/10 30% ==============-----------------------------------[6156]     1641 ms: Scavenge 38.8 (60.6) -> 27.7 (61.6) MB, 8.0 ms [allocation failure].
[6156]     1972 ms: Scavenge 41.6 (63.6) -> 31.2 (66.6) MB, 10.0 ms [allocation failure].
[6156]     2413 ms: Scavenge 45.2 (67.6) -> 32.6 (69.6) MB, 8.0 ms [allocation failure].
[6156]     2915 ms: Scavenge 48.4 (70.6) -> 35.1 (71.6) MB, 6.0 ms [allocation failure].
[6156]     3392 ms: Scavenge 50.1 (71.6) -> 37.3 (73.6) MB, 8.0 ms [allocation failure].
[6156]     3880 ms: Scavenge 52.3 (74.6) -> 39.1 (75.6) MB, 6.0 ms [allocation failure].
[6156]     4315 ms: Scavenge 54.3 (75.6) -> 40.6 (76.6) MB, 4.0 ms [allocation failure].
[6156]     4744 ms: Scavenge 55.8 (77.6) -> 41.4 (77.6) MB, 3.0 ms [allocation failure].
[6156]     5193 ms: Scavenge 57.0 (79.6) -> 42.7 (80.6) MB, 5.0 ms [allocation failure].
[6156]     5622 ms: Scavenge 58.3 (80.6) -> 43.8 (81.6) MB, 3.0 ms [allocation failure].
[6156]     6019 ms: Scavenge 59.2 (81.6) -> 44.7 (81.6) MB, 3.0 ms [allocation failure].
[6156]     6659 ms: Scavenge 60.0 (81.6) -> 45.4 (82.6) MB, 4.0 ms [allocation failure].
[6156]     7338 ms: Scavenge 61.0 (82.6) -> 45.9 (83.6) MB, 2.0 ms [allocation failure].
[6156]     8009 ms: Scavenge 61.5 (83.6) -> 46.3 (83.6) MB, 2.0 ms [allocation failure].
[6156]     8681 ms: Scavenge 61.9 (83.6) -> 46.7 (83.6) MB, 2.0 ms [allocation failure].
[6156]     9410 ms: Scavenge 62.3 (84.6) -> 47.2 (85.6) MB, 2.0 ms (+ 46.0 ms in 235 steps since last GC) [allocation failure].
[6156]     9717 ms: Mark-sweep 53.5 (85.6) -> 32.0 (85.6) MB, 12.0 ms (+ 56.0 ms in 330 steps since start of marking, biggest step 1.0 ms) [GC interrupt] [GC in old space requested].
[6156]    10394 ms: Scavenge 47.9 (85.6) -> 32.5 (85.6) MB, 2.0 ms [allocation failure].
[6156]    11084 ms: Scavenge 48.2 (85.6) -> 33.0 (85.6) MB, 3.0 ms [allocation failure].
[6156]    11767 ms: Scavenge 48.6 (85.6) -> 33.4 (85.6) MB, 3.0 ms [allocation failure].
[6156]    12440 ms: Scavenge 49.0 (85.6) -> 33.8 (85.6) MB, 2.0 ms [allocation failure].
[6156]    13058 ms: Scavenge 50.2 (85.6) -> 35.4 (85.6) MB, 3.0 ms [allocation failure].
Performing contextualizeFiles at 0/100 0% -------------------------------------------------[6156]    13591 ms: Scavenge 51.3 (85.6) -> 37.1 (85.6) MB, 5.0 ms [allocation failure].
[6156]    14107 ms: Scavenge 52.9 (85.6) -> 39.1 (85.6) MB, 6.0 ms [allocation failure].
Performing contextualizeFiles at 8/100 8% ===----------------------------------------------[6156]    14619 ms: Scavenge 54.2 (85.6) -> 40.0 (85.6) MB, 5.0 ms [allocation failure].
Performing contextualizeFiles at 49/100 49% ========================-------------------------[6156]    15139 ms: Scavenge 55.5 (85.6) -> 40.9 (85.6) MB, 4.0 ms [allocation failure].
Performing contextualizeFiles at 92/100 92% =============================================----[6156]    15657 ms: Scavenge 56.3 (85.6) -> 41.8 (86.6) MB, 4.0 ms [allocation failure].
Performing renderFiles (pass 1) at 0/100 0% -------------------------------------------------[6156]    16173 ms: Scavenge 57.4 (86.6) -> 43.0 (87.6) MB, 6.0 ms [allocation failure].
[6156]    16691 ms: Scavenge 58.8 (87.6) -> 44.9 (87.6) MB, 6.0 ms [allocation failure].
[6156]    17199 ms: Scavenge 60.1 (87.6) -> 46.2 (88.6) MB, 6.0 ms [allocation failure].
[6156]    17715 ms: Scavenge 61.7 (89.6) -> 48.5 (89.6) MB, 6.0 ms [allocation failure].
[6156]    18212 ms: Scavenge 63.1 (90.6) -> 50.3 (91.6) MB, 8.0 ms [allocation failure].
[6156]    18671 ms: Scavenge 65.4 (91.6) -> 52.0 (93.6) MB, 7.0 ms [allocation failure].
[6156]    19175 ms: Scavenge 67.4 (94.6) -> 54.1 (95.6) MB, 7.0 ms [allocation failure].
[6156]    19521 ms: Scavenge 71.0 (98.6) -> 57.5 (99.6) MB, 6.0 ms [allocation failure].
[6156]    19671 ms: Scavenge 73.1 (99.6) -> 59.1 (100.6) MB, 5.0 ms [allocation failure].
[6156]    20106 ms: Scavenge 74.3 (100.6) -> 59.6 (101.6) MB, 5.0 ms [allocation failure].
[6156]    20576 ms: Scavenge 75.4 (101.6) -> 60.2 (101.6) MB, 4.0 ms [allocation failure].
[6156]    21061 ms: Scavenge 76.1 (101.6) -> 61.1 (102.6) MB, 3.0 ms [allocation failure].
[6156]    21576 ms: Scavenge 77.1 (103.6) -> 62.9 (103.6) MB, 5.0 ms [allocation failure].
[6156]    22041 ms: Scavenge 77.8 (104.6) -> 63.4 (105.6) MB, 6.0 ms [allocation failure].
[6156]    22475 ms: Scavenge 79.5 (105.6) -> 65.2 (105.6) MB, 5.0 ms [allocation failure].
[6156]    22834 ms: Scavenge 80.4 (105.6) -> 67.5 (107.6) MB, 6.0 ms [allocation failure].
[6156]    23270 ms: Scavenge 82.0 (107.6) -> 68.8 (108.6) MB, 7.0 ms [allocation failure].
[6156]    23803 ms: Scavenge 84.3 (109.6) -> 70.8 (110.6) MB, 7.0 ms [allocation failure].
[6156]    24310 ms: Scavenge 85.7 (110.6) -> 72.5 (112.6) MB, 8.0 ms [allocation failure].
[6156]    24781 ms: Scavenge 87.5 (112.6) -> 74.0 (113.6) MB, 8.0 ms [allocation failure].
[6156]    25285 ms: Scavenge 89.4 (115.6) -> 76.0 (116.6) MB, 7.0 ms [allocation failure].
[6156]    25555 ms: Scavenge 91.3 (117.6) -> 78.3 (119.6) MB, 8.0 ms [allocation failure].
[6156]    25665 ms: Scavenge 92.8 (119.6) -> 79.1 (120.6) MB, 7.0 ms [allocation failure].
[6156]    25776 ms: Scavenge 94.5 (120.6) -> 79.7 (121.6) MB, 5.0 ms [allocation failure].
[6156]    26121 ms: Scavenge 95.3 (122.6) -> 80.3 (122.6) MB, 4.0 ms [allocation failure].
[6156]    26590 ms: Scavenge 96.0 (122.6) -> 80.8 (123.6) MB, 5.0 ms [allocation failure].
[6156]    27067 ms: Scavenge 96.6 (123.6) -> 81.4 (123.6) MB, 4.0 ms [allocation failure].
[6156]    27604 ms: Scavenge 97.7 (124.6) -> 83.5 (124.6) MB, 6.0 ms [allocation failure].
[6156]    28056 ms: Scavenge 98.2 (124.6) -> 84.0 (125.6) MB, 6.0 ms [allocation failure].
Performing renderFiles (pass 1) at 4/100 4% =------------------------------------------------[6156]    28538 ms: Scavenge 99.7 (125.6) -> 84.7 (126.6) MB, 5.0 ms [allocation failure].
Performing renderFiles (pass 1) at 16/100 16% =======------------------------------------------[6156]    29001 ms: Scavenge 100.3 (126.6) -> 85.3 (126.6) MB, 5.0 ms [allocation failure].
Performing renderFiles (pass 1) at 28/100 28% =============------------------------------------[6156]    29463 ms: Scavenge 100.8 (126.6) -> 85.8 (127.6) MB, 4.0 ms [allocation failure].
Performing renderFiles (pass 1) at 40/100 40% ===================------------------------------[6156]    29925 ms: Scavenge 101.4 (127.6) -> 86.4 (127.6) MB, 5.0 ms [allocation failure].
Performing renderFiles (pass 1) at 51/100 51% =========================------------------------[6156]    30389 ms: Scavenge 102.0 (128.6) -> 87.0 (129.6) MB, 5.0 ms [allocation failure].
Performing renderFiles (pass 1) at 63/100 63% ===============================------------------[6156]    30855 ms: Scavenge 102.6 (129.6) -> 87.6 (129.6) MB, 5.0 ms [allocation failure].
Performing renderFiles (pass 1) at 75/100 75% =====================================------------[6156]    31324 ms: Scavenge 103.1 (129.6) -> 88.1 (129.6) MB, 5.0 ms [allocation failure].
Performing renderFiles (pass 1) at 87/100 87% ===========================================------[6156]    31787 ms: Scavenge 103.7 (130.6) -> 88.8 (130.6) MB, 6.0 ms [allocation failure].
Performing renderFiles (pass 1) at 99/100 99% =================================================[6156]    32255 ms: Scavenge 104.3 (130.6) -> 89.3 (130.6) MB, 5.0 ms [allocation failure].
Performing writeFiles at 0/100 0% -------------------------------------------------[6156]    32726 ms: Scavenge 105.6 (131.6) -> 91.2 (131.6) MB, 6.0 ms [allocation failure].
[6156]    33190 ms: Scavenge 106.5 (131.6) -> 92.9 (132.6) MB, 8.0 ms [allocation failure].
[6156]    33686 ms: Scavenge 108.2 (134.6) -> 94.4 (135.6) MB, 9.0 ms [allocation failure].
[6156]    34193 ms: Scavenge 109.7 (136.6) -> 95.4 (137.6) MB, 1 / 8.0 ms [allocation failure].
Performing writeFiles at 22/100 22% ==========---------------------------------------[6156]    34737 ms: Scavenge 110.8 (137.6) -> 96.0 (137.6) MB, 5.0 ms [allocation failure].
Performing writeFiles at 63/100 63% ===============================------------------[6156]    35232 ms: Scavenge 111.8 (137.6) -> 96.6 (138.6) MB, 7.0 ms [allocation failure].
undefined
info: Generating...
info: Generated 100/101 files in 34.221 seconds
[6156]    35736 ms: Scavenge 112.5 (138.6) -> 97.4 (138.6) MB, 6.0 ms [allocation failure].
info: The action completed successfully
info: Shutting down... cya next time!
```

**Comment by pflannery** [comment]
@balupton 
> Until we get flame graphs or proper profiling tools for Node.js, it is going to be very hard to track this down.

I've found that we can use [v8-profiler](https://github.com/node-inspector/v8-profiler/) along with google's dev tools to look at the flame chart and where most of the time is spent.

Here is a basic example of generating a cpu profile. Then in chrome dev tools load the output file under Profiles and switch to chart mode
```js
function saveCpuProfile(fileName, profile) {
  fs.writeFileSync(fileName, JSON.stringify(profile))
}

var profiler = require('v8-profiler');
profiler.startProfiling();
// ... do something
var profile = profiler.stopProfiling();
saveCpuProfile("complete.cpuprofile", profile);
```

**Comment by pflannery** [comment]
To make life easier I've made a small plugin called [cpuprofiler](https://github.com/pflannery/docpad-plugin-cpuprofiler) that will record cpu profiles between single or multiple events and save the snapshots to file. These snapshots can then be opened in chrome dev tools ;)

**Comment by jlukic** [comment]
My modest sized project (50ish pages) takes about 90 seconds to regenerate on my virtual machine. Basically its hell if i change any partial that modifies more than one page.

**Comment by balupton** [comment]
For what it's worth, node v4 is now out, here's some benchmarks:

---

Running DocPad v6.78.3 on a 1,000 document sample site using jade templates:

Node v4
info: Generated 1000/1001 files in 109.393 seconds

Node v0.12
info: Generated 1000/1001 files in 193.692 seconds

Sample site was @pflannery 
https://github.com/pflannery/docpad-large-site-test

---

@pflannery want to transfer that repo to the docpad org? And I’ll spruce it up and use it as an official benchmark test.

**Comment by pflannery** [comment]
@balupton done.

**Comment by balupton** [comment]
@pflannery sweet, all spruced up

**Comment by dimitarkolev** [comment]
I can confirm that with node4 render time on one of our projects went down from 20min to 10min.

**Comment by balupton** [comment]
So out of curiosity, I've tried the ES6 branch of TaskGroup on node 0.12 and node 4, pretty much the same:

```
Running benchmarks on: { http_parser: '2.3',
  node: '0.12.7',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1p' }
Adding 100000 tasks
Running tasks
Completed 100000 tasks. Total seconds: 8.10
```

```
Running benchmarks on: { http_parser: '2.5.0',
  node: '4.0.0',
  v8: '4.5.103.30',
  uv: '1.7.3',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '46',
  openssl: '1.0.2d' }
Adding 100000 tasks
Running tasks
Completed 100000 tasks. Total seconds: 8.32
```

So, the ES6 performance at least for TaskGroup is the same. TaskGroup's ES6 version still brings huge performance benefits over TaskGroup's current CoffeeScript version, so still expect to see huge performance gains when the ES6 version lands.

**Comment by balupton** [comment]
DocPad v6.80 should be order of magnitudes faster.

**Comment by balupton** [comment]
Dupe of #545

**Comment by balupton** [comment]
https://github.com/docpad/docpad-skeleton-benchmark

- docpad 6.78.3 rendered 1000 eco 2.2.1 documents with layout in 47.92 seconds
- docpad 6.83.1 rendered 1000 eco 2.5.0 documents with layout in 6.363 seconds
