### ISSUE TITLE
Fix --no-color

### ISSUE THREAD

**Issue by Zearin** [docpad/docpad#938]
It’s plainly visible in the Terminal.  It wasn’t showing up when I copy-pasted it straight from the terminal, so I redirected it to a file for a few seconds like so:

```
$ ./node_modules/.bin/docpad --debug 7 --no-color run > _no_color.log
^C
```

Here’s what I got:

```
[32mdebug:[39m load tasks ➞  normalize the userConfigPath > added
    [2m→ [2015-02-26 07:54:43.417] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  load the user's configuration > added
    [2m→ [2015-02-26 07:54:43.432] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  load the anonymous user's configuration > added
    [2m→ [2015-02-26 07:54:43.437] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  load the website's package data > added
    [2m→ [2015-02-26 07:54:43.441] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  read the .env file if it exists > added
    [2m→ [2015-02-26 07:54:43.444] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  load the website's configuration > added
    [2m→ [2015-02-26 07:54:43.449] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks > started
    [2m→ [2015-02-26 07:54:43.453] [events.js:104] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  normalize the userConfigPath > started
    [2m→ [2015-02-26 07:54:43.456] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  normalize the userConfigPath > done
    [2m→ [2015-02-26 07:54:43.462] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  load the user's configuration > started
    [2m→ [2015-02-26 07:54:43.466] [events.js:107] [_Class.emit][22m
[32mdebug:[39m Loading user's configuration: /Users/tony/Dropbox/.docpad.cson
    [2m→ [2015-02-26 07:54:43.471] [/Users/tony/__PROJECT__/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55] [ambi][22m
[32mdebug:[39m Loading configuration path: /Users/tony/Dropbox/.docpad.cson
    [2m→ [2015-02-26 07:54:43.474] [/Users/tony/__PROJECT__/node_modules/docpad/out/lib/docpad.js:1710] [DocPad.loadConfigPath][22m
[32mdebug:[39m Loading user's configuration: /Users/tony/Dropbox/.docpad.cson
    [2m→ [2015-02-26 07:54:43.485] [/Users/tony/__PROJECT__/node_modules/docpad/out/lib/docpad.js:1706] [unknown][22m
[32mdebug:[39m load tasks ➞  load the user's configuration > done
    [2m→ [2015-02-26 07:54:43.487] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  load the anonymous user's configuration > started
    [2m→ [2015-02-26 07:54:43.491] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  load the anonymous user's configuration > done
    [2m→ [2015-02-26 07:54:43.494] [events.js:107] [_Class.emit][22m
[32mdebug:[39m load tasks ➞  load the website's package data > started
    [2m→ [2015-02-26 07:54:43.498] [events.js:107] [_Class.emit][22m
[32mdebug:[39m Loading website package.json configuration: /Users/tony/__PROJECT__/package.json
    [2m→ [2015-02-26 07:54:43.500] [/Users/tony/__PROJECT__/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55] [ambi][22m
[32mdebug:[39m Loading configuration path: /Users/tony/__PROJECT__/package.json
    [2m→ [2015-02-26 07:54:43.503] [/Users/tony/__PROJECT__/node_modules/docpad/out/lib/docpad.js:1710] [DocPad.loadConfigPath][22m
[32mdebug:[39m Loaded website package.json configuration: /Users/tony/__PROJECT__/package.json
    [2m→ [2015-02-26 07:54:43.508] 
```

---
## Recommend the following:
- [ ] Make `--no-color` work unconditionally
- [ ] Make colorful output ONLY work when the output is connected to a Terminal (i.e., automatically turn off colors if output is being redirected)

---

**Edit:** Replaced middle of the path with **PROJECT**
**Edit:** Trimmed output text length

**Comment by balupton** [comment]
Strange, as a lot of work was done on this. Only evidence that tests are needed it seems! Perhaps we could also pull request to caterpillar-human to some degree. @Zearin do you want to take this one? :-)

**Comment by Zearin** [comment]
I wish I could.  :(  I have too much going on right now to do much of anything!  

Most of my time lately is spent on a project that uses DocPad, which is why I’ve been reporting stuff lately.

When I am once again able to, I’ll pitch in, for sure.  I’m sorry I can’t do much beyond report this for the moment, but I’m kind of maxed out.  :-/

**Comment by balupton** [comment]
No worries. I'll add it to my todo.

@mikeumus perhaps it would be good to use trello or something simpler just so that people can see my current todo flow. Currently I've been using our telegram group for that, but perhaps trello or any other Kanban board would be better.

**Comment by mikeumus** [comment]
Yeah, we do already have Huboard too which ties nicely with GitHub: 
- https://huboard.com/docpad/docpad/#/

It's simpler in some ways but has been getting better. I'd be fine using this, just need a little cleaning.

**Comment by balupton** [comment]
I was imagining something more like each of the core team have their own stack, and we can drag things into our stacks in the order we are doing them. They don't necessarily have to be project or even work specific. For instance I will add my "4 day roadtrip" to the top now, as that is what I'll be doing.

Then there will be an "icebox" of things that our extras team people and strangers/guests can grab if they want.

**Comment by mikeumus** [comment]
Yeah that sounds pretty good. I'll set it up.

**Comment by balupton** [comment]
This still isn't fixed.
