### ISSUE TITLE
Why does docpad depend on ifconfig?

### ISSUE THREAD

**Issue by asdofindia** [docpad/docpad#939]
````
warning: Failed to get your computer's MAC address
The error follows:

Error: Command failed: /bin/sh -c ifconfig
/bin/sh: ifconfig: command not found

  at ChildProcess.exithandler (child_process.js:744:12)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1008:16)
  at Socket.<anonymous> (child_process.js:1176:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:476:12)
````

I'm running ArchLinux and there is no ifconfig installed. 

This doesn't hinder docpad in any way, but I'm just curious why it is needed.

**Comment by Greduan** [comment]
For setting up a server I'm guessing? I didn't have this problem when I was in Arch though, weird.

**Comment by pflannery** [comment]
I wonder if this also happens on centos 7?

It seems its this [line here](https://github.com/docpad/docpad/blob/cd40065f355678aa47596e6d198579af8a3ef3dd/src/lib/docpad.coffee#L1753), which means the issue probably bubbles up from [getmac](https://github.com/bevry/getmac)

I'm going to guess here but its needed for reporting statistics if the user has opted in but is anonymous. 

You might be able to avoid this error by going to ~/.docpad.cson and entering a username. Its worth a try anyway

**Comment by pflannery** [comment]
seems there is a pull request for arch linux for getmac - https://github.com/bevry/getmac/pull/10

**Comment by SteveMcArthur** [comment]
@pflannery this also happens on Windows!

**Comment by pflannery** [comment]
@SteveMcArthur what version are you seeing that on? I'm on Windows 8.1 and I'm not seeing this

**Comment by balupton** [comment]
closed as  bevry/getmac#10 is now implemented

**Comment by maciejmyslinski** [comment]
@balupton the error still occurs on OS X 10.11.5
I have iTerm with zsh, though. I do not know if this is somehow connected.

**Comment by balupton** [comment]
@maciejmyslinski that's strange, can you upload the docpad-debug.log somewhere and link me

getmac is on my queue for things to update in the coming weeks, actually already did a maintenance release of it 10 days ago, so another release with better changes come soon

https://github.com/docpad/docpad/issues/1041 may also fix this, as we move away from all analytics, thus not needing getmac anymore

**Comment by maciejmyslinski** [comment]
@balupton I do not see docpad-debug.log file anywhere. How can I generate it?

**Comment by mikeumus** [comment]
Hey @maciejmyslinski, see docpad.org/support page on docs for getting the docpad-debug.log file:
 - http://docpad.org/docs/support/

> The docpad-debug.log file when you run DocPad in debug mode by specifying the `-d` flag (e.g., `docpad run -d`)

**Comment by maciejmyslinski** [comment]
Great!
[Here it is](https://drive.google.com/file/d/0B5RQQCK7AeJqb0hjVFFQakl5ZG8/view?usp=sharing) 👍

**Comment by balupton** [comment]
@maciejmyslinski thanks for that, does `/sbin/ifconfig` exist for you when running in your terminal program, so `/sbin/ifconfig -a`

**Comment by maciejmyslinski** [comment]
@balupton yes, command `/sbin/ifconfig -a` works for me and prints some information.

**Comment by maciejmyslinski** [comment]
Hey, this problem still occurs since on OS X there is no ifconfig nor ip command.
