### ISSUE TITLE
docpad is not defined

### ISSUE THREAD

**Issue by Naatan** [docpad/docpad#940]
I just updated docpad (having not updated for a while) and am running into a 'docpad is not defined' error in my docpad.coffee templateData.

I read that for plugins docpad is not accessible at certain times anymore, but for templateData?

Is there some type of alternate way that I should be accessing docpad?

**Comment by mikeumus** [comment]
Ben's out on a road-trip and the DocPad website isn't using the very latest version of DocPad currently but I'd say just check how it's using `@docpad` here:
https://github.com/docpad/website/blob/master/docpad.coffee#L361

**Comment by balupton** [comment]
Not enough info to make any further action on this.
