### ISSUE TITLE
How to configure subdomains?

### ISSUE THREAD

**Issue by Zearin** [docpad/docpad#945]
How would I configure a subdomain in `docpad.coffee`?  

Let’s suppose I want to map all requests from `http://img.localhost:9778/*` to `http://localhost:9778/img/*`.  How would I do that?

**Comment by balupton** [comment]
See how the `oldUrls` configuration works inside the DocPad website skeleton. Could probably be made into a plugin if it isn't already a plugin.

**Comment by Zearin** [comment]
> See how the oldUrls configuration works inside the DocPad website skeleton. Could probably be made into a plugin if it isn't already a plugin.

I just went to [`docpad.coffee`](https://github.com/docpad/website/blob/master/docpad.coffee) in docpad/website, and did a search for “`oldUrls`”.  No results.

**Comment by balupton** [comment]
Hrmm, must have removed it. Bevry website still has it: https://github.com/bevry/website/blob/309dc978d0d4f6c541fc0057a37d724bc57447a5/docpad.coffee#L291-L296

**Comment by Zearin** [comment]
What if I want subdomains on a non-Express server?

**Comment by balupton** [comment]
You would have a docpad project for each subdomain, or you would have a single project and just change the templateData.site.url accordingly.
