### ISSUE TITLE
file not updated the second time is has been changed?

### ISSUE THREAD

**Issue by madshobye** [docpad/docpad#949]
The site is not regenerated the second time a change the content of a markdown file. It is a strange problem but pretty consistent. Anybody who knows what causes this?

I am using the following setup:

Mac Osx (yosimite) edit with sublime or textmate. This is synced via dropbox to an ubuntu server running docpad.

I have the same expereince when running docpad locally on my mac.

**Comment by balupton** [comment]
What happens with the suggestions here:
https://docpad.org/docs/troubleshoot#watching-doesn-t-work-works-only-some-of-the-time-i-get-eisdir-errors

**Comment by madshobye** [comment]
Yes! Thanks!
