### ISSUE TITLE
Why doesn’t `filesPaths` do like `docpad-plugin-raw`?

### ISSUE THREAD

**Issue by Zearin** [docpad/docpad#950]
The `docpad-plugin-raw` plugin is recommended for possible performance gains over the built-in processing done in `filesPaths`.  

Why?  How come the default behavior is not like `docpad-plugin-raw`?

**Comment by balupton** [comment]
It doesn't need to be in the core, so it isn't. Just like partials. It can be handled fine by a plugin. We should recommend the plugin more.

**Comment by mikeumus** [comment]
Consider it a step towards the "Abstract all the things" Milestone. But @Zearin has a point, modules can come standard especially if it's another notch of speed on our belts.

**Comment by balupton** [comment]
> modules can come standard especially if it's another notch of speed on our belts.

A lot of thought has been put into bundled plugins - the conclusion has been that the issues are too high with it - instantly incompatibilities between sites can arise, and what happens if a deploy occurs and that plugin is missing locally? Too difficult.

We should treat it the same as we treat renderer plugins - very good docs encouraging its use.

**Comment by SteveMcArthur** [comment]
I think what @Zearin is getting at is there is a natural assumption that the point of the filesPaths is that it does what the raw plugin actually does. There is a possibility that new users won't realise that this is not the case and just think docpad is slow after dumping a whole lot of js files and images into the filesPaths.

**Comment by Zearin** [comment]
> I think what @Zearin is getting at is there is a natural assumption that the point of the filesPaths is that it does what the raw plugin actually does. There is a possibility that new users won't realise that this is not the case and just think docpad is slow after dumping a whole lot of js files and images into the filesPaths.
> 

Yes. Exactly. 

(Thank you for expressing my thoughts in clearer phrasing.)

**Comment by balupton** [comment]
Perhaps the confusion here is to think that we can just replace the filesPaths concept with the raw plugin behaviour, when they do different things.

Files in DocPad are for when you need a file loaded into the in-memory database for querying/accessing but when it doesn't need to be rendered or have a meta header. Raw plugin is for when you the files don't need to be touched at all.

I think in the docs these days we have renamed the `files` directory to `static`, and that we mention files go inside the `static` folder for the above reasoning. I could be wrong.

Open to pull requests to promote the raw plugin more.

**Comment by Ziflin** [comment]
Just as a note, I was confused by this as well just starting with DocPad.  It was my assumption that the purpose of the 'files' directory was just to be a straight copy from it to the 'out' folder basically. What is being done to files in the 'files' folder that makes things slow?

**Comment by balupton** [comment]
DocPad loads the the entire file into memory for querying and referencing. That is what makes it slow.

**Comment by SteveMcArthur** [comment]
@balupton Is this an argument for the raw plugin being part of the core functionality?

**Comment by SteveMcArthur** [comment]
@balupton having scrolled up and looked at you previous comments. I think the raw plugin should come automatically with a docpad installation - unless removed. I would call this making it part of the core functionality. Its not the same as partials. If someone wants to use partials they may google "docpad partial" but if a user thinks docpad is slow they may just give up ("it doesn't work")

**Comment by dimitarkolev** [comment]
Raw plugin is very slow as well consider using docpad-plugin-copy if you
want speed.

**Comment by Zearin** [comment]
@balupton:
> I think in the docs these days we have renamed the `files` directory to `static`, and that we mention files go inside the static folder for the above reasoning. I could be wrong.

Yes, we have renamed `files` to `static`.  (I helped convert much of the docs to the new name. ☻)


## Why isn’t `static`, uh, static?

> Perhaps the confusion here is to think that we can just replace the filesPaths concept with the raw plugin behaviour, when they do different things.
>
> Files in DocPad are for when you need a file loaded into the in-memory database for querying/accessing but when it doesn't need to be rendered or have a meta header. Raw plugin is for when you the files don't need to be touched at all.

I think this is extremely anti-intuitive.  

Given the folders `render` and `static`, it’s natural to assume that DocPad will be doing extra work with the stuff in `render`, and will treat the stuff in `static` like exactly that—static files.  


@balupton said:
> DocPad loads the the entire file into memory for querying and referencing. That is what makes it slow.

But earlier, he also said:
> \[The raw plugin\] doesn't need to be in the core, so it isn't. Just like partials. It can be handled fine by a plugin.

…Whoa!  Simply copying files from a source to a distination “doesn’t need to be in the core”, but loading an “entire file into memory for querying and referencing” *does?!*

That doesn’t make sense to me.


## A case for moving QueryEngine to a plugin

The Backbone/QueryEngine functionality *is* incredibly powerful. 

But as a newcomer, it was very distracting when I was learning basics of DocPad from the Beginner’s Guide.  At the time, I didn’t know BackBone, I didn’t know what QueryEngine was (or that it was built on BackBone), and the Beginner’s Guide seemed to assume that I knew both of these things.  I think that’s asking too much of a beginner.  

----

To me, the “basic” functionality of DocPad is this:

I get some basic templates (`layouts`), I have some static assets (`static`—no in-memory database magic assumed!), and DocPad assembles these into a site.  

That’s it.

Copying files is one of the simplest things a program can do with a file.  Several of the most popular rendering plugins—Markdown to HTML, Stylus to CSS, etc.—are things that I **always** use, but they are still plugins.  And QueryEngine functionality (DocPad `collections`) is even more complicated than rendering.  In the time since I started using DocPad, I’ve learned what Backbone is, and I’ve read the QueryEngine documentation—but I still rarely use it.

----

So, here is what I propose:

I think the QueryEngine functionality should:

* be a major highlight of DocPad,
* should be a plugin, and 
* receive a dedicated piece of documentation (separate from the Beginner’s Guide).  This documentation should also be expanded from what currently exists; it should explain that DocPad `collections` use something called QueryEngine, that QueryEngine is built on Backbone.js, and show several different examples of what this powerful plugin is capable of.

I think this change will benefit:

* **beginners**, because it will make the Beginner’s Guide much more beginner-friendly;
* **QueryEngine**, because users that discover it as “a plugin with its own documentation” will have a dedicated space to learn about what it is, and what it can do; and
* **DocPad**, because it will not have the overhead of QueryEngine unless the user has opted-in, and because it will be less intimidating to newcomers.

----

Thoughts?

**Comment by balupton** [comment]
Files and documents go into in memory database. Raw does not.
