### ISSUE TITLE
Replace `docpad-plugin-eco` with `docpad-plugin-ect`

### ISSUE THREAD

**Issue by Zearin** [docpad/docpad#951]
After looking into [`docpad-plugin-ect`](https://github.com/jeremyfa/docpad-plugin-ect), it appears to have identical functionality to [`docpad-plugin-eco`](https://github.com/docpad/docpad-plugin-eco), but superior performance.  

Should we consider making it the main recommendation in skeletons, and on the website?

**Comment by mikeumus** [comment]
One of our focuses now is making a faster SSG so this may be a good step towards that using ['docpad-plugin-ect'](https://github.com/docpad/docpad-plugin-eco). I'm for it.

**Comment by balupton** [comment]
+1

**Comment by balupton** [comment]
We should make the ect plugin an official plugin before doing this switch. We need to have any plugins we officially recommend to be controlled by us.

**Comment by balupton** [comment]
@jeremyfa would you be up for transferring the plugin to the `docpad` organisation we the community can take over maintenance?

**Comment by jeremyfa** [comment]
@balupton Sure! How do you want to proceed?

**Comment by dimitarkolev** [comment]
Just changed all my eco templates to ect and the generation time went from 580s to 890s. It's large and complex site, but be careful when suggesting ect instead of eco. For simple scenarios it might offer some benefit but in real life its even slower than eco.

**Comment by balupton** [comment]
Hrmm, we should verify that a ect docpad site is faster than an eco one.

For anyone who wants to run this experiment, they could use the script in https://github.com/pflannery/docpad-large-site-test to generate a 1000 page eco site, and then a 1000 page ect site, and compare the generation times.

**Comment by Zearin** [comment]
(I haven't run the experiment yet, but I will get to it soon…)

Wow. Given the superior performance of ECT in a non-DocPad environment, I wonder why all those speed gains turn into speed penalties when running as a plugin. 

Is something about DocPad's plugin infrastructure hamstringing the performance?

**Comment by Zearin** [comment]
(Still curious about this one…)

**Comment by balupton** [comment]
Plugin needs to be transferred to the docpad github org if they want to make it official
