### ISSUE TITLE
How to automatically insert metadata's' into blank files.

### ISSUE THREAD

**Issue by vsopvsop** [docpad/docpad#978]
Suppose I have 100 team members. 
I am creating a page for each of them. 
I have created 100 blank files with "their name.html" as file name.

Now I want to  insert two metadatas into the file automatically instead of opening each file and inserting --- on first line  and manually typing their name: "membername" and layout: "members" and then closing the metadata with --- 100 times.

example: insert these lines into a blank file

= = =
name: "<%= document.basename %>"
layout: "members"
= = =

Since when creating the blank file I have named it with the team members' name as basename.
Can the metadata automatically take the basename and insert it in the name: value pair?

Please help.

**Comment by derberg** [comment]
@vsopvsop so basename is actually one of the built in metadatas attached to the model. Check the full list: https://docpad.org/docs/meta-data

so in short, if you access the name like this: `collectionElement.name` then you can access its basename with `collectionElement.basename`. You do not need to assign basename to a name. Actually, with your scenario,  you do not need `name` metadata at all.

**Comment by pflannery** [comment]
@vsopvsop Do you generate a file for every user manually or do you generate them from a service using a script?

if generated from a script then it sounds like you need to write an importer that will generate documents for each users. See the tumblr plugin for a working example https://github.com/docpad/docpad-plugin-tumblr it pulls in posts and generates static documents with meta.

**Comment by vsopvsop** [comment]
I had used a simple shell script using > and >> to create those files. Thanks to all of you. Closing the issue.

**Comment by SteveMcArthur** [comment]
@vsopvsop The DocPad website itself does something similar to what you are trying to achieve in the docpad.coffee file (https://github.com/docpad/website/blob/master/docpad.coffee). Effectively it iterates through each document and modifys its metadata properties, like this:

					# Apply
					document
						.setMetaDefaults({
							layout
							standalone

							name
							title
							pageTitle

							url: urls[0]

							editUrl

							organisationDirectory
							organisation
							organisationName

							projectDirectory
							project
							projectName

							categoryDirectory
							category
							categoryName
						})
						.addUrl(urls)

You could also do this using one of the DocPad events. So given that, I think using a shell script is the wrong way to go.
