### ISSUE TITLE
Metadata not properly cleared on reload

### ISSUE THREAD

**Issue by Ziflin** [docpad/docpad#980]
I had some logic based on a metadata tag and noticed that if the tag wasn't being removed between reloads.  To reproduce:
- docpad run
- Set a metadata value in say "index.html.md"
  - test: "Hello"
- in a layout file, say "default.html.eco"
  - ....
  - <%= @document.test %>
  - ...
- Save and refresh the browser.
- Remove: _test: "Hello"_ and resave and refresh the browser.  It will still display the **old** _test_ value.

You must manually stop (ctrl-c) and restart docpad run to have it properly render without the old test value.  This caused me a few WTF moments :). It looks like docpad is caching the yaml/metadata values instead of properly clearly them each reload.

**Comment by dimitarkolev** [comment]
This bug is the same as #929

**Comment by fizzvr** [comment]
Agree :-1: 
>  This caused me a few WTF moments :).

**Comment by balupton** [comment]
Closing as dupe of #929

**Comment by balupton** [comment]
Closing as dupe of #521

**Comment by balupton** [comment]
Closing as dupe of #517
