### ISSUE TITLE
Install Guide: Remind user to create new folder before docpad run

### ISSUE THREAD

**Issue by basteln3rk** [docpad/docpad#987]
In the [docpad install guide](https://docpad.org/docs/install), step 4 is to "run docpad for the first time". This creates quite a number of files in the current directory, which was not clear from the install guide.

Perhaps this could be changed to read: "Create a new directory for your first docpad run, and then execute ``docpad run`` from this directory." - or words to the effect

**Comment by balupton** [comment]
> Perhaps this could be changed to read: "Create a new directory for your first docpad run, and then execute docpad run from this directory." - or words to the effect

Hrmm, DocPad should only start adding files if it was already inside an empty directory? Was this not the case for you?

**Comment by mikeumus** [comment]
Yeah that's how it works @balupton, as you described. I think what @basteln3rk is saying is that `docpad run` will exit the install if there is even a `.git` in the folder which gets in my way sometimes too.
