### ISSUE TITLE
Docpad generate hangs since v6.76.0 when run from Grunt

### ISSUE THREAD

**Issue by damirarh** [docpad/docpad#988]
After updating DocPad to version 6.76.0 or more recent, running `docpad generate --env static` from Grunt never exits after outputting `info: Shutting down... cya next time!`.

Here's how to reproduce it:
- Inside an empty directory call `docpad run`, select skeleton 1 (because it uses DocPad v6.75.2). `Ctrl+C` after it's done, to break back into command line.
- Save `Gruntfile.coffee` with the following contents to the same directory:

``` coffeescript
module.exports = (grunt) ->
  grunt.initConfig(
    {
      shell:
        docpad:
          options:
            stdout: true
          command: "docpad generate --env static"
    }
  )

  grunt.loadNpmTasks('grunt-shell')

  grunt.registerTask('default', ['shell:docpad'])
```
- Install `grunt` and `grunt-shell`:

``` dos
npm install --save-dev grunt
npm install --save-dev grunt-shell
```
- Call `grunt` to execute default target - it will behave as expected: **DocPad will quit.**
- Update DocPad to v6.76.0: `npm install docpad@6.76.0`
- Call `grunt` again - this time **DocPad will hang indefinitely** after it's done.

**Comment by MattKotsenas** [comment]
I'm seeing the same behavior

**Comment by balupton** [comment]
This will be ratified in v6.80.7 which will be out momentarily.

**Comment by balupton** [comment]
Took a bit longer than expected. But v6.80.7 is now out.
