### ISSUE TITLE
Docpad server does not work

### ISSUE THREAD

**Issue by varya** [docpad/docpad#989]
I used docpad@6.69.2 with node 0.10, and everything worked OK. This is the code of the website https://github.com/varya/varya.github.com/tree/develop

Not I'm switching to node 0.12 and docpad@6.78.1. When I am running `docpad run` or `docpad server`, it generates into `./out` correctly and runs the server. But the server does not show anything. If requesting any page in a browser, it always shows that it's loading.

On the other hand, if I run a simple server in the `./out` directory manually, I see the needed website.
So, the problem must be with the server which is run by docpad.

What could be an error?

**Comment by varya** [comment]
My problem was using `gulp-shell` which did not emit finishing event (https://github.com/sun-zheng-an/gulp-shell/issues/5). I fixed this using `gulp-run` instead.

**Comment by fizzvr** [comment]
:beer:
