### ISSUE TITLE
An error occured within the child DocPad instance: spawn C:\Program Files\nodejs ENOENT

### ISSUE THREAD

**Issue by jash4** [docpad/docpad#991]
I'm on windows 7 machine and having similar issue like #944  

https://github.com/docpad/docpad/issues/944

`node -v  returns 
     v0.12.7`
`npm -v returns 2.11.3`

`docpad -V`
`v6.78.1 (global installation: C:\Users\x\AppData\Roaming\npm\node_modules\docpad`

After having installed docpad globally

`info: Installed the skeleton succesfully`
`notice: Shutting down the global DocPad, and starting up the local`

I' am able to execute docpad run successfully and subsequently selecting "No Skeleton Template"

Further running  **docpad run** terminates after giving following error

```
  An error occured within the child DocPad instance: spawn C:\Program Files\nodejs ENOENT
```

Instead when I run local docpad package using  **_npm start**_ It is working perfectly.

---

Even installing docpad plugins gives the same error 

``` javascript

docpad install eco

An error occured within the child DocPad instance: spawn C:\Program Files\nodejs ENOENT
```

tried installing node and docpad several times but the issue still persists

**Comment by balupton** [comment]
Strange, will you be around tomorrow? Perhaps I can remote in.

Seems like for some reason docpad can't find where your node executable is. For now, try just running docpad with the `--global` flag, so `docpad run --global`

**Comment by balupton** [comment]
Closing due to age. Ecosystem has likely fixed this. Try again with v6.80 or later.
